// Diário de bordo do CONTROL APP (núcleo) — invoices, rides, clientes,
// custos: o sistema maduro que roda a operação. SEM número de versão e SEM
// selo, por regra do Márcio (20/ago): retro-versionar 1.094 commits desde
// mai/2026 seria ficção — o git é a história real; só FINANCIAL
// (lib/finVersion) e DATA CHECK (lib/dcVersion) carregam selo, por serem
// produtos em construção. Upgrade do núcleo ganha uma linha datada aqui.
export const APP_CHANGELOG: { date: string; notes: string }[] = [
  {date: "2026-09-14",notes: "A TRAVESSIA US ⇄ BR SAI DO EDITOR E VAI PARA O MOTOR (lei sagrada de 13/set: todo PAID FROM/TO entre as empresas vira shopping invoice no app do outro). O save do editor de invoice não escreve mais a 085.N do BR à mão: chama /api/crossing só para a chave daquela invoice, e o motor (lib/crossing.server.ts) grava o que falta — linha nova, elo, câmbio carimbado UMA vez, Pending balance — sem nunca apagar e recriar linha espelhada nem recalcular R$/US$ gravado. O espelho velho (app/api/br-mirror/shopping), que refazia itens e pendente e reconvertia todo R$ pelo dólar do dia a cada save, aposentou (fica só para a aba velha, rodando o motor). PAID/UNPAID direto no banco também chama o motor, solto. Item espelho (mirror_src) sai da margem viva, e linha com elo da travessia não é apagada sem perguntar (REMOVE, grupo, kit, scan que substitui) nem mandada ao estoque. Cron novo /api/cron/crossing de hora em hora (minuto 47), no máximo 15 chaves e 200 s por rodada, parando na primeira que erra. No motor: chaves SEGURAS numa lista de uma linha por pergunta (US.001.1, US.009.1, US.007.1), a season com voo «VALOR A CONFIRMAR» ou linha sem data trava com o motivo, a renda da BR.537.1 vale US$ 1.402,00 (usd_rate gravada da invoice, antes da regra do IOF), o câmbio resolve cada data no dia exato, o pendente desconta as outras rendas em aberto, a manchete lista o dinheiro parado por chave travada e a impressão digital leva os pares. TRAVESSIA_PAUSADA=1 segura as escritas automáticas."},
  {date: "2026-09-14",notes: "PAGADOR SÓ ONDE HÁ ESCOLHA (onda 10 do pacote PAID FROM/TO, Márcio, 11/set). A régua por tabela mora em lib/payerRule.ts e a tela e os robôs leem a mesma: invoice_expenses, assets, assets_expenses e staff_expenses mostram só PAID FROM (PAID TO é GZ28US escondido); invoice_incomes só PAID TO; SUPPLIES, ESTOQUE e CUSTO FIXO não mostram pagador nenhum (os dois GZ28US escondidos); estoque DOADO não tem pagador. UM campo por fato: o seletor legado SourceSelect, que gravava só o SOURCE ao lado do PAID FROM, saiu de SUPPLIES (novo/edição) e virou PaidFromSelect — o único pagador da linha, gravando paid_from e espelhando o SOURCE — na despesa extra de asset (novo/edição), no REVIEW PURCHASE do scan de GOODS e do editor de invoice e no EDIT PURCHASE do editor (que abria o pedido pelo SOURCE e reescrevia calado um paid_from GZ28BR como GZ28US; vazio agora fica vazio). O ESCONDIDO GRAVA na linha nova e quando o pagamento nasce com o campo vazio — nunca por cima de um valor gravado: PAID IN? do editor de invoice, EDIT PURCHASE (banco E tela, que antes seguia sem o PAID TO até recarregar), edição de despesa, despesa da frota em /goods e na página do carro (insert e EDIT), data do pedido em GOODS/SUPPLIES/ESTOQUE, scan de SUPPLIES (nascia sem pagador nenhum), SEND TO STOCK/GOODS (o asset leva o pagador da despesa de origem), pack que vira invoice, geradores de parcelas de custo fixo e da folha prevista, e os robôs: recibo de app por e-mail, «comprovante = paga», imposto de importação, fila de compras, folha, passagem de staff e o lançamento do AutoBook. Os números medidos e congelados em comentários saíram."},
  {date: "2026-09-10",notes: "FIN SYNC ▸ AUTOBOOK ganha o LIVRO DO ROBÔ (pedido do Márcio): as regras do AutoBook, que moravam espalhadas em comentários de código, em três tabelas e nas notas da Claudinha fora do app, passam a ter um lugar só — em sequência, do e-mail que chega à linha registrada, mais as outras bocas (Zelle, papel sem e-mail, grupos do BR). Cada regra traz o estado (NO AR, À MÃO, EM CONSTRUÇÃO, FURO), a fala do Márcio quando ele a ditou e a função que a executa; busca e filtro por estado. Fonte única em lib/autoBookLivro.ts; a página só desenha."},
  {date: "2026-09-10",notes: "Menu principal ganha a cortina FIN SYNC (pedido do Márcio), com o primeiro item AUTOBOOK (/fin-sync/autobook) — página vazia, marcada EM DESENVOLVIMENTO até o escopo ser definido."},
  {date: "2026-08-25",notes: "Caso Drácula, ato 2 (João: \"continua igual — por quê?\"): o editor de INVOICE nem usa o PaymentFields consertado — tinha os PRÓPRIOS defaults fabricados em três camadas: ao carregar a invoice, ao salvar a despesa do modal e, a pior, ao salvar a invoice INTEIRA (qualquer salvamento gravava GZ28US em TODA despesa sem resposta). Agora as três camadas contam a verdade: vazio aparece \"— quem pagou? —\" (âmbar), salvar mantém NULL, e o default GZ28US ficou só na despesa NOVA. O source legado acompanha (espelho do paid_from, NULL quando não há resposta)."},
  {date: "2026-08-25",notes: "Caso Drácula (João, na 1ª rodada do Data Checker): o formulário de edição mostrava PAID FROM \"GZ28US\" numa despesa cujo paid_from era NULL no banco — o paymentFromRow fabricava o default ao carregar, a tela parecia preenchida (o Data Checker acusava e ESTAVA CERTO) e qualquer salvamento gravava o fabricado como dado real. Agora editar mostra a verdade: vazio vira \"— quem pagou? —\" / \"— de quem é a conta? —\" com borda âmbar, e salvar sem escolher mantém NULL. O default GZ28US continua no lançamento NOVO (defaultPayment), que é onde o Márcio o quis."},
  { date: '2026-08-24', notes: 'Untangle do catálogo: source_type volta a ser só ORIGEM (SCAN/HUNT/MANUAL/INVOICE, com constraint); o cadeado vive em locked_at/locked_by e o kit em is_kit — badge e isLockedPart atualizados (tolerantes ao legado até a migration), TRAVAR/DESTRAVAR não altera mais a origem, kit novo nasce MANUAL+is_kit. Categoria ganha vocabulário fechado de 13 valores (lib/partsMeta).' },
  { date: '2026-08-24', notes: 'Identidade de peças no núcleo (pré-P1 do Crew Chief): STREAM e INPUTS/NEW ganham o PART PICKER — a entrada escolhe a peça do catálogo e já nasce linkada (part_id), preenchendo nome/fornecedor; e a página PARTS ganha TRAVAR/DESTRAVAR com trilha (parts-lock): travar = "dados conferidos", congela; destravar exige confirmação e fica registrado com autor. O cadeado que o Márcio inventou pra se proteger dele mesmo, agora com recibo.' },
  { date: '2026-08-21', notes: 'Invoice: trava do fechamento (data de hoje oferecida) e selo ATRASADA/EM ATRASO passam a usar o relógio de Orlando com fuso fixo — antes seguiam o fuso do navegador, o que quebraria no Brasil.' },
  { date: '2026-08-20', notes: 'Editor de invoice: ADD PENDING BALANCE sempre visível — cinza com NADA PENDENTE (e tooltip) quando os incomes já cobrem o grand total; botão que some parece botão que sumiu.' },
  { date: '2026-08-20', notes: 'EXPECTED CONCLUSION DATE no invoice (MIGRATION_invoice_expected_conclusion.sql): a previsão ganha campo próprio, o banner PROMISED TO muda de casa e delivery/conclusion viram só fato. Selo de prazo no invoice: ATRASADA/ADIANTADA/NO PRAZO contra a previsão, EM ATRASO correndo quando ela vence sem conclusão.' },
  { date: '2026-08-20', notes: 'Diário de bordo criado: upgrades do núcleo saem do changelog do FINANCIAL (que versiona só demonstrações). Em produção desde mai/2026 — 1.094 commits até aqui; história completa no git.' },
]
