// Diário de bordo do CONTROL APP (núcleo) — invoices, rides, clientes,
// custos: o sistema maduro que roda a operação. SEM número de versão e SEM
// selo, por regra do Márcio (20/ago): retro-versionar 1.094 commits desde
// mai/2026 seria ficção — o git é a história real; só FINANCIAL
// (lib/finVersion) e DATA CHECK (lib/dcVersion) carregam selo, por serem
// produtos em construção. Upgrade do núcleo ganha uma linha datada aqui.
export const APP_CHANGELOG: { date: string; notes: string }[] = [
  {date: "2026-08-25",notes: "Caso Drácula, ato 2 (João: \"continua igual — por quê?\"): o editor de INVOICE nem usa o PaymentFields consertado — tinha os PRÓPRIOS defaults fabricados em três camadas: ao carregar a invoice, ao salvar a despesa do modal e, a pior, ao salvar a invoice INTEIRA (qualquer salvamento gravava GZ28US em TODA despesa sem resposta). Agora as três camadas contam a verdade: vazio aparece \"— quem pagou? —\" (âmbar), salvar mantém NULL, e o default GZ28US ficou só na despesa NOVA. O source legado acompanha (espelho do paid_from, NULL quando não há resposta)."},
  {date: "2026-08-25",notes: "Caso Drácula (João, na 1ª rodada do Data Checker): o formulário de edição mostrava PAID FROM \"GZ28US\" numa despesa cujo paid_from era NULL no banco — o paymentFromRow fabricava o default ao carregar, a tela parecia preenchida (o Data Checker acusava e ESTAVA CERTO) e qualquer salvamento gravava o fabricado como dado real. Agora editar mostra a verdade: vazio vira \"— quem pagou? —\" / \"— de quem é a conta? —\" com borda âmbar, e salvar sem escolher mantém NULL. O default GZ28US continua no lançamento NOVO (defaultPayment), que é onde o Márcio o quis."},
  { date: '2026-08-24', notes: 'Untangle do catálogo: source_type volta a ser só ORIGEM (SCAN/HUNT/MANUAL/INVOICE, com constraint); o cadeado vive em locked_at/locked_by e o kit em is_kit — badge e isLockedPart atualizados (tolerantes ao legado até a migration), TRAVAR/DESTRAVAR não altera mais a origem, kit novo nasce MANUAL+is_kit. Categoria ganha vocabulário fechado de 13 valores (lib/partsMeta).' },
  { date: '2026-08-24', notes: 'Identidade de peças no núcleo (pré-P1 do Crew Chief): STREAM e INPUTS/NEW ganham o PART PICKER — a entrada escolhe a peça do catálogo e já nasce linkada (part_id), preenchendo nome/fornecedor; e a página PARTS ganha TRAVAR/DESTRAVAR com trilha (parts-lock): travar = "dados conferidos", congela; destravar exige confirmação e fica registrado com autor. O cadeado que o Márcio inventou pra se proteger dele mesmo, agora com recibo.' },
  { date: '2026-08-21', notes: 'Invoice: trava do fechamento (data de hoje oferecida) e selo ATRASADA/EM ATRASO passam a usar o relógio de Orlando com fuso fixo — antes seguiam o fuso do navegador, o que quebraria no Brasil.' },
  { date: '2026-08-20', notes: 'Editor de invoice: ADD PENDING BALANCE sempre visível — cinza com NADA PENDENTE (e tooltip) quando os incomes já cobrem o grand total; botão que some parece botão que sumiu.' },
  { date: '2026-08-20', notes: 'EXPECTED CONCLUSION DATE no invoice (MIGRATION_invoice_expected_conclusion.sql): a previsão ganha campo próprio, o banner PROMISED TO muda de casa e delivery/conclusion viram só fato. Selo de prazo no invoice: ATRASADA/ADIANTADA/NO PRAZO contra a previsão, EM ATRASO correndo quando ela vence sem conclusão.' },
  { date: '2026-08-20', notes: 'Diário de bordo criado: upgrades do núcleo saem do changelog do FINANCIAL (que versiona só demonstrações). Em produção desde mai/2026 — 1.094 commits até aqui; história completa no git.' },
]
