// FIN SYNC ▸ AUTOBOOK — O LIVRO DO ROBÔ (Márcio, 10/set/2026).
//
//   "Quero que ali estejam listadas na sequencia, todas as regras que o robô usa
//    desde a detectção do income ou expense via email até estar registrado no app,
//    todos os passo do PROCESSAMENTO."
//   "Quero tudo do nosso AutoBook lá, tem que viver lá, se vive em outro lugar,
//    mova pra lá."
//
// ── POR QUE ESTE ARQUIVO EXISTE ────────────────────────────────────────────
// Até aqui as regras do AutoBook moravam em três lugares que ninguém lia junto:
//   • comentários espalhados em uns doze arquivos de código — o robô executa,
//     ninguém vê;
//   • três tabelas (auto_book_mail, auto_book_mail_rules, auto_book_mail_runs),
//     que guardam a fila, a regra aprendida e o pulso, não o porquê;
//   • as notas da Claudinha, FORA do app — onde o robô não alcança, e onde várias
//     regras moravam sozinhas (estorno como linha negativa, placeholder exportado,
//     destino pelo endereço de entrega, a pesca na conta da loja).
//
// Este arquivo é a fonte única do livro; a página /fin-sync/autobook só desenha o
// que está aqui. O código que executa cada regra continua onde está — mudar
// arquivo de lugar não ensina nada ao robô e quebra quem o importa. O que muda é
// que cada regra passa a ter UM texto, UM estado e o endereço de quem a executa.
//
// ── A DISCIPLINA ───────────────────────────────────────────────────────────
//   • Regra nova de AutoBook entra AQUI no dia em que é ditada: EM CONSTRUÇÃO se
//     o robô ainda não faz, À MÃO se quem faz é gente.
//   • O commit que põe a regra em código muda o estado dela para NO AR no MESMO
//     commit, com `onde` apontando a função que executa.
//   • Defeito conhecido em algo que está no ar é FURO, e o texto da regra diz o
//     comportamento CERTO; a nota diz o que acontece hoje.
//   • O `id` não muda ("5.2"): é por ele que conversa, recado e comentário de
//     código citam a regra. Regra nova entra no FIM da etapa.
//   • `fala` são as palavras DELE, literais. Sem fala conferida, fica sem fala.

export type Estado = 'NO AR' | 'À MÃO' | 'EM CONSTRUÇÃO' | 'FURO'

export const ESTADOS: { estado: Estado; diz: string }[] = [
  { estado: 'NO AR', diz: 'o robô faz sozinho, em produção' },
  { estado: 'À MÃO', diz: 'a regra vale, mas quem executa é gente: o Márcio ou a Claudinha' },
  { estado: 'EM CONSTRUÇÃO', diz: 'o robô ainda não faz; a nota diz se já foi pedido ao App development' },
  { estado: 'FURO', diz: 'o robô faz, com defeito conhecido; a nota diz o que acontece hoje' },
]

export type Regra = {
  id: string
  texto: string
  estado: Estado
  desde?: string   // quando a regra nasceu (dd/mm/aaaa)
  fala?: string    // as palavras do Márcio, literais
  onde?: string    // quem executa: arquivo · função · tabela
  nota?: string    // o caso, a medida, o que falta
}

export type Etapa = { id: string; titulo: string; resumo: string; regras: Regra[] }

export const LIVRO_ATUALIZADO = '2026-09-10'

// ═══ A SEQUÊNCIA — O CAMINHO DO E-MAIL DE COMPRA ATÉ A LINHA NO APP ═══════════
export const SEQUENCIA: Etapa[] = [
  {
    id: '0',
    titulo: 'ANTES DO E-MAIL',
    resumo: 'A parte da casa. É ela que deixa o robô saber de qual carro é a compra.',
    regras: [
      { id: '0.1', estado: 'À MÃO', desde: '27/07/2026',
        texto: 'Compra sempre logada na conta própria da loja, nunca como convidado. Criar conta, digitar senha e pagar é do Márcio.' },
      { id: '0.2', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'O documento da compra é salvo na pasta da invoice certa do carro certo: Rides/<carro>/Invoices/<código> - <nome>/. É esse arquivo que responde ao robô de qual carro e de qual invoice é a compra.',
        fala: 'eu salvo o invoice da compra na pasta da invoice certa do carro certo' },
      { id: '0.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Toda invoice de carro nasce com a sua pasta dentro de Invoices/, com o código e o nome dela. Quote não ganha pasta. Renomear a invoice ou renumerar o carro renomeia a pasta.',
        onde: 'app/api/ride-folder · invoice-folder' },
    ],
  },
  {
    id: '1',
    titulo: 'O ROBÔ ACORDA',
    resumo: 'Relógio próprio, janela com sobra e prova de que rodou.',
    regras: [
      { id: '1.1', estado: 'NO AR', desde: '06/09/2026',
        texto: 'O robô roda de hora em hora, com relógio próprio — fora do mail-poll de 5 minutos, que carrega 15 trabalhos em série e já deixou quem estava no fim da fila sem rodar.',
        fala: 'Precisamos automatizar ao máximo o AutoBook.',
        onde: 'vercel.json (0 * * * *) · app/api/cron/auto-book' },
      { id: '1.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Cada rodada lê as últimas 3 horas: as 2 horas de sobra cobrem a rodada que falhou e o e-mail que chega na virada, e repetir não duplica nada. Para recuperar uma rodada perdida, ?horas=N vai até 168 e a rodada fica marcada como humana.',
        onde: 'app/api/cron/auto-book' },
      { id: '1.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Prova de vida: a rodada abre uma linha RUNNING antes de trabalhar e fecha DONE ou ERROR com os contadores. Sem essa linha, fila vazia não diz se o robô rodou; RUNNING velho é rodada que morreu no meio.',
        onde: 'auto_book_mail_runs · abreRodada / fechaRodada',
        nota: 'Medido em 10/09/2026: 90 rodadas registradas; nos últimos 7 dias, 89 DONE e 1 ERROR.' },
      { id: '1.4', estado: 'NO AR', desde: '10/09/2026',
        texto: 'A rota do relógio só roda para o cron da Vercel (CRON_SECRET) ou para quem tem a chave de leitura — é essa chave que mantém possível a rodada humana de ?horas=N. Sem nenhuma das duas, 401.',
        onde: 'app/api/cron/auto-book',
        nota: 'Até 10/09 não conferia: qualquer um com a URL disparava uma varredura de até 168 horas, que lê as caixas e arquiva e-mails (achado da sessão do João). Fechada no mesmo dia, com o aval do Márcio, junto com a rota do marketing kill.' },
      { id: '1.5', estado: 'FURO', desde: '10/09/2026',
        texto: 'Caixa sem token ou com erro de API é erro da rodada, nunca caixa vazia.',
        onde: 'lib/autoBookMail.server.ts · lerCaixa · lib/streamMail.server.ts · fetchRecentMessages',
        nota: 'Hoje a caixa morta volta com zero mensagens e a rodada fecha DONE: as caixas podem morrer uma a uma sem aviso (achados 1 e 2 do João).' },
    ],
  },
  {
    id: '2',
    titulo: 'RECEBE O E-MAIL',
    resumo: 'As caixas conectadas, com o corte do BR e a proteção do arquivo de compras.',
    regras: [
      { id: '2.1', estado: 'NO AR',
        texto: 'Lê todas as caixas conectadas ao app — hoje são 6. Se a caixa é Outlook ou Gmail sai do cadastro dela, nunca do número do slot.',
        onde: 'stream_mail_auth · listMailAuths / mailProvider' },
      { id: '2.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'No Gmail a busca é pela COMPRA, não só pelo despacho: era lá que moravam os recibos da Amazon e da Home Depot, e a busca antiga só pedia e-mail de envio.',
        onde: 'lib/streamMail.server.ts · GMAIL_Q_COMPRA' },
      { id: '2.3', estado: 'NO AR', desde: '06/09/2026',
        texto: 'BR sem retroativo: e-mail das caixas do BR anterior a 06/09/2026 00:00 de Brasília não é processado nem vira pergunta. A trava mora no robô, não na janela — varredura larga não ressuscita o passado.',
        fala: 'pode processar as coisas do BR, mas sem retroativo, só daqui pra frente.',
        onde: 'lib/autoBookMail.server.ts · BR_FLOOR' },
      { id: '2.4', estado: 'NO AR', desde: '04/09/2026',
        texto: 'Caixa marcada para não ser varrida — a 6, gz28shopping, arquivo de compras do BR — é lida, mas nenhum robô move nem apaga nada nela.',
        onde: 'stream_mail_auth.auto_sweep · maySweep' },
      { id: '2.5', estado: 'FURO', desde: '10/09/2026',
        texto: 'Nenhum recibo fica fora da leitura por excesso de e-mail na janela.',
        onde: 'lib/streamMail.server.ts · fetchRecentMessages / fetchRecentGmail',
        nota: 'Hoje o teto é 50 mensagens por caixa no Outlook e 60 no Gmail, sem paginação: uma onda de marketing empurra recibo real para fora, calado (achado 3 do João).' },
    ],
  },
  {
    id: '3',
    titulo: 'PENEIRA: SÓ PASSA DINHEIRO',
    resumo: 'Uma pergunta só: isso vira ou muda uma linha de dinheiro no app?',
    regras: [
      { id: '3.1', estado: 'NO AR', desde: '05/09/2026',
        texto: 'Passa compra, estorno e cobrança. Marketing, conversa e aviso sem compra morrem aqui, calados.',
        onde: 'lib/autoBookMail.server.ts · classify' },
      { id: '3.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Compra se reconhece pelo CONTEÚDO — um total de rótulo forte e um número de pedido —, nunca pelo formato do assunto. O assunto só reforça quando o valor não deu para ler.',
        onde: 'classify · COMPRA_ASSUNTO',
        nota: 'A primeira rodada leu 173 e-mails e achou zero com dinheiro, porque julgava a compra pelo assunto.' },
      { id: '3.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Recibo do PayPal: o valor está no ASSUNTO («HP Tuners LLC: $499.99 USD») e o fornecedor é o COMERCIANTE, sem LLC ou INC — nunca «paypal.com».',
        onde: 'paypalReceipt' },
      { id: '3.4', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Estorno só conta quando o vendedor afirma que devolveu («has been refunded»). «Refund policy» e «request a refund» são conversa.',
        onde: 'lib/mailToItem.server.ts · ESTORNOU' },
      { id: '3.5', estado: 'À MÃO', desde: '05/09/2026',
        texto: 'Não é gasto até pagar: orçamento, cotação, link de pagamento em aberto, backorder, contrato e e-sign não entram.',
        nota: 'O robô não separa cotação de compra quando as duas trazem total e número; quem responde a dúvida aplica a regra e ignora.' },
    ],
  },
  {
    id: '4',
    titulo: 'VALIDA AS INFORMAÇÕES',
    resumo: 'Pedido, valor, moeda e data — o que o e-mail precisa trazer para virar linha.',
    regras: [
      { id: '4.1', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Número do pedido só vale colado à palavra do pedido («order», «order ID», «pedido»), nos formatos reais da casa — eBay 12-12345-12345, Amazon 123-1234567-1234567, Temu PO-…, e 6 a 7 dígitos (HHP, HP Tuners, PayPal).',
        onde: 'lib/mailToItem.server.ts · PEDIDO_NOVO',
        nota: 'Formato largo pega telefone, CEP e pedaço de valor; por isso a lista é fechada.' },
      { id: '4.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Valor que autoriza lançamento só de rótulo FORTE: Order total, Grand total, Total paid, Valor pago. «Total» dentro de «Order Summary» vale como forte. Subtotal é o mais fraco de todos — com desconto, fica acima do que foi pago.',
        onde: 'parseMoney',
        nota: 'Caso HHP 384734: o robô leu o subtotal 1.444,75 no lugar dos 1.290,93 pagos.' },
      { id: '4.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Um e-mail, vários pedidos (Temu, «divided into N orders»): cada pedido fica com o SEU total, lido logo depois do número. Sem total colado ao número, o valor não é atribuído.',
        onde: 'totaisPorPedido' },
      { id: '4.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Número nos dois formatos: em «1,234.56» e «1.234,56» o último separador manda; três casas depois dele é milhar.',
        onde: 'parseNumber' },
      { id: '4.5', estado: 'NO AR', desde: '07/09/2026',
        texto: 'R$ ou BRL é real; o resto é dólar.',
        onde: 'parseMoney' },
      { id: '4.6', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Total 0,00 de rótulo forte — brinde, pedido pago com crédito da loja — não gera linha. O e-mail é arquivado.',
        onde: 'runAutoBookMail' },
      { id: '4.7', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O total do e-mail nunca vira preço de peça: lançar o total como preço único quebra preço × quantidade + imposto + frete e contamina o custo no Parts DB. A linha detalhada vem do documento (etapa 7).',
        nota: 'É por isso que a caça na pasta aponta a invoice, mas não lança sozinha.' },
      { id: '4.8', estado: 'À MÃO', desde: '08/09/2026',
        texto: 'A data do pagamento é o dia em que pagamos, e vem do recibo ou do e-mail do vendedor. A data do extrato é a do processamento; a data de um pedido ainda não pago não é pagamento.',
        fala: 'a data do pagamento é o dia que pagamos, o dia que aparece no banco deve ser a data de processamento, são 2 datas diferentes. Nunca o dia do pagamento é o mesmo do processamento.',
        nota: 'O robô ainda não grava a data do pagamento na linha que lança — ver 8.7.' },
    ],
  },
  {
    id: '5',
    titulo: 'JÁ EXISTE NO APP?',
    resumo: 'Antes de perguntar ou lançar, provar que não é duplicado.',
    regras: [
      { id: '5.1', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Pedido que já existe em qualquer tabela de item ou de custo fixo não é compra nova: o e-mail vira FATO daquela linha (rastreio, entrega, estorno) e é arquivado.',
        onde: 'pedidosConhecidos · lib/mailToItem.server.ts' },
      { id: '5.2', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O mesmo pedido escrito de dois jeitos é o mesmo pedido: só letras e números, e também a forma sem zeros à esquerda quando sobram 5 ou mais caracteres (0430475 = 430475).',
        onde: 'formasDoPedido' },
      { id: '5.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Assinatura é do SUBSCRIPTIONS: o remetente casa pelo DOMÍNIO cadastrado no prestador. Já lançada em até 6 dias, arquiva; não lançada, vira aviso. Nunca pelo nome no texto — o app escreve «Claude», não «Anthropic».',
        onde: 'appsPorDominio / assinaturaLancada',
        nota: 'Na primeira rodada boa, 10 das 11 perguntas eram recargas já lançadas.' },
      { id: '5.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Recibo do PayPal sem pedido, com linha do mesmo comerciante em até 6 dias, é o pagamento de uma compra já lançada: arquiva. Recibo nunca se confere por valor exato — o app parte a compra em preço + imposto + frete e rateia entre carros.',
        onde: 'temLinhaPorPerto',
        nota: 'Conferir por valor exato deu 4 alarmes falsos em 04/09.' },
      { id: '5.5', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Antes de perguntar, procura por VALOR + fornecedor, 15 dias para cada lado, nas 7 tabelas de gasto — a maioria das linhas nasce sem número de pedido. Achou, arquiva.',
        fala: 'ponha o robô pra vasculhar o app pra esta nova despesa; se não encontrar, verificar as pastas PURCHASES dos carros; só se não encontrar nestes 2 lugares, isto fica em dúvida.',
        onde: 'achaNoApp' },
      { id: '5.6', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Nunca pergunta duas vezes: cada e-mail, e cada pedido dentro dele, tem chave única.',
        onde: 'auto_book_mail.message_key' },
      { id: '5.7', estado: 'NO AR', desde: '07/09/2026',
        texto: '«Não achei» diz ONDE procurou: a pergunta lista as tabelas, os bancos e as pastas consultados.',
        onde: 'runAutoBookMail' },
      { id: '5.8', estado: 'FURO', desde: '07/09/2026',
        texto: 'Compra já lançada no app do BR não vira pergunta.',
        onde: 'pedidosConhecidos',
        nota: 'Hoje o robô só consulta o banco do US, e a pergunta sai com o aviso «CONFERIR NO APP DO BR». Falta a chave de serviço do BR no Vercel do US (SUPABASE_BR_SERVICE_ROLE_KEY).' },
    ],
  },
  {
    id: '6',
    titulo: 'VAI NAS PASTAS',
    resumo: 'Papel salvo por gente é resposta dada. A pasta vem antes da estatística.',
    regras: [
      { id: '6.1', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A pasta da invoice é o PRIMEIRO lugar de caça. O arquivo salvo ali responde de qual carro e de qual invoice é a compra — e vale mais que o histórico do fornecedor.',
        fala: 'o primeiro lugar que o robô tem que caçar é nas pastas das invoices',
        onde: 'lib/dropboxHunt.server.ts · cacaNaPasta',
        nota: 'Caso Summit, 08/09: o histórico apontava três carros, todos errados; a pasta apontou o SublimeHell.' },
      { id: '6.2', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Procura pelo NOME do arquivo nas duas raízes: /001 - GZ28US/GZ28US Rides e /000 - GZ28BR/GZ28BR Rides.',
        onde: 'cacaNaPasta' },
      { id: '6.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Três forças de evidência: ORDEM (o número do pedido está no nome — decide), RECENTE (nome do fornecedor e arquivo salvo até 12 horas do e-mail — decide se for a única) e FORNECEDOR (outra época — só ordena as sugestões). A força mais alta presente decide sozinha.',
        onde: 'respostaUnica' },
      { id: '6.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A hora do arquivo é a da mão de quem salvou (client_modified), nunca a do servidor do Dropbox, que muda a cada ressincronização.',
        onde: 'cacaNaPasta' },
      { id: '6.5', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Procura com o nome que veio no e-mail E com o nome do cadastro e seus apelidos, porque a pasta é nomeada com o nome curado. Apelido vai inteiro; no máximo 4 termos.',
        onde: 'termosDeBusca',
        nota: 'Caso HHP 384734: o robô procurou «Highhorseperformance» e o arquivo estava salvo como «HHP».' },
      { id: '6.6', estado: 'NO AR', desde: '09/09/2026',
        texto: 'O nome que voltou tem de conter todas as palavras do termo procurado — o Dropbox afrouxa a busca e devolve arquivo de outra loja.',
        onde: 'nomeConfirma' },
      { id: '6.7', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Carro e invoice saem do CAMINHO do arquivo. Purchases/ guarda o papel do carro que ainda não tem invoice definida.',
        onde: 'leCaminho' },
      { id: '6.8', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Procura também nos recibos já guardados no app, pelo pedido ou pelo fornecedor no nome. Achou: «o papel está guardado, falta a linha».',
        onde: 'achaPapel' },
      { id: '6.9', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O histórico do fornecedor — onde foram parar as compras anteriores, com a contagem real — só entra depois da pasta, como sugestão.',
        onde: 'candidatosPara' },
      { id: '6.10', estado: 'FURO', desde: '10/09/2026',
        texto: 'Falha do Dropbox é erro da caça, não da rodada.',
        onde: 'runAutoBookMail',
        nota: 'Hoje uma falha de autenticação do Dropbox fecha a rodada como ERROR mesmo com a pergunta registrada certa (achado 5 do João; foi o único ERROR da semana).' },
    ],
  },
  {
    id: '7',
    titulo: 'LÊ O DOCUMENTO E PESCA O QUE FALTA',
    resumo: 'A pasta diz QUAL invoice; o documento diz O QUE lançar.',
    regras: [
      { id: '7.1', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O robô baixa o documento que achou na pasta e lê com o mesmo leitor do botão SCAN: item, quantidade, desconto, imposto e frete, linha a linha.',
        onde: 'app/api/auto-book/ler-pasta · app/api/scan-receipt',
        nota: 'A leitura existe desde 09/09; o robô de hora em hora ainda não a chama. Especificação dos 10 passos entregue ao App development em 09/09.' },
      { id: '7.2', estado: 'NO AR',
        texto: 'Rateio do documento: imposto e frete divididos na proporção do valor de cada linha; o centavo que sobra fica na última; a soma das linhas fecha o total pago ao centavo.',
        onde: 'app/api/scan-receipt' },
      { id: '7.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Desconto de linha é PERCENTUAL: arredonda((1 − pago ÷ lista) × 1000) ÷ 10. O preço da linha é o custo já pago.',
        onde: 'app/api/scan-receipt',
        nota: 'Três telas subtraíam o percentual como se fosse dinheiro; corrigido em 07/09.' },
      { id: '7.4', estado: 'À MÃO', desde: '19/08/2026',
        texto: 'Sem documento na pasta e com e-mail cego, pesca-se na conta da loja: Temu pelo detalhe do pedido; Amazon pelo apelido do endereço de entrega; eBay pelo detalhe do pedido em order.ebay.com.',
        nota: 'Feito pela Claudinha, no navegador logado.' },
      { id: '7.5', estado: 'À MÃO',
        texto: 'Ele loga, a Claudinha opera: senha, CPF, cadastro e captcha só o Márcio digita.' },
      { id: '7.6', estado: 'À MÃO', desde: '31/08/2026',
        texto: 'No site o valor é o total do pedido: o «saved $X» da Temu não é valor, e pedidos em sequência do mesmo vendedor no eBay são UM pedido — somar os números triplica.' },
    ],
  },
  {
    id: '8',
    titulo: 'REGISTRA NO LUGAR CERTO',
    resumo: 'Na invoice certa, na tabela certa, com os campos certos — e sem deixar nada duplicado.',
    regras: [
      { id: '8.1', estado: 'NO AR', desde: '10/08/2026',
        texto: 'Tudo gira em torno de invoice: a primeira pergunta de todo lançamento é «qual invoice?». Na dúvida de onde lançar, pergunta.',
        onde: 'a pergunta da etapa 12' },
      { id: '8.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Lança sozinho SÓ com as três juntas: regra escrita por gente, valor de rótulo forte e número do pedido. Nunca escolhe carro por conta própria.',
        onde: 'lancar · auto_book_mail_rules',
        nota: 'Medido em 10/09: nenhuma regra aprendida ainda — todo lançamento até hoje veio de resposta humana.' },
      { id: '8.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Cada tabela com a sua coluna de valor: price na invoice, amount em expenses, unit_price em supplies. Trocar grava zero.',
        onde: 'lancar' },
      { id: '8.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O fornecedor entra com o nome do CADASTRO; sem cadastro que case, entra o nome como veio — inventar é pior. A cura é só na escrita: a busca no banco usa o nome cru, que é o que está lá.',
        fala: 'normalize sempre os nomes dos fornecedores, ensine todos os robôs de escaneamento a fazer isso, assim os dados já entram certos',
        onde: 'lib/supplierMatch.ts · matchSupplier' },
      { id: '8.5', estado: 'NO AR', desde: '04/08/2026',
        texto: 'Número do pedido sempre, na coluna própria. Pedidos nunca se juntam: uma cobrança do PayPal com dois pedidos vira duas linhas.',
        fala: 'every single purchase/expense, not only inputs, every single expense should have the order number field',
        onde: 'lancar' },
      { id: '8.6', estado: 'NO AR', desde: '18/08/2026',
        texto: 'A despesa tem UMA data: a do pagamento.',
        onde: 'app/rides/[id]/invoices/edit/[invoiceId] (expense_date espelha payment_date)' },
      { id: '8.7', estado: 'FURO', desde: '10/09/2026',
        texto: 'A linha lançada pelo robô nasce com a data do pagamento e com quem pagou.',
        onde: 'lancar',
        nota: 'Hoje nasce sem payment_date e sem paid_from: até o banco casar, fica fora de «quem pagou» e do fluxo de caixa (achado 8 do João).' },
      { id: '8.8', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Compra real apaga o que ela substitui: as despesas NÃO PAGAS contidas nesta compra saem, e fica só o que não estava nela. Só com casamento forte (fornecedor + valor + quantidade); o resto vira pergunta.',
        fala: 'o AutoBook cuida pra nas expenses não haver nada duplicado, ou seja, ele apaga as expenses não pagas contidas nesta compra, deixa só o que não estava nesta compra.',
        nota: 'Lei desde 10/08; passo 9 da especificação entregue ao App development em 09/09. Hoje é feito à mão.' },
      { id: '8.9', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'Se a despesa não paga já foi levada para ITEMS, a compra real entra POR CIMA dela: apagar romperia o elo com o item, e uma reimportação duplicaria os ITEMS.',
        nota: 'Caso HHP 384734, GoldenEye.' },
      { id: '8.10', estado: 'À MÃO', desde: '04/09/2026',
        texto: 'Estorno é uma linha NEGATIVA espelhando a original — mesmo pedido, mesmo comprovante, mesma categoria —, com a data do e-mail do estorno. A linha original nunca é editada para baixo.' },
      { id: '8.11', estado: 'À MÃO', desde: '27/08/2026',
        texto: 'Pedido com itens de destinos diferentes vira linhas separadas, rateadas pelo preço de cada item.' },
      { id: '8.12', estado: 'À MÃO', desde: '25/08/2026',
        texto: 'O endereço de entrega decide o destino: 4000 Headwaters (Luma) é APARTMENT; 11320 Space Blvd 2A é o galpão; entrega na PowerTrade Miami é compra do GZ28BR; bicho no galpão é CATS.' },
      { id: '8.13', estado: 'À MÃO', desde: '28/07/2026',
        texto: 'Custo de carro tem UM dono: seguro e uso da ferramenta de trabalho são da oficina; compra, documentação e custos de carro de patrimônio ou de cliente vão na invoice do próprio carro. O dinheiro sai uma vez e é lançado uma vez.',
        fala: 'se tem seguro é porque tem título e está EM USO DA OFICINA' },
      { id: '8.14', estado: 'À MÃO', desde: '03/09/2026',
        texto: 'No app do BR o valor é em REAIS; o dólar vai em amount_usd, convertido pela taxa da invoice. Depois de pago, o valor congela.',
        fala: 'depois que está pago, tem que ficar o valor que foi pago no dia, não pode variar mais.' },
      { id: '8.15', estado: 'NO AR', desde: '09/09/2026',
        texto: 'PAID FROM CLIENT: despesa, item e receita carregam o MESMO número, gravado no banco — não calculado na tela —, com o mesmo comprovante.',
        fala: 'não é a tela que tem que derivar, tem que estar gravado no banco certo.',
        onde: 'lib/clientPaidMirror.server.ts · app/api/cron/invoice-receipts' },
    ],
  },
  {
    id: '9',
    titulo: 'PARTS DB',
    resumo: 'A peça comprada entra no banco de peças — e a última compra manda no custo.',
    regras: [
      { id: '9.1', estado: 'À MÃO', desde: '03/09/2026',
        texto: 'Toda peça comprada entra no Parts DB sem perguntar, com tudo: apelido, descrição, número da peça, MAP, custo, fornecedor, desconto, o menor frete, peso e o link do produto. Auditada três vezes antes de gravar: a soma bate com o total pago, um número de peça é uma linha só, nenhum campo vazio e MAP maior ou igual ao custo.',
        fala: 'sempre! pra entrar no parts db, tem que ser com tudo, tudo, auditado triplamente, e badgeado assim.' },
      { id: '9.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A compra real da mesma peça no mesmo fornecedor atualiza o custo mesmo com cadeado. O cadeado continua onde estava.',
        fala: 'sempre que uma compra real é feita, da mesma peça, no mesmo fornecedor, tem que atualizar o valor da peça no parts db, mesmo que bloqueada.',
        onde: 'lib/partsDb.ts · enrollOne' },
      { id: '9.3', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A ÚLTIMA compra manda, promoção incluída; na próxima, se o valor for outro, atualiza de novo. O banco guarda o que foi pago da última vez — não a média, nem o melhor preço.',
        fala: 'sempre a última compra atualiza o parts db, mesmo que seja promo, na próxima compra, se o valor for outro, atualiza de novo.',
        onde: 'lib/partsDb.ts · enrollOne' },
      { id: '9.4', estado: 'À MÃO', desde: '05/08/2026',
        texto: 'O frete da peça no Parts DB é o MENOR possível — nunca o expresso de uma compra com pressa.' },
      { id: '9.5', estado: 'NO AR', desde: '08/07/2026',
        texto: 'O MAP que vale é o preço de lista impresso na nota real; ele revalida o MAP guardado.',
        onde: 'lib/partsDb.ts · enrollOne',
        nota: 'Sem nota, a caça de preço usa o eBay primeiro — à mão.' },
      { id: '9.6', estado: 'EM CONSTRUÇÃO',
        texto: 'O AutoBook atualiza o Parts DB sozinho depois de lançar a compra.',
        nota: 'Hoje o banco de peças só aprende pelo SCAN das telas ou à mão; o robô do e-mail não chama o cadastro de peças. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: '10',
    titulo: 'SALVA O COMPROVANTE',
    resumo: 'O documento do vendedor nos dois lugares, com o nome certo e sem cópia repetida.',
    regras: [
      { id: '10.1', estado: 'NO AR', desde: '24/08/2026',
        texto: 'O documento oficial do vendedor mora nos DOIS lugares: anexado na linha e na pasta da invoice. Sem os dois, o lançamento está incompleto.',
        fala: 'sempre o PRINTABLE INVOICE do vendedor nas expenses no app e na pasta purchases no dropbox.',
        onde: 'app/api/cron/invoice-receipts · app/api/ride-folder',
        nota: 'Desde 08/09 a pasta é a DA INVOICE; Purchases/ ficou só para o papel que não se sabe de qual invoice é.' },
      { id: '10.2', estado: 'À MÃO', desde: '26/07/2026',
        texto: 'É o documento REAL: o PDF do vendedor ou a versão printer-friendly da loja. Quando a prova é um e-mail, ele vira PDF — nunca HTML, nunca documento redigitado.' },
      { id: '10.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Compra dividida entre carros: toda linha leva o documento da compra INTEIRA, e o arquivo vai para a pasta de TODAS as invoices que entraram nela. O elo é fornecedor + número do pedido.',
        fala: 'toda compra rateada deve ter o arquivo em todas as pastas',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Nome canônico: [código da invoice] [carro] - [fornecedor do cadastro] [pedido].pdf. Quem nomeia é a rota, lendo o banco — renomear a invoice, renumerar o carro ou curar o fornecedor conserta os arquivos sozinho.',
        fala: 'Dentro desta pasta é onde devem ficar TODAS as invoices de expenses desta invoice, devidamente nomeadas, com o [cod invoice] [ride] - [supplier] [order #].',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.5', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Duplicata se mede pelo CONTEÚDO (content_hash), nunca pelo nome: não sobe de novo o que já está lá, apaga a cópia de nome velho com o mesmo conteúdo e tira da Purchases o que já está idêntico na pasta da invoice.',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.6', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O que não bate com documento nenhum FICA. Papel posto à mão não se apaga por dedução.',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.7', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Se o e-mail trouxer um documento MELHOR que o salvo na pasta, o robô anexa o novo, salva com o nome certo e mantém o arquivo original.',
        fala: 'pode ser que no email chegue uma invoice mais apropriada, se for este o caso o AutoBook registra no app esta invoice nova, salva na pasta com o nome certo e mantém o arquivo original meu lá',
        nota: 'Passo 8 da especificação entregue ao App development em 09/09.' },
      { id: '10.8', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O robô que lança anexa o comprovante na mesma hora.',
        fala: 'o AutoBook registra aquela compra na invoice em questão, anexando o comprovante',
        nota: 'Hoje a linha lançada por regra nasce sem comprovante, e a fila registra «falta a printable invoice». Passo 7 da especificação de 09/09.' },
      { id: '10.9', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Quem escreve direto no banco também leva o papel: de 2 em 2 horas, toda invoice cuja despesa com comprovante mudou nas últimas 6 horas tem a pasta sincronizada.',
        onde: 'vercel.json (23 */2) · app/api/cron/invoice-receipts' },
      { id: '10.10', estado: 'NO AR', desde: '01/08/2026',
        texto: 'Comprovante anexado = despesa paga: a data do pagamento entra sozinha, a cada 5 minutos.',
        fala: 'Se tem comprovante, está PAGA.',
        onde: 'lib/expenseReportNet.server.ts · enforceReceiptPaid' },
    ],
  },
  {
    id: '11',
    titulo: 'ARQUIVA O E-MAIL',
    resumo: 'Resolvido sai da caixa; pergunta aberta fica à vista.',
    regras: [
      { id: '11.1', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O que o robô resolve sai da caixa na mesma passada. O que virou pergunta fica na caixa de entrada até ser respondido.',
        fala: 'porque tem tanto email da sua pauta ainda na minha caixa?',
        onde: 'lib/autoBookMail.server.ts · arquiva' },
      { id: '11.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Destino em degraus: a pasta do FORNECEDOR e, sem ela, «Purchases». O robô nunca cria pasta; sem destino, reporta.',
        onde: 'arquiva' },
      { id: '11.3', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Fechado o lançamento, a THREAD inteira daquela compra vai para a pasta do carro. O que entra é a compra — pedido, fatura, assunto —, nunca todos os e-mails do fornecedor.',
        fala: 'ah, e o AutoBook processa os emails referente a esta compra, guarda todos na pasta do carro.',
        nota: 'Passo 11, entregue ao App development em 09/09. A rota que arquiva já existe (/api/stream/mail-file); falta o robô chamá-la. Hoje é feito à mão.' },
      { id: '11.4', estado: 'FURO', desde: '02/09/2026',
        texto: 'Processado = na pasta E marcado: a marca d’água diz o que o e-mail virou (tabela e linha).',
        fala: 'todos os emails processados devem ir pra sua pasta e marcados como processados',
        onde: 'app/api/stream/mail-file · mail_processed',
        nota: 'A rota de arquivar grava a marca sozinha; o robô de hora em hora move o e-mail direto no Outlook e não deixa marca.' },
      { id: '11.5', estado: 'EM CONSTRUÇÃO',
        texto: 'As caixas do Gmail também são arquivadas pelo robô.',
        onde: 'arquiva',
        nota: 'Hoje só as caixas Outlook. A rota de arquivar já sabe mover no Gmail desde 04/09. Ainda não pedido ao App development.' },
      { id: '11.6', estado: 'À MÃO', desde: '04/08/2026',
        texto: 'Processar inclui os ENVIADOS: e-mail que mandamos sobre a compra vai para a mesma pasta da thread.',
        fala: 'PROCESS means all emails, not only the incoming ones!' },
    ],
  },
  {
    id: '12',
    titulo: 'A DÚVIDA',
    resumo: 'O robô só faz sozinho o que não precisa de decisão. O resto vira pergunta com lugar, e a resposta vira regra.',
    regras: [
      { id: '12.1', estado: 'NO AR', desde: '06/09/2026',
        texto: 'Não resolveu sozinho: UMA pergunta na fila, com fornecedor, pedido, valor, moeda, o que falta e onde procurou. Dinheiro nunca some calado — não existe terceira saída.',
        fala: 'ensine o robô a fazer o round de 1 em 1 hora, pra que ele deixe pra vc aqui só o que ele tiver dúvida.',
        onde: 'auto_book_mail (status DOUBT)',
        nota: 'Medido em 10/09: 1 dúvida aberta, 7 lançadas, 10 ignoradas.' },
      { id: '12.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'As sugestões de destino vêm medidas: primeiro a PASTA, com o arquivo que provou; depois o HISTÓRICO do fornecedor, com a contagem real. Número inventado, nunca.',
        onde: 'candidatosDaPasta / candidatosPara' },
      { id: '12.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'A resposta resolve o e-mail (lança ou ignora) e, marcada para aprender, vira regra: o mesmo caso nunca mais é perguntado.',
        onde: 'POST /api/auto-book · auto_book_mail_rules' },
      { id: '12.4', estado: 'FURO', desde: '10/09/2026',
        texto: 'Regra aprendida tem teto de valor, validade e desfazer.',
        onde: 'lancar · auto_book_mail_rules',
        nota: 'Hoje a regra nasce de UMA resposta, sem teto nem validade, e o que ela lança não deixa trilha para desfazer (achado 4 do João).' },
      { id: '12.5', estado: 'EM CONSTRUÇÃO',
        texto: 'A fila de dúvidas tem tela.',
        nota: 'Hoje só a Claudinha lê a fila. Candidata a próxima aba desta página.' },
    ],
  },
  {
    id: '13',
    titulo: 'DEPOIS DE REGISTRADO',
    resumo: 'Report, rastreio e conferência — o que acontece com a linha depois que ela existe.',
    regras: [
      { id: '13.1', estado: 'NO AR', desde: '01/08/2026',
        texto: 'Report no grupo SÓ quando o dinheiro entra ou sai agora — a data do dinheiro nos últimos 3 dias. Lançamento retroativo, correção e edição são silêncio.',
        fala: 'ENTROU ou SAIU $? REPORT.',
        onde: 'lib/expenseReportNet.server.ts · runExpenseReportNet' },
      { id: '13.2', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Rastreio, entrega e estorno moram na LINHA da compra. O status BOUGHT, SHIPPED ou DELIVERED é calculado, nunca escrito.',
        fala: 'as infos de ORDER NUMBER, TRACKING e STATUS vivem nas origens das compras',
        onde: 'lib/mailToItem.server.ts · lib/deliverStatus.ts' },
      { id: '13.3', estado: 'NO AR', desde: '04/08/2026',
        texto: 'Depois de lançada a compra, os e-mails seguintes só atualizam fatos, casados pelo número do pedido: nunca sobrescrevem um rastreio que já existe e nunca desfazem entrega ou estorno.',
        onde: 'lib/mailToItem.server.ts' },
      { id: '13.4', estado: 'NO AR', desde: '30/08/2026',
        texto: 'A transportadora é perguntada de hora em hora pelos números de rastreio já gravados nas linhas.',
        onde: 'vercel.json (37 * * * *) · app/api/items/track' },
      { id: '13.5', estado: 'NO AR',
        texto: 'A linha do extrato do banco é ligada ao registro pelo AUTO-LINK (Bank Link, sessão do João), que só lança quando ninguém lançou.',
        onde: 'lib/bankReconcile.server.ts',
        nota: 'Outro robô: o AutoBook não lê o AUTO-LINK, nem o contrário.' },
      { id: '13.6', estado: 'NO AR', desde: '10/09/2026',
        texto: 'O Data Checker confere os dois robôs lado a lado e pergunta a gente quando eles discordam.',
        onde: 'lib/enginesAudit.server.ts · card «Os dois motores concordam?»' },
    ],
  },
]

// ═══ OUTRAS BOCAS — DINHEIRO QUE NÃO ENTRA PELO E-MAIL DE COMPRA ═════════════
export const OUTRAS_BOCAS: Etapa[] = [
  {
    id: 'A',
    titulo: 'ZELLE — RECEITA E PAGAMENTO',
    resumo: 'O dinheiro que entra ou sai por Zelle, lido do aviso do Regions.',
    regras: [
      { id: 'A.1', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Zelle nunca passa batido: a caixa inteira do gz28us@hotmail, em todas as pastas, é lida a cada 5 minutos, antes de qualquer robô arquivar.',
        fala: 'zelle is a serious thing, fix it, so it never happens anymore.',
        onde: 'lib/zelleWatch.server.ts · mail-poll' },
      { id: 'A.2', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Nunca duplica: o número de confirmação do Zelle é procurado nas receitas e nas despesas antes de lançar.',
        onde: 'zelleWatch' },
      { id: 'A.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Quem: o nome de quem mandou casa com o cadastro de clientes. Onde: a invoice que ESPERA aquele valor em aberto — não a mais recente.',
        fala: 'Recebeu um Zelle do Jesse McGee, a primeira coisa que o robô tem que fazer é ver se temos um cliente com este nome, se tiver, ele tem que ver se há alguma invoice dele com um valor próximo, tendo, é isso, ele deve cadastrar o income e apagar a linha anterior de income não paga, se houver, anexando o comprovante.',
        onde: 'zelleWatch' },
      { id: 'A.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Igual ao centavo e única: lança e APAGA a pendente que quitou. Perto, mas não igual: lança e a pendente FICA, com a diferença no aviso. Empate entre duas: palpite, dito como palpite.',
        onde: 'zelleWatch' },
      { id: 'A.5', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A receita nasce com a BAIXA (paid_at, meio-dia de Orlando). payment_date é só a data prevista, e só a baixa vira caixa.',
        onde: 'zelleWatch · lib/financials.ts' },
      { id: 'A.6', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O comprovante é o próprio aviso do Regions, guardado na linha que recebeu. Falhar em guardar o papel nunca desfaz o lançamento.',
        onde: 'zelleWatch' },
      { id: 'A.7', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Zelle ENVIADO nunca lança sozinho — falta o carro e a invoice: vira aviso com o memo do Zelle.',
        onde: 'zelleWatch' },
      { id: 'A.8', estado: 'EM CONSTRUÇÃO', desde: '08/09/2026',
        texto: 'Receita por wire, PIX ou cartão é caçada do mesmo jeito.',
        fala: 'O AutoBook, depois de pronto, tem que ser capaz de alocar no app qualquer gasto ou receita detectada!',
        nota: 'Hoje só o Zelle tem caçador. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: 'B',
    titulo: 'PAPEL SEM E-MAIL',
    resumo: 'Loja que não manda e-mail nunca acorda o robô. O sinal que sobra é o papel na pasta.',
    regras: [
      { id: 'B.1', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'Loja que não manda e-mail — AutoZone, balcão, loja física, serviço por telefone — nunca dispara o robô: a compra é lançada à mão, a partir do papel salvo na pasta.',
        fala: 'AutoZone não manda email, logo, não há este trigger pras compras dele, faça manualmente agora.' },
      { id: 'B.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Arquivo fora do padrão de nome dentro da pasta de uma invoice é suspeita de compra não lançada: o app só renomeia o que tem linha no banco.',
        onde: 'lib/papelOrfao.server.ts · papeisOrfaos' },
      { id: 'B.3', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A varredura conta, por invoice, os papéis na pasta contra os comprovantes no banco e dá o veredito: RECIBO A COLAR (a despesa existe sem comprovante), SUSPEITA DE COMPRA NÃO LANÇADA ou INVOICE FORA DESTE BANCO — sempre dizendo em qual banco perguntou. Só lê: não lança, não apaga, não renomeia.',
        onde: 'GET /api/auto-book?orfaos=1 · papeisOrfaos' },
      { id: 'B.4', estado: 'EM CONSTRUÇÃO',
        texto: 'A varredura roda sozinha, e o que ela acha vira pergunta na fila.',
        nota: 'Hoje só roda quando alguém chama a rota. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: 'C',
    titulo: 'GRUPOS DO WHATSAPP → APP DO BR',
    resumo: 'No BR a compra acontece no grupo: o pedido, o Pix e o comprovante em foto.',
    regras: [
      { id: 'C.1', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Tudo que é comprado E PAGO reportado nos grupos COMPRAS e FINANCEIRO vira linha no app do BR. Pedido não é pagamento: «preciso dessa peça» não lança; «pix para …» e comprovante lançam.',
        fala: 'ensine o robô a registrar tudo que é comprado e pago reportado no grupo compras e financeiro, pro app do BR.',
        nota: 'Especificação entregue ao App development em 09/09.' },
      { id: 'C.2', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O *asterisco* é o carro. Casa pelo conjunto de palavras do nome do carro, nunca por pedaço — «FireHawk» não é o «Hawk».',
        nota: '72 dos 94 rótulos usados desde 01/07 não casam exato com o nome do carro no app: falta um cadastro de apelidos por carro.' },
      { id: 'C.3', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Antes de tudo, descarta as mensagens do próprio número e os reports que o app manda no grupo — senão o robô lê o próprio relatório e lança de novo.' },
      { id: 'C.4', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Mensagem repetida é dado: a mesma mensagem vista pelos dois números nasce marcada como repetida, e quem lê pergunta a um campo só.',
        fala: 'o app tem que identificar se é repetido',
        onde: 'whatsapp_messages.duplicate_of',
        nota: 'Medido em 10/09: 2.619 mensagens marcadas.' },
      { id: 'C.5', estado: 'NO AR', desde: '27/07/2026',
        texto: 'FINANCEIRO é foto de comprovante: o valor sai da imagem, lido pelo mesmo leitor do botão SCAN; a legenda diz para que foi.',
        fala: 'i want this feature to be done by the app, not by you here, automatically, with the PC closed',
        onde: 'financeiro_inbox (banco US) · app BR /api/cron/financeiro' },
      { id: 'C.6', estado: 'NO AR', desde: '27/07/2026',
        texto: 'Só lança sozinho com o CARRO identificado e o VALOR lido; sem os dois, a mensagem espera gente.',
        onde: 'app BR /api/cron/financeiro',
        nota: 'Medido em 10/09, últimos 14 dias: 128 posts — 1 lançado (29/08), 65 esperando gente, 62 descartados.' },
    ],
  },
]
