// FIN SYNC ▸ AUTOBOOK — O LIVRO DO ROBÔ (Márcio, 10/set/2026).
//
//   "Quero que ali estejam listadas na sequencia, todas as regras que o robô usa
//    desde a detectção do income ou expense via email até estar registrado no app,
//    todos os passo do PROCESSAMENTO."
//   "Quero tudo do nosso AutoBook lá, tem que viver lá, se vive em outro lugar,
//    mova pra lá."
//   13/set/2026 — o fim do caminho mudou: "o AutoBook PROCESSING só está concluído
//    quando a movimentação financeira no banco está casada com app". O livro vai
//    agora do e-mail até a linha do extrato casada (etapa 14).
//
// ── POR QUE ESTE ARQUIVO EXISTE ────────────────────────────────────────────
// Até aqui as regras do AutoBook moravam em três lugares que ninguém lia junto:
//   • comentários espalhados em uns doze arquivos de código — o robô executa,
//     ninguém vê;
//   • três tabelas (auto_book_mail, auto_book_mail_rules, auto_book_mail_runs),
//     que guardam a fila, a regra aprendida e o pulso, não o porquê;
//   • as notas da Claudinha, FORA do app — onde o robô não alcança, e onde várias
//     regras moravam sozinhas (estorno como linha negativa, placeholder exportado,
//     destino pelo endereço de entrega, a pesca na conta da loja).
//
// Este arquivo é a fonte única do livro; a página /fin-sync/autobook só desenha o
// que está aqui. O código que executa cada regra continua onde está — mudar
// arquivo de lugar não ensina nada ao robô e quebra quem o importa. O que muda é
// que cada regra passa a ter UM texto, UM estado e o endereço de quem a executa.
//
// ── A DISCIPLINA ───────────────────────────────────────────────────────────
//   • Regra nova de AutoBook entra AQUI no dia em que é ditada: EM CONSTRUÇÃO se
//     o robô ainda não faz, À MÃO se quem faz é gente.
//   • O commit que põe a regra em código muda o estado dela para NO AR no MESMO
//     commit, com `onde` apontando a função que executa.
//   • Defeito conhecido em algo que está no ar é FURO, e o texto da regra diz o
//     comportamento CERTO; a nota diz o que acontece hoje.
//   • O `id` não muda ("5.2"): é por ele que conversa, recado e comentário de
//     código citam a regra. Regra nova entra no FIM da etapa.
//   • `fala` são as palavras DELE, literais. Sem fala conferida, fica sem fala.

export type Estado = 'NO AR' | 'À MÃO' | 'EM CONSTRUÇÃO' | 'FURO'

export const ESTADOS: { estado: Estado; diz: string }[] = [
  { estado: 'NO AR', diz: 'o robô faz sozinho, em produção' },
  { estado: 'À MÃO', diz: 'a regra vale, mas quem executa é gente: o Márcio ou a Claudinha' },
  { estado: 'EM CONSTRUÇÃO', diz: 'o robô ainda não faz; a nota diz se já foi pedido ao App development' },
  { estado: 'FURO', diz: 'o robô faz, com defeito conhecido; a nota diz o que acontece hoje' },
]

export type Regra = {
  id: string
  texto: string
  estado: Estado
  desde?: string   // quando a regra nasceu (dd/mm/aaaa)
  fala?: string    // as palavras do Márcio, literais
  onde?: string    // quem executa: arquivo · função · tabela
  nota?: string    // o caso, a medida, o que falta
}

export type Etapa = { id: string; titulo: string; resumo: string; regras: Regra[] }

export const LIVRO_ATUALIZADO = '2026-09-16'

// ═══ A SEQUÊNCIA — O CAMINHO DO E-MAIL DE COMPRA ATÉ A LINHA NO APP ═══════════
export const SEQUENCIA: Etapa[] = [
  {
    id: '0',
    titulo: 'ANTES DO E-MAIL',
    resumo: 'A parte da casa. É ela que deixa o robô saber de qual carro é a compra.',
    regras: [
      { id: '0.1', estado: 'À MÃO', desde: '27/07/2026',
        texto: 'Compra sempre logada na conta própria da loja, nunca como convidado. Criar conta, digitar senha e pagar é do Márcio.' },
      { id: '0.2', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'O documento da compra é salvo na pasta da invoice certa do carro certo: Rides/<carro>/Invoices/<código> - <nome>/. É esse arquivo que responde ao robô de qual carro e de qual invoice é a compra.',
        fala: 'eu salvo o invoice da compra na pasta da invoice certa do carro certo' },
      { id: '0.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Toda invoice de carro nasce com a sua pasta dentro de Invoices/, com o código e o nome dela. Quote não ganha pasta. Renomear a invoice ou renumerar o carro renomeia a pasta.',
        onde: 'app/api/ride-folder · invoice-folder' },
    ],
  },
  {
    id: '1',
    titulo: 'O ROBÔ ACORDA',
    resumo: 'Relógio próprio, janela com sobra e prova de que rodou.',
    regras: [
      { id: '1.1', estado: 'NO AR', desde: '06/09/2026',
        texto: 'O robô roda de hora em hora, com relógio próprio — fora do mail-poll de 5 minutos, que carrega 15 trabalhos em série e já deixou quem estava no fim da fila sem rodar.',
        fala: 'Precisamos automatizar ao máximo o AutoBook.',
        onde: 'vercel.json (0 * * * *) · app/api/cron/auto-book' },
      { id: '1.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Cada rodada lê as últimas 3 horas: as 2 horas de sobra cobrem a rodada que falhou e o e-mail que chega na virada, e repetir não duplica nada. Para recuperar uma rodada perdida, ?horas=N vai até 168 e a rodada fica marcada como humana.',
        onde: 'app/api/cron/auto-book' },
      { id: '1.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Prova de vida: a rodada abre uma linha RUNNING antes de trabalhar e fecha DONE ou ERROR com os contadores. Sem essa linha, fila vazia não diz se o robô rodou; RUNNING velho é rodada que morreu no meio.',
        onde: 'auto_book_mail_runs · abreRodada / fechaRodada',
        nota: 'Medido em 10/09/2026: 90 rodadas registradas; nos últimos 7 dias, 89 DONE e 1 ERROR.' },
      { id: '1.4', estado: 'NO AR', desde: '10/09/2026',
        texto: 'A rota do relógio só roda para o cron da Vercel (CRON_SECRET) ou para quem tem a chave de leitura — é essa chave que mantém possível a rodada humana de ?horas=N. Sem nenhuma das duas, 401.',
        onde: 'app/api/cron/auto-book',
        nota: 'Até 10/09 não conferia: qualquer um com a URL disparava uma varredura de até 168 horas, que lê as caixas e arquiva e-mails (achado da sessão do João). Fechada no mesmo dia, com o aval do Márcio, junto com a rota do marketing kill.' },
      { id: '1.5', estado: 'FURO', desde: '10/09/2026',
        texto: 'Caixa sem token ou com erro de API é erro da rodada, nunca caixa vazia.',
        onde: 'lib/autoBookMail.server.ts · lerCaixa · lib/streamMail.server.ts · fetchRecentMessages',
        nota: 'Hoje a caixa morta volta com zero mensagens e a rodada fecha DONE: as caixas podem morrer uma a uma sem aviso (achados 1 e 2 do João).' },
    ],
  },
  {
    id: '2',
    titulo: 'RECEBE O E-MAIL',
    resumo: 'As caixas conectadas, com o corte do BR e a proteção do arquivo de compras.',
    regras: [
      { id: '2.1', estado: 'NO AR',
        texto: 'Lê todas as caixas conectadas ao app — hoje são 6. Se a caixa é Outlook ou Gmail sai do cadastro dela, nunca do número do slot.',
        onde: 'stream_mail_auth · listMailAuths / mailProvider' },
      { id: '2.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'No Gmail a busca é pela COMPRA, não só pelo despacho: era lá que moravam os recibos da Amazon e da Home Depot, e a busca antiga só pedia e-mail de envio.',
        onde: 'lib/streamMail.server.ts · GMAIL_Q_COMPRA' },
      { id: '2.3', estado: 'NO AR', desde: '06/09/2026',
        texto: 'BR sem retroativo: e-mail das caixas do BR anterior a 06/09/2026 00:00 de Brasília não é processado nem vira pergunta. A trava mora no robô, não na janela — varredura larga não ressuscita o passado.',
        fala: 'pode processar as coisas do BR, mas sem retroativo, só daqui pra frente.',
        onde: 'lib/autoBookMail.server.ts · BR_FLOOR' },
      { id: '2.4', estado: 'NO AR', desde: '04/09/2026',
        texto: 'Caixa marcada para não ser varrida — a 6, gz28shopping, arquivo de compras do BR — é lida, mas nenhum robô move nem apaga nada nela.',
        onde: 'stream_mail_auth.auto_sweep · maySweep' },
      { id: '2.5', estado: 'FURO', desde: '10/09/2026',
        texto: 'Nenhum recibo fica fora da leitura por excesso de e-mail na janela.',
        onde: 'lib/streamMail.server.ts · fetchRecentMessages / fetchRecentGmail',
        nota: 'Hoje o teto é 50 mensagens por caixa no Outlook e 60 no Gmail, sem paginação: uma onda de marketing empurra recibo real para fora, calado (achado 3 do João).' },
    ],
  },
  {
    id: '3',
    titulo: 'PENEIRA: SÓ PASSA DINHEIRO',
    resumo: 'Uma pergunta só: isso vira ou muda uma linha de dinheiro no app?',
    regras: [
      { id: '3.1', estado: 'NO AR', desde: '05/09/2026',
        texto: 'Passa compra, estorno e cobrança. Marketing, conversa e aviso sem compra morrem aqui, calados.',
        onde: 'lib/autoBookMail.server.ts · classify' },
      { id: '3.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Compra se reconhece pelo CONTEÚDO — um total de rótulo forte e um número de pedido —, nunca pelo formato do assunto. O assunto só reforça quando o valor não deu para ler.',
        onde: 'classify · COMPRA_ASSUNTO',
        nota: 'A primeira rodada leu 173 e-mails e achou zero com dinheiro, porque julgava a compra pelo assunto.' },
      { id: '3.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Recibo do PayPal: o valor está no ASSUNTO («HP Tuners LLC: $499.99 USD») e o fornecedor é o COMERCIANTE, sem LLC ou INC — nunca «paypal.com».',
        onde: 'paypalReceipt' },
      { id: '3.4', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Estorno só conta quando o vendedor afirma que devolveu («has been refunded»). «Refund policy» e «request a refund» são conversa.',
        onde: 'lib/mailToItem.server.ts · ESTORNOU' },
      { id: '3.5', estado: 'À MÃO', desde: '05/09/2026',
        texto: 'Não é gasto até pagar: orçamento, cotação, link de pagamento em aberto, backorder, contrato e e-sign não entram.',
        nota: 'O robô não separa cotação de compra quando as duas trazem total e número; quem responde a dúvida aplica a regra e ignora.' },
      { id: '3.6', estado: 'NO AR', desde: '11/09/2026',
        texto: 'Aviso de ENVIO do PayPal («order is on its way») não é cobrança: morre na peneira, calado, e o e-mail do PayPal sem pedido cujo comerciante já tem linha por perto é arquivado como pagamento de compra já lançada — MENOS estorno, que sempre pergunta. Em e-mail do PayPal o fornecedor é o comerciante do corpo (linha «Merchant»); quando o corpo não traz essa linha, vale o comerciante do assunto estruturado, e só sem os dois fica «PayPal».',
        onde: 'lib/autoBookMail.server.ts · classify (ENVIO_ASSUNTO) · comercianteDoPayPal · vendorOf · paypalReceipt · temLinhaPorPerto',
        nota: 'Caso de 10/09 14:23: o aviso de envio da compra HHP 384734, lançada em 09/09, abriu a dúvida 6bab19c6 como cobrança nova de US$ 1.290,93 do fornecedor «PayPal». Fechada à mão como IGNORED. Consertado em 11/09: assunto de embarque do PayPal morre na peneira (só do PayPal — na loja, embarque no corpo é compra de verdade), o fornecedor sai da linha «Merchant» do corpo e o teste de «já tem linha por perto» roda com a grafia crua e com a curada do cadastro (High Horse Performance = HHP). O TAMANHO EXATO DA REGRA, medido em 11/09 nas 8 cartas do PayPal que a fila guarda: o corpo entrega o comerciante em 4 e devolve nulo em 4 (eBay Commerce, eBay Commerce Canada, Apple Services) — nessas o nome vem do assunto. E o rastreio dentro do aviso só vira fato de uma linha quando o NÚMERO DO PEDIDO aparece no texto: na carta do caso ele não aparece (só «UPS 1Z1777V54254429692»), então ali o rastreio se perde mesmo — o que esta regra garante é que ele não vira dúvida falsa.' },
      { id: '3.7', estado: 'NO AR', desde: '11/09/2026',
        texto: 'Recibo de loja Shopify («Receipt for order #13150») chega à fila mesmo com pedido de 5 dígitos: o remetente @t.shopifyemail.com COM o número do pedido no assunto é recibo de loja. Só o remetente não basta — a campanha de marketing sai do mesmo domínio.',
        onde: 'lib/mailToItem.server.ts · PEDIDO_NOVO · lib/autoBookMail.server.ts · COMPRA_ASSUNTO · classify · vendorOf',
        nota: 'Caso Detail Ground 13150 (10/09 13:39, US$ 77,67): nenhuma linha em auto_book_mail. O e-mail morreu calado e a compra só foi achada pela foto no grupo do time. Consertado em 11/09: «order #NNNNN» de 5 a 8 dígitos com a cerquilha colada vira pedido, «receipt for order» entra na peneira de assunto, o remetente da plataforma com o pedido NO ASSUNTO é compra, e o fornecedor é o NOME da loja no remetente, não «Shopifyemail». O pedido tem de estar no assunto porque o rodapé de promoção («check your order status») também carrega número de pedido no corpo.' },
      { id: '3.8', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Hapvida / NotreDame Intermédica é CONTA REAL: o plano de saúde PJ da Galpão Z28 (contrato 1T9UC.000000), processado no app como qualquer conta. Todo mês chegam dois boletos, com vencimento no dia 23 — mensalidade e coparticipação. O PDF vem com senha (os 4 primeiros dígitos do CNPJ). O e-mail automático — boleto, aviso de fatura pendente ou de pagamento não identificado — entra no processamento, nunca vai para Itens Excluídos.',
        fala: 'este e HPVida tem que ser processados no app à partir de agora também, são contas reais',
        onde: 'marketing_senders (os 4 remetentes com active = false, sem a exceção das travas) · lançamento no app BR ainda sem robô',
        nota: 'Substitui a regra de 12/09 («apague sempre»), que caiu em 13/09 por ordem do Márcio. A App development tirou do apagar sempre boleto.notredamesp@hapvida.com.br, comunicacao@contato.hapvidandi.com.br, ccg@contato.comunicacaoccg.com.br e contato@pagoufacil.com.br (trilha em data_fixes, check_key hapvida-conta-real); a trava de palavra e a de anexo voltam a proteger o boleto. Entre 10 e 13/09 o robô mandou 6 avisos do pagoufacil para Itens Excluídos da galpaoz28, nenhum deles boleto. comunicado.importante@intermedica.com.br nunca esteve na lista (10 e-mails de 2023–2024 numa pasta). Referência 09/2026: mensalidade R$ 4.600,85 + coparticipação R$ 208,62. Como lançar (app BR, folha da Galpão — ver marli-health-plan-payroll) é decisão a fechar com o Márcio.' },
      { id: '3.9', estado: 'NO AR', desde: '16/09/2026',
        texto: 'Loja online de concessionária (plataforma RevolutionParts, remetente @emails.revolutionparts.com): o fornecedor é a LOJA — o nome antes dos dois pontos no assunto («Mopar.com National eStore: Order #…»), ou o nome do remetente. Sem nenhum dos dois, fica «RevolutionParts», nunca o pedaço do domínio. E em qualquer domínio, «emails.» é prefixo de envio, não nome de fornecedor.',
        onde: 'lib/autoBookMail.server.ts · vendorOf · lojaRevolution',
        nota: 'Caso Mopar.com National eStore, pedido 1055505 (14/09 23:28 Orlando, US$ 801,43, um ECM 68434939AC): a dúvida d37b4b91 nasceu com o fornecedor «Emails». Achado pela Staff Cronogram e consertado pela App development em 16/09. Medido nas 34 linhas da fila: só essa muda.' },
    ],
  },
  {
    id: '4',
    titulo: 'VALIDA AS INFORMAÇÕES',
    resumo: 'Pedido, valor, moeda e data — o que o e-mail precisa trazer para virar linha.',
    regras: [
      { id: '4.1', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Número do pedido só vale colado à palavra do pedido («order», «order ID», «pedido»), nos formatos reais da casa — eBay 12-12345-12345, Amazon 123-1234567-1234567, Temu PO-…, 6 a 7 dígitos (HHP, HP Tuners, PayPal), «#13150» de 5 a 8 dígitos com a cerquilha colada NO NÚMERO, sem espaço (loja Shopify), e código com letra: 2 a 3 letras + 6 a 12 dígitos (Home Depot WH43863914, inclusive com sufixo de remessa «-1») ou 1 a 3 letras + 4 a 12 dígitos (Aeromotive A13706).',
        onde: 'lib/mailToItem.server.ts · PEDIDO_NOVO',
        nota: 'Formato largo pega telefone, CEP e pedaço de valor; por isso a lista é fechada. Os dois formatos de 11/09 entraram com trava: a cerquilha colada no de 5 dígitos («order # 12345», com espaço, NÃO entra) e o código em MAIÚSCULAS no de letra (ver 3.7 e 5.9). A trava anti-recorte — que impede «T2024-001» virar «T2024» — mora SÓ na forma de 1 letra: colada também na forma antiga, ela matava «Order #WH43863914-1», que o robô lia inteiro desde 07/09 (medido em 11/09).' },
      { id: '4.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Valor que autoriza lançamento só de rótulo FORTE: Order total, Grand total, Total paid, Valor pago. «Total» dentro de «Order Summary» vale como forte. Subtotal é o mais fraco de todos — com desconto, fica acima do que foi pago.',
        onde: 'parseMoney',
        nota: 'Caso HHP 384734: o robô leu o subtotal 1.444,75 no lugar dos 1.290,93 pagos.' },
      { id: '4.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Um e-mail, vários pedidos (Temu, «divided into N orders»): cada pedido fica com o SEU total, lido logo depois do número. Sem total colado ao número, o valor não é atribuído.',
        onde: 'totaisPorPedido' },
      { id: '4.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Número nos dois formatos: em «1,234.56» e «1.234,56» o último separador manda; três casas depois dele é milhar.',
        onde: 'parseNumber' },
      { id: '4.5', estado: 'NO AR', desde: '07/09/2026',
        texto: 'R$ ou BRL é real; o resto é dólar.',
        onde: 'parseMoney' },
      { id: '4.6', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Total 0,00 de rótulo forte — brinde, pedido pago com crédito da loja — não gera linha. O e-mail é arquivado.',
        onde: 'runAutoBookMail' },
      { id: '4.7', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O total do e-mail nunca vira preço de peça: lançar o total como preço único quebra preço × quantidade + imposto + frete e contamina o custo no Parts DB. A linha detalhada vem do documento (etapa 7).',
        nota: 'É por isso que a caça na pasta aponta a invoice, mas não lança sozinha.' },
      { id: '4.8', estado: 'À MÃO', desde: '08/09/2026',
        texto: 'A data do pagamento é o dia em que pagamos, e vem do recibo ou do e-mail do vendedor. A data do extrato é a do processamento; a data de um pedido ainda não pago não é pagamento.',
        fala: 'a data do pagamento é o dia que pagamos, o dia que aparece no banco deve ser a data de processamento, são 2 datas diferentes. Nunca o dia do pagamento é o mesmo do processamento.',
        nota: 'O robô ainda não grava a data do pagamento na linha que lança — ver 8.7.' },
      { id: '4.9', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Antes de cadastrar custo fixo a partir de um e-mail, abre o anexo: cobrança única — multa rescisória, taxa, acordo — não é mensalidade. Mensalidade só nasce com dois sinais de recorrência (contrato, duas faturas seguidas, a palavra «mensalidade»).',
        nota: 'Caso Emive (BR, 28/07): o boleto «RECEITA MULTA RESCISORIA ALARME» de R$ 1.311,88 virou fixo MENSAL sem ninguém abrir o PDF, com 8 parcelas fantasma (R$ 10,5 mil no Future Flow). Corrigido em 13/09: paga uma vez, em 11/08, R$ 1.446,59 com juros.' },
      { id: '4.10', estado: 'NO AR', desde: '16/09/2026',
        texto: 'Valor tem de ser dinheiro: o número termina em dígito e não vem colado em letra — «68434939AC» é part number, e o ponto final da frase não entra no número. Depois de rótulo fraco («Total» solto), número sem moeda e sem centavos também não é valor (cabeçalho de tabela, quantidade). «Amount Charged/Authorized» é rótulo forte.',
        onde: 'lib/autoBookMail.server.ts · ROTULO · parseMoney',
        nota: 'Caso Mopar.com National eStore 1055505 (dúvida d37b4b91): o «Total» do cabeçalho «Part Number Part Name Price Quantity Total» leu o part number da 1ª linha e a pergunta saiu «USD 68434939»; o total de verdade, US$ 801,43, estava duas vezes no e-mail («Total: $801.43» e «Amount Charged/Authorized: $801.43»). Na bancada do conserto apareceu um furo pior e calado: «Order total: $150.00.», com o ponto final da frase, era lido 15.000 — com rótulo FORTE, o que autoriza lançamento. Os dois consertados em 16/09 (App development, relato da Staff Cronogram). Medido nas 34 linhas da fila: só a d37b4b91 muda.' },
    ],
  },
  {
    id: '5',
    titulo: 'JÁ EXISTE NO APP?',
    resumo: 'Antes de perguntar ou lançar, provar que não é duplicado.',
    regras: [
      { id: '5.1', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Pedido que já existe em qualquer tabela de item ou de custo fixo não é compra nova: o e-mail vira FATO daquela linha (rastreio, entrega, estorno) e é arquivado.',
        onde: 'pedidosConhecidos · lib/mailToItem.server.ts' },
      { id: '5.2', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O mesmo pedido escrito de dois jeitos é o mesmo pedido: só letras e números, e também a forma sem zeros à esquerda quando sobram 5 ou mais caracteres (0430475 = 430475).',
        onde: 'formasDoPedido' },
      { id: '5.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Assinatura é do SUBSCRIPTIONS: o remetente casa pelo DOMÍNIO cadastrado no prestador. Já lançada em até 6 dias, arquiva; não lançada, vira aviso. Nunca pelo nome no texto — o app escreve «Claude», não «Anthropic».',
        onde: 'appsPorDominio / assinaturaLancada',
        nota: 'Na primeira rodada boa, 10 das 11 perguntas eram recargas já lançadas.' },
      { id: '5.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Recibo do PayPal sem pedido, com linha do mesmo comerciante em até 6 dias, é o pagamento de uma compra já lançada: arquiva. Recibo nunca se confere por valor exato — o app parte a compra em preço + imposto + frete e rateia entre carros.',
        onde: 'temLinhaPorPerto',
        nota: 'Conferir por valor exato deu 4 alarmes falsos em 04/09.' },
      { id: '5.5', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Antes de perguntar, procura por VALOR + fornecedor, 15 dias para cada lado, nas 7 tabelas de gasto — a maioria das linhas nasce sem número de pedido. Achou, arquiva.',
        fala: 'ponha o robô pra vasculhar o app pra esta nova despesa; se não encontrar, verificar as pastas PURCHASES dos carros; só se não encontrar nestes 2 lugares, isto fica em dúvida.',
        onde: 'achaNoApp' },
      { id: '5.6', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Nunca pergunta duas vezes: cada e-mail, e cada pedido dentro dele, tem chave única.',
        onde: 'auto_book_mail.message_key' },
      { id: '5.7', estado: 'NO AR', desde: '07/09/2026',
        texto: '«Não achei» diz ONDE procurou: a pergunta lista as tabelas, os bancos e as pastas consultados.',
        onde: 'runAutoBookMail' },
      { id: '5.8', estado: 'FURO', desde: '07/09/2026',
        texto: 'Compra já lançada no app do BR não vira pergunta.',
        onde: 'pedidosConhecidos',
        nota: 'Hoje o robô só consulta o banco do US, e a pergunta sai com o aviso «CONFERIR NO APP DO BR». Falta a chave de serviço do BR no Vercel do US (SUPABASE_BR_SERVICE_ROLE_KEY).' },
      { id: '5.9', estado: 'NO AR', desde: '11/09/2026',
        texto: 'Pedido com letra («Order A13706») é pedido. Dois e-mails da mesma compra — mesmo fornecedor, mesmo valor ao centavo, dúvida aberta nas últimas 24 horas — viram UMA pergunta só: a 2ª carta não abre dúvida nova, mas deixa a linha dela na fila como DUPLICATE, sai da caixa, e o número de pedido que ela trouxer é enxertado na dúvida que ficou.',
        onde: 'lib/mailToItem.server.ts · PEDIDO_NOVO · lib/autoBookMail.server.ts · chaveDuvida · lerCaixa (ordem do relógio) · runAutoBookMail',
        nota: 'Caso Aeromotive A13706 (10/09 22:37 e 22:38): a confirmação e o e-mail de boas-vindas abriram as dúvidas 07142a50 e 3ccf912c, as duas «sem número de pedido». Lançado à mão na US.019.3. Consertado em 11/09: 1 a 3 letras coladas a 4 a 12 dígitos depois de «Order» viram pedido (piso de 5 caracteres, o mesmo do dicionário), e a segunda carta da mesma compra não abre dúvida nova. Sem valor legível não deduplica, e estorno nunca é engolido por compra — silêncio é o único erro que esta fila não pode cometer. A RODADA LÊ NA ORDEM DO RELÓGIO: o Graph devolve da carta mais nova para a mais velha, e sem inverter isso quem sobrevivia era a de 22:38 («Thanks for your order!», sem pedido) e quem sumia era a de 22:37, a única que carrega o A13706.' },
    ],
  },
  {
    id: '6',
    titulo: 'VAI NAS PASTAS',
    resumo: 'Papel salvo por gente é resposta dada. A pasta vem antes da estatística.',
    regras: [
      { id: '6.1', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A pasta da invoice é o PRIMEIRO lugar de caça. O arquivo salvo ali responde de qual carro e de qual invoice é a compra — e vale mais que o histórico do fornecedor.',
        fala: 'o primeiro lugar que o robô tem que caçar é nas pastas das invoices',
        onde: 'lib/dropboxHunt.server.ts · cacaNaPasta',
        nota: 'Caso Summit, 08/09: o histórico apontava três carros, todos errados; a pasta apontou o SublimeHell.' },
      { id: '6.2', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Procura pelo NOME do arquivo nas duas raízes: /001 - GZ28US/GZ28US Rides e /000 - GZ28BR/GZ28BR Rides.',
        onde: 'cacaNaPasta' },
      { id: '6.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Três forças de evidência: ORDEM (o número do pedido está no nome — decide), RECENTE (nome do fornecedor e arquivo salvo até 12 horas do e-mail — decide se for a única) e FORNECEDOR (outra época — só ordena as sugestões). A força mais alta presente decide sozinha.',
        onde: 'respostaUnica' },
      { id: '6.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A hora do arquivo é a da mão de quem salvou (client_modified), nunca a do servidor do Dropbox, que muda a cada ressincronização.',
        onde: 'cacaNaPasta' },
      { id: '6.5', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Procura com o nome que veio no e-mail E com o nome do cadastro e seus apelidos, porque a pasta é nomeada com o nome curado. Apelido vai inteiro; no máximo 4 termos.',
        onde: 'termosDeBusca',
        nota: 'Caso HHP 384734: o robô procurou «Highhorseperformance» e o arquivo estava salvo como «HHP».' },
      { id: '6.6', estado: 'NO AR', desde: '09/09/2026',
        texto: 'O nome que voltou tem de conter todas as palavras do termo procurado — o Dropbox afrouxa a busca e devolve arquivo de outra loja.',
        onde: 'nomeConfirma' },
      { id: '6.7', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Carro e invoice saem do CAMINHO do arquivo. Purchases/ guarda o papel do carro que ainda não tem invoice definida.',
        onde: 'leCaminho' },
      { id: '6.8', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Procura também nos recibos já guardados no app, pelo pedido ou pelo fornecedor no nome. Achou: «o papel está guardado, falta a linha».',
        onde: 'achaPapel' },
      { id: '6.9', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O histórico do fornecedor — onde foram parar as compras anteriores, com a contagem real — só entra depois da pasta, como sugestão.',
        onde: 'candidatosPara' },
      { id: '6.10', estado: 'FURO', desde: '10/09/2026',
        texto: 'Falha do Dropbox é erro da caça, não da rodada.',
        onde: 'runAutoBookMail',
        nota: 'Hoje uma falha de autenticação do Dropbox fecha a rodada como ERROR mesmo com a pergunta registrada certa (achado 5 do João; foi o único ERROR da semana).' },
      { id: '6.11', estado: 'À MÃO', desde: '10/09/2026',
        texto: 'Toda caça a um gasto COMEÇA pelos dois grupos do time nos EUA — «GZ28US Time» e «GZ28US - STAFF». É lá que a foto do recibo aparece, no mesmo dia da compra, com o carro na legenda.',
        fala: 'sempre que quiser pesquisar sobre um gasto, inicie buscando neste 2 grupos',
        onde: 'espelho whatsapp_messages (banco US), só a linha canônica (duplicate_of nulo)',
        nota: 'Foi assim que as 4 compras de 10/09 do WorkTruck apareceram: quatro fotos às 15h26, com Discount Tire, AutoZone, Harbor Freight e Detail Ground. E foi assim que se provou que a AutoZone de US$ 201,44 do mesmo dia NÃO tem recibo postado. Para o robô, ler grupo ainda só existe no BR (boca C).' },
    ],
  },
  {
    id: '7',
    titulo: 'LÊ O DOCUMENTO E PESCA O QUE FALTA',
    resumo: 'A pasta diz QUAL invoice; o documento diz O QUE lançar.',
    regras: [
      { id: '7.1', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O robô baixa o documento que achou na pasta e lê com o mesmo leitor do botão SCAN: item, quantidade, desconto, imposto e frete, linha a linha.',
        onde: 'app/api/auto-book/ler-pasta · app/api/scan-receipt',
        nota: 'A leitura existe desde 09/09; o robô de hora em hora ainda não a chama. Especificação dos 10 passos entregue ao App development em 09/09.' },
      { id: '7.2', estado: 'NO AR',
        texto: 'Rateio do documento: imposto e frete divididos na proporção do valor de cada linha; o centavo que sobra fica na última; a soma das linhas fecha o total pago ao centavo.',
        onde: 'app/api/scan-receipt' },
      { id: '7.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Desconto de linha é PERCENTUAL: arredonda((1 − pago ÷ lista) × 1000) ÷ 10. O preço da linha é o custo já pago.',
        onde: 'app/api/scan-receipt',
        nota: 'Três telas subtraíam o percentual como se fosse dinheiro; corrigido em 07/09.' },
      { id: '7.4', estado: 'À MÃO', desde: '19/08/2026',
        texto: 'Sem documento na pasta e com e-mail cego, pesca-se na conta da loja: Temu pelo detalhe do pedido; Amazon pelo apelido do endereço de entrega; eBay pelo detalhe do pedido em order.ebay.com.',
        nota: 'Feito pela Claudinha, no navegador logado.' },
      { id: '7.5', estado: 'À MÃO',
        texto: 'Ele loga, a Claudinha opera: senha, CPF, cadastro e captcha só o Márcio digita.' },
      { id: '7.6', estado: 'À MÃO', desde: '31/08/2026',
        texto: 'No site o valor é o total do pedido: o «saved $X» da Temu não é valor, e pedidos em sequência do mesmo vendedor no eBay são UM pedido — somar os números triplica.' },
      { id: '7.7', estado: 'NO AR', desde: '10/09/2026',
        texto: 'Desconto dado no TOTAL da nota entra RATEADO no preço de cada linha; o percentual fica só em item_discount, que existe para reconstruir o MAP. Preço de lista na linha, com o desconto só no campo, infla o custo do carro.',
        onde: 'app/api/scan-receipt (itemScale · cost_derived) · lib/financials.ts · expLine',
        nota: 'Caso O&J Woo199927 (US.022.2, compra de 04/09): as duas linhas entraram com preço de lista e o custo ficou US$ 17,16 acima do que saiu do cartão — e a cobrança do banco ficou sem casar por isso. Corrigido em 10/09 pela sessão App development, com trilha em data_fixes. Das outras 116 linhas com desconto do banco do US, nenhuma estava bruta.' },
    ],
  },
  {
    id: '8',
    titulo: 'REGISTRA NO LUGAR CERTO',
    resumo: 'Na invoice certa, na tabela certa, com os campos certos — e sem deixar nada duplicado.',
    regras: [
      { id: '8.1', estado: 'NO AR', desde: '10/08/2026',
        texto: 'Tudo gira em torno de invoice: a primeira pergunta de todo lançamento é «qual invoice?». Na dúvida de onde lançar, pergunta.',
        onde: 'a pergunta da etapa 12' },
      { id: '8.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Lança sozinho SÓ com as três juntas: regra escrita por gente, valor de rótulo forte e número do pedido. Nunca escolhe carro por conta própria.',
        onde: 'lancar · auto_book_mail_rules',
        nota: 'Medido em 10/09: nenhuma regra aprendida ainda — todo lançamento até hoje veio de resposta humana.' },
      { id: '8.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Cada tabela com a sua coluna de valor: price na invoice, amount em staff_expenses, unit_price em supplies. Trocar grava zero.',
        onde: 'lancar' },
      { id: '8.4', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O fornecedor entra com o nome do CADASTRO; sem cadastro que case, entra o nome como veio — inventar é pior. A cura é só na escrita: a busca no banco usa o nome cru, que é o que está lá.',
        fala: 'normalize sempre os nomes dos fornecedores, ensine todos os robôs de escaneamento a fazer isso, assim os dados já entram certos',
        onde: 'lib/supplierMatch.ts · matchSupplier' },
      { id: '8.5', estado: 'NO AR', desde: '04/08/2026',
        texto: 'Número do pedido sempre, na coluna própria. Pedidos nunca se juntam: uma cobrança do PayPal com dois pedidos vira duas linhas.',
        fala: 'every single purchase/expense, not only inputs, every single expense should have the order number field',
        onde: 'lancar' },
      { id: '8.6', estado: 'NO AR', desde: '18/08/2026',
        texto: 'A despesa tem UMA data: a do pagamento.',
        onde: 'app/rides/[id]/invoices/edit/[invoiceId] (expense_date espelha payment_date)' },
      { id: '8.7', estado: 'FURO', desde: '10/09/2026',
        texto: 'A linha lançada pelo robô nasce com a data do pagamento e com quem pagou.',
        onde: 'lancar',
        nota: 'Hoje nasce sem payment_date e sem paid_from: até o banco casar, fica fora de «quem pagou» e do fluxo de caixa (achado 8 do João).' },
      { id: '8.8', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Compra real apaga o que ela substitui: as despesas NÃO PAGAS contidas nesta compra saem, e fica só o que não estava nela. Só com casamento forte (fornecedor + valor + quantidade); o resto vira pergunta.',
        fala: 'o AutoBook cuida pra nas expenses não haver nada duplicado, ou seja, ele apaga as expenses não pagas contidas nesta compra, deixa só o que não estava nesta compra.',
        nota: 'Lei desde 10/08; passo 9 da especificação entregue ao App development em 09/09. Hoje é feito à mão.' },
      { id: '8.9', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'Se a despesa não paga já foi levada para ITEMS, a compra real entra POR CIMA dela: apagar romperia o elo com o item, e uma reimportação duplicaria os ITEMS.',
        nota: 'Caso HHP 384734, GoldenEye.' },
      { id: '8.10', estado: 'À MÃO', desde: '04/09/2026',
        texto: 'Estorno é uma linha NEGATIVA espelhando a original — mesmo pedido, mesmo comprovante, mesma categoria —, com a data do e-mail do estorno. A linha original nunca é editada para baixo.' },
      { id: '8.11', estado: 'À MÃO', desde: '27/08/2026',
        texto: 'Pedido com itens de destinos diferentes vira linhas separadas, rateadas pelo preço de cada item.' },
      { id: '8.12', estado: 'À MÃO', desde: '25/08/2026',
        texto: 'O endereço de entrega decide o destino: 4000 Headwaters (Luma) é APARTMENT; 11320 Space Blvd 2A é o galpão; entrega na PowerTrade Miami é compra do GZ28BR; bicho no galpão é CATS.' },
      { id: '8.13', estado: 'À MÃO', desde: '28/07/2026',
        texto: 'Custo de carro tem UM dono: seguro e uso da ferramenta de trabalho são da oficina; compra, documentação e custos de carro de patrimônio ou de cliente vão na invoice do próprio carro. O dinheiro sai uma vez e é lançado uma vez.',
        fala: 'se tem seguro é porque tem título e está EM USO DA OFICINA' },
      { id: '8.14', estado: 'À MÃO', desde: '03/09/2026',
        texto: 'No app do BR o valor é em REAIS; o dólar vai em amount_usd, convertido pela taxa da invoice. Depois de pago, o valor congela.',
        fala: 'depois que está pago, tem que ficar o valor que foi pago no dia, não pode variar mais.' },
      { id: '8.15', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Merch da marca — camiseta, boné, moletom GZ28 — é MARKETING: brinde para evento, cliente e redes. Entra em custo com fornecedor de marketing, não em estoque de revenda nem em uniforme.',
        onde: 'fixed_cost_suppliers (cost_type MARKETING) · fixed_cost_expenses SINGLE',
        nota: 'TSS Printing, 13/09: lote de 100 camisetas (FJR082616, US$ 1.094,82) e pedido #1131 (US$ 380, 26/06).' },
      { id: '8.16', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Seguro viagem e passagem de gente do time são custo do GZ28US na season da pessoa: uma linha por pessoa, com voucher e nota fiscal, e a data do pagamento. Compra para duas pessoas divide ao meio.',
        onde: 'staff_expenses (origin GZ28US, season_id)',
        nota: 'Molde: seguro do Jeferson (pedido Promo 1186818). Aplicado em 13/09 ao pedido 1187616 (Guilherme US.003 + João Luca US.002).' },
    ],
  },
  {
    id: '9',
    titulo: 'PARTS DB',
    resumo: 'A peça comprada entra no banco de peças — e a última compra manda no custo.',
    regras: [
      { id: '9.1', estado: 'À MÃO', desde: '03/09/2026',
        texto: 'Toda peça comprada entra no Parts DB sem perguntar, com tudo: apelido, descrição, número da peça, MAP, custo, fornecedor, desconto, o menor frete, peso e o link do produto. Auditada três vezes antes de gravar: a soma bate com o total pago, um número de peça é uma linha só, nenhum campo vazio e MAP maior ou igual ao custo.',
        fala: 'sempre! pra entrar no parts db, tem que ser com tudo, tudo, auditado triplamente, e badgeado assim.' },
      { id: '9.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A compra real da mesma peça no mesmo fornecedor atualiza o custo mesmo com cadeado. O cadeado continua onde estava.',
        fala: 'sempre que uma compra real é feita, da mesma peça, no mesmo fornecedor, tem que atualizar o valor da peça no parts db, mesmo que bloqueada.',
        onde: 'lib/partsDb.ts · enrollOne' },
      { id: '9.3', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A ÚLTIMA compra manda, promoção incluída; na próxima, se o valor for outro, atualiza de novo. O banco guarda o que foi pago da última vez — não a média, nem o melhor preço.',
        fala: 'sempre a última compra atualiza o parts db, mesmo que seja promo, na próxima compra, se o valor for outro, atualiza de novo.',
        onde: 'lib/partsDb.ts · enrollOne' },
      { id: '9.4', estado: 'À MÃO', desde: '05/08/2026',
        texto: 'O frete da peça no Parts DB é o MENOR possível — nunca o expresso de uma compra com pressa.' },
      { id: '9.5', estado: 'NO AR', desde: '08/07/2026',
        texto: 'O MAP que vale é o preço de lista impresso na nota real; ele revalida o MAP guardado.',
        onde: 'lib/partsDb.ts · enrollOne',
        nota: 'Sem nota, a caça de preço usa o eBay primeiro — à mão.' },
      { id: '9.6', estado: 'EM CONSTRUÇÃO',
        texto: 'O AutoBook atualiza o Parts DB sozinho depois de lançar a compra.',
        nota: 'Hoje o banco de peças só aprende pelo SCAN das telas ou à mão; o robô do e-mail não chama o cadastro de peças. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: '10',
    titulo: 'SALVA O COMPROVANTE',
    resumo: 'O documento do vendedor nos dois lugares, com o nome certo e sem cópia repetida.',
    regras: [
      { id: '10.1', estado: 'NO AR', desde: '24/08/2026',
        texto: 'O documento oficial do vendedor mora nos DOIS lugares: anexado na linha e na pasta da invoice. Sem os dois, o lançamento está incompleto.',
        fala: 'sempre o PRINTABLE INVOICE do vendedor nas expenses no app e na pasta purchases no dropbox.',
        onde: 'app/api/cron/invoice-receipts · app/api/ride-folder',
        nota: 'Desde 08/09 a pasta é a DA INVOICE; Purchases/ ficou só para o papel que não se sabe de qual invoice é.' },
      { id: '10.2', estado: 'À MÃO', desde: '26/07/2026',
        texto: 'É o documento REAL: o PDF do vendedor ou a versão printer-friendly da loja. Quando a prova é um e-mail, ele vira PDF — nunca HTML, nunca documento redigitado.' },
      { id: '10.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Compra dividida entre carros: toda linha leva o documento da compra INTEIRA, e o arquivo vai para a pasta de TODAS as invoices que entraram nela. O elo é fornecedor + número do pedido.',
        fala: 'toda compra rateada deve ter o arquivo em todas as pastas',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Nome canônico: [código da invoice] [carro] - [fornecedor do cadastro] [pedido].pdf. Quem nomeia é a rota, lendo o banco — renomear a invoice, renumerar o carro ou curar o fornecedor conserta os arquivos sozinho.',
        fala: 'Dentro desta pasta é onde devem ficar TODAS as invoices de expenses desta invoice, devidamente nomeadas, com o [cod invoice] [ride] - [supplier] [order #].',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.5', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Duplicata se mede pelo CONTEÚDO (content_hash), nunca pelo nome: não sobe de novo o que já está lá, apaga a cópia de nome velho com o mesmo conteúdo e tira da Purchases o que já está idêntico na pasta da invoice.',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.6', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O que não bate com documento nenhum FICA. Papel posto à mão não se apaga por dedução.',
        onde: 'app/api/ride-folder · invoice-receipts' },
      { id: '10.7', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Se o e-mail trouxer um documento MELHOR que o salvo na pasta, o robô anexa o novo, salva com o nome certo e mantém o arquivo original.',
        fala: 'pode ser que no email chegue uma invoice mais apropriada, se for este o caso o AutoBook registra no app esta invoice nova, salva na pasta com o nome certo e mantém o arquivo original meu lá',
        nota: 'Passo 8 da especificação entregue ao App development em 09/09.' },
      { id: '10.8', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O robô que lança anexa o comprovante na mesma hora.',
        fala: 'o AutoBook registra aquela compra na invoice em questão, anexando o comprovante',
        nota: 'Hoje a linha lançada por regra nasce sem comprovante, e a fila registra «falta a printable invoice». Passo 7 da especificação de 09/09.' },
      { id: '10.9', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Quem escreve direto no banco também leva o papel: de 2 em 2 horas, toda invoice cuja despesa com comprovante mudou nas últimas 6 horas tem a pasta sincronizada.',
        onde: 'vercel.json (23 */2) · app/api/cron/invoice-receipts' },
      { id: '10.10', estado: 'NO AR', desde: '01/08/2026',
        texto: 'Comprovante anexado = despesa paga: a data do pagamento entra sozinha, a cada 5 minutos.',
        fala: 'Se tem comprovante, está PAGA.',
        onde: 'lib/expenseReportNet.server.ts · enforceReceiptPaid',
        nota: 'Na agendada de custo fixo a baixa acontece pelo valor ESTIMADO — defeito descrito na 14.7.' },
    ],
  },
  {
    id: '11',
    titulo: 'ARQUIVA O E-MAIL',
    resumo: 'Resolvido sai da caixa; pergunta aberta fica à vista.',
    regras: [
      { id: '11.1', estado: 'NO AR', desde: '07/09/2026',
        texto: 'O que o robô resolve sai da caixa na mesma passada. O que virou pergunta fica na caixa de entrada até ser respondido.',
        fala: 'porque tem tanto email da sua pauta ainda na minha caixa?',
        onde: 'lib/autoBookMail.server.ts · arquiva' },
      { id: '11.2', estado: 'NO AR', desde: '07/09/2026',
        texto: 'Destino em degraus: a pasta do FORNECEDOR e, sem ela, «Purchases». O robô nunca cria pasta; sem destino, reporta.',
        onde: 'arquiva' },
      { id: '11.3', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Fechado o lançamento, a THREAD inteira daquela compra vai para a pasta do carro. O que entra é a compra — pedido, fatura, assunto —, nunca todos os e-mails do fornecedor.',
        fala: 'ah, e o AutoBook processa os emails referente a esta compra, guarda todos na pasta do carro.',
        nota: 'Passo 11, entregue ao App development em 09/09. A rota que arquiva já existe (/api/stream/mail-file); falta o robô chamá-la. Hoje é feito à mão.' },
      { id: '11.4', estado: 'FURO', desde: '02/09/2026',
        texto: 'Processado = na pasta E marcado: a marca d’água diz o que o e-mail virou (tabela e linha).',
        fala: 'todos os emails processados devem ir pra sua pasta e marcados como processados',
        onde: 'app/api/stream/mail-file · mail_processed',
        nota: 'A rota de arquivar grava a marca sozinha; o robô de hora em hora move o e-mail direto no Outlook e não deixa marca.' },
      { id: '11.5', estado: 'EM CONSTRUÇÃO',
        texto: 'As caixas do Gmail também são arquivadas pelo robô.',
        onde: 'arquiva',
        nota: 'Hoje só as caixas Outlook. A rota de arquivar já sabe mover no Gmail desde 04/09. Ainda não pedido ao App development.' },
      { id: '11.6', estado: 'À MÃO', desde: '04/08/2026',
        texto: 'Processar inclui os ENVIADOS: e-mail que mandamos sobre a compra vai para a mesma pasta da thread.',
        fala: 'PROCESS means all emails, not only the incoming ones!' },
      { id: '11.7', estado: 'NO AR', desde: '17/09/2026',
        texto: 'O robô só tira e-mail da CAIXA DE ENTRADA. Carta que já está em outra pasta foi guardada por alguém e fica onde está.',
        onde: 'lib/autoBookMail.server.ts · arquiva',
        nota: 'O leitor lê a caixa inteira. Em 16–17/09 o robô levou duas vezes para «Purchases» as cartas da United HGCVN5 que a rodada de e-mail tinha guardado em «Businesses/Trips/Bruno Guerreiro», e repetia o move a cada hora.' },
    ],
  },
  {
    id: '12',
    titulo: 'A DÚVIDA',
    resumo: 'O robô só faz sozinho o que não precisa de decisão. O resto vira pergunta com lugar, e a resposta vira regra.',
    regras: [
      { id: '12.1', estado: 'NO AR', desde: '06/09/2026',
        texto: 'Não resolveu sozinho: UMA pergunta na fila, com fornecedor, pedido, valor, moeda, o que falta e onde procurou. Dinheiro nunca some calado — não existe terceira saída.',
        fala: 'ensine o robô a fazer o round de 1 em 1 hora, pra que ele deixe pra vc aqui só o que ele tiver dúvida.',
        onde: 'auto_book_mail (status DOUBT)',
        nota: 'Medido em 10/09: 1 dúvida aberta, 7 lançadas, 10 ignoradas.' },
      { id: '12.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'As sugestões de destino vêm medidas: primeiro a PASTA, com o arquivo que provou; depois o HISTÓRICO do fornecedor, com a contagem real. Número inventado, nunca.',
        onde: 'candidatosDaPasta / candidatosPara' },
      { id: '12.3', estado: 'NO AR', desde: '07/09/2026',
        texto: 'A resposta resolve o e-mail (lança ou ignora) e, marcada para aprender, vira regra: o mesmo caso nunca mais é perguntado.',
        onde: 'POST /api/auto-book · auto_book_mail_rules' },
      { id: '12.4', estado: 'FURO', desde: '10/09/2026',
        texto: 'Regra aprendida tem teto de valor, validade e desfazer.',
        onde: 'lancar · auto_book_mail_rules',
        nota: 'Hoje a regra nasce de UMA resposta, sem teto nem validade, e o que ela lança não deixa trilha para desfazer (achado 4 do João).' },
      { id: '12.5', estado: 'EM CONSTRUÇÃO',
        texto: 'A fila de dúvidas tem tela.',
        nota: 'Hoje só a Claudinha lê a fila. Candidata a próxima aba desta página.' },
    ],
  },
  {
    id: '13',
    titulo: 'DEPOIS DE REGISTRADO',
    resumo: 'Report, rastreio e conferência — o que acontece com a linha depois que ela existe.',
    regras: [
      { id: '13.1', estado: 'NO AR', desde: '01/08/2026',
        texto: 'Report no grupo SÓ quando o dinheiro entra ou sai agora — a data do dinheiro nos últimos 3 dias. Lançamento retroativo, correção e edição são silêncio.',
        fala: 'ENTROU ou SAIU $? REPORT.',
        onde: 'lib/expenseReportNet.server.ts · runExpenseReportNet' },
      { id: '13.2', estado: 'NO AR', desde: '30/08/2026',
        texto: 'Rastreio, entrega e estorno moram na LINHA da compra. O status BOUGHT, SHIPPED ou DELIVERED é calculado, nunca escrito.',
        fala: 'as infos de ORDER NUMBER, TRACKING e STATUS vivem nas origens das compras',
        onde: 'lib/mailToItem.server.ts · lib/deliverStatus.ts' },
      { id: '13.3', estado: 'NO AR', desde: '04/08/2026',
        texto: 'Depois de lançada a compra, os e-mails seguintes só atualizam fatos, casados pelo número do pedido: nunca sobrescrevem um rastreio que já existe e nunca desfazem entrega ou estorno.',
        onde: 'lib/mailToItem.server.ts' },
      { id: '13.4', estado: 'NO AR', desde: '30/08/2026',
        texto: 'A transportadora é perguntada de hora em hora pelos números de rastreio já gravados nas linhas.',
        onde: 'vercel.json (37 * * * *) · app/api/items/track' },
      { id: '13.5', estado: 'NO AR',
        texto: 'A linha do extrato do banco é ligada ao registro pelo motor do Bank Link (sessão do João), que só lança quando ninguém lançou. Garantir que TODA movimentação fique casada é papel do AutoBook — etapa 14.',
        onde: 'lib/bankReconcile.server.ts',
        nota: 'Até 13/09 eram dois robôs que não se liam. Em 13/09 o Márcio pôs o casamento dentro do processamento do AutoBook (14.1); o motor continua sendo a ferramenta que grava o casamento.' },
      { id: '13.6', estado: 'NO AR', desde: '10/09/2026',
        texto: 'O Data Checker confere os dois robôs lado a lado e pergunta a gente quando eles discordam.',
        onde: 'lib/enginesAudit.server.ts · card «Os dois motores concordam?»' },
      { id: '13.7', estado: 'À MÃO', desde: '11/09/2026',
        texto: 'Gasto real que ainda não saiu no grupo e que a rede de 5 minutos não vai mandar — compra de poucos dias achada só agora, goods, inputs, custo fixo, estorno — sai no grupo REPORTS à mão, no formato do balão da rede. A data de REPORTED da linha (reported_at, 13.9) é gravada ANTES de mandar, pela mesma reserva da rede; sem ela, a rede manda de novo.',
        fala: 'não esqueça de mandar os gastos reais no grupo de report. E tem que ficar marcados como enviados, pra não enviar duplicado depois.',
        onde: 'lib/reportedAt.ts · claimReport · /api/report-net/mute',
        nota: 'A rede cobre só invoice_expenses, receitas e folha, e só com a data do dinheiro nos últimos 3 dias (13.1). Na mesma ordem ele disse: «Não esqueça de reportar qualquer saída ou entrada de $ nos grupos de report». Estorno reporta quando o dinheiro CAI; até lá a linha fica CANCELLED.' },
      { id: '13.8', estado: 'FURO', desde: '12/09/2026',
        texto: 'Compra real escrita POR CIMA de um placeholder antigo some da rede de report: a rede só lê linha com updated_at depois do EPOCH (26/07/2026), e escrever por fora do app não encosta nesse campo. Quem escreve por cima tem de gravar updated_at junto — senão o balão sai com uma parte da compra e ninguém percebe, porque a parte que falta nunca é perguntada.',
        onde: 'lib/expenseReportNet.server.ts · EPOCH · runExpenseReportNet (.gte(updated_at, EPOCH))',
        nota: 'Medido na HHP #384917 (12/09/2026, US.022.2 Apocalypse, US$ 4.112,27): das 5 linhas, 3 entraram por cima de placeholders de 12/07 e ficaram invisíveis — o grupo recebeu US$ 2.821,12 de 2 itens às 01h06 Orlando. Destravado encostando no updated_at; o complemento de US$ 1.291,15 saiu na passada seguinte, por ordem dele («Rede manda o complemento»). O mesmo alçapão pega qualquer escrita por fora do app.' },
      { id: '13.9', estado: 'NO AR', desde: '16/09/2026',
        texto: 'Toda linha de dinheiro sabe se já foi reportada: a coluna reported_at (vazia = NÃO, com data = REPORTED) nas 8 tabelas — invoice_expenses, invoice_incomes, staff_expenses, assets, assets_expenses, inputs, inventory, fixed_cost_expenses. Nenhum robô nem tela reporta linha com data. Quem vai mandar RESERVA a linha antes (só pega linha sem data) e só manda o que reservou. Dinheiro que o banco já anunciou no grupo (ZELLE ENVIADO / RECEBIDO, mesmo valor, até 3 dias) ganha data em silêncio quando a linha é lançada depois; a renda que o Zelle watch lança nasce REPORTED.',
        fala: 'o app está mandando report de expense que já havia mandando, crie uma coluna no banco pras expenses e incomes as marcando como REPORTED ou NÃO, pra nunca mais acontecer isso. O App não reporta mais coisa que já reportou.',
        onde: 'lib/reportedAt.ts · claimReport · lib/expenseReportNet.server.ts · runExpenseReportNet / anunciosDoBanco · app/api/cron/recurring-expense-reports · lib/reportMark.ts (telas) · lib/zelleWatch.server.ts · lib/appsMail.server.ts',
        nota: 'Três furos repetiam balão: (1) o cron de staff mandava, a cada 7 dias, um balão para CADA linha semanal da season, paga ou prevista — a enxurrada de 17/08 e a semana paga em 14/08 reportada de novo em 14/09; agora só linha paga, sem data e de até 3 dias, uma vez; (2) o «já reportei» morava fora da linha (stream_mail_moves ern:<tipo>:<id> e expense_reports_sent), e linha recriada saía de novo — as marcas antigas viraram a coluna na MIGRATION_reported_at.sql (trilha data_fixes reported-at-backfill); (3) o dinheiro do Zelle saía duas vezes — Raydn 003598: US$ 329,56 no ZELLE ENVIADO de 15/09 e de novo dentro do EXPENSE PAID de US$ 408,81 em 16/09. As 331 compras do balde A ATRIBUIR ficaram sem data de propósito: o balão da atribuição ainda tem de poder sair.' },
    ],
  },
  {
    id: '14',
    titulo: 'CASA COM O BANCO',
    resumo: 'O processamento só termina aqui: a movimentação do banco ligada ao registro no app. Lançado e sem casar é processamento em aberto; linha do banco sem processamento nenhum é gatilho.',
    regras: [
      { id: '14.1', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'O processamento do AutoBook só está CONCLUÍDO quando a movimentação no banco está casada com o registro no app. Lançar não conclui: enquanto a linha do extrato estiver sem casamento, o gasto ou a receita segue em processamento. Casar toda a movimentação financeira com o app é papel do AutoBook.',
        fala: 'o AutoBook PROCESSING só está concluído quando a movimentação financeira no banco está casada com app, enquanto isso não está feito, o processamento não está concluído … é papel do AutoBook CASAR toda a movimentação financeira com o app',
        onde: 'bank_transactions.match_status · Bank Link (/api/bank/reconcile: match, match_adjust, unmatch, ignore)',
        nota: 'Hoje quem casa é a Claudinha, à mão, pelas ações do Bank Link na sessão logada do Márcio; cada caso aprendido vira regra nesta etapa e pedido ao App development, até o robô fazer tudo. Medido em 13/09 (06 a 13/09): 102 linhas na Regions, 41 casadas, 17 pendentes, 44 compensadas sem casamento.' },
      { id: '14.2', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Linha PENDENTE no banco não casa: espera compensar, porque o Plaid troca o id da linha ao postar. O processamento dela fica aberto até lá.',
        onde: 'lib/bankReconcile.server.ts · humanMatch (recusa pending)' },
      { id: '14.3', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Valor igual ao centavo e mesma compra: liga a linha do banco ao registro que já existe. Dinheiro que já está no app nunca ganha um segundo lançamento.',
        onde: 'Bank Link · match',
        nota: 'eBay, 13/09: rodas Welds (HellKing), faróis Morimoto e hood pin (Apocalypse), emblemas (HellMonster), conector do pisca (GoldenEye) — todos lançados certos e sem casamento.' },
      { id: '14.4', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Uma cobrança que pagou vários registros casa com todos juntos: itens do mesmo pedido pelo grupo de compra; despesas de staff (duas passagens, dois seguros) pelo «casar com ajuste», até 3, com a diferença de câmbio rateada ao centavo.',
        onde: 'Bank Link · match (purchase_group) · match_adjust (expense_group)',
        nota: 'Seguro Promo 1187616 (Guilherme + João Luca, US$ 212,78) e passagem Copa AZPYJG (US$ 750,44 estimado → US$ 764,11 do banco), 13/09.' },
      { id: '14.5', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Linha que o motor mandou para o balde «A ATRIBUIR» e já tem dono: DESFAZER no Bank Link (o app apaga a compra do balde), lançar no lugar certo com o comprovante, e casar. Equipamento da oficina vai para GOODS; seguro e passagem de staff, para a season (8.16); merch da marca, para MARKETING (8.15).',
        onde: 'Bank Link · unmatch + match / match_adjust',
        nota: 'JEGS gaveteiro 97259544 e carrinho 97298972 → GOODS; seguro Promo 1187616 → seasons; 13/09.' },
      { id: '14.6', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Compra que voltou inteira (cancelada pelo vendedor ou devolvida), com a cobrança e o estorno no banco, não é gasto: DESFAZ a cobrança do balde e as duas linhas ficam IGNORADAS com a nota «COMPRA ESTORNADA» e o número do pedido. Compra que ficou, com estorno parcial, segue a 8.10.',
        onde: 'Bank Link · unmatch + ignore',
        nota: 'eBay 01-14353-04110 (porcas de roda, cancelado) e 03-14444-12482 (amortecedores do porta-malas, devolvidos), Camaro, 13/09.' },
      { id: '14.7', estado: 'FURO', desde: '13/09/2026',
        texto: 'Agendada só vira paga com o valor do recibo. Se o valor real é diferente do estimado, a linha ganha o valor real antes da baixa — senão o banco não acha o gêmeo, o Bank Link lança outra linha e o mês fica em dobro.',
        onde: 'lib/expenseReportNet.server.ts · enforceReceiptPaid (10.10)',
        nota: 'Hoje o comprovante anexado dá baixa na agendada pelo valor ESTIMADO. Caso Supabase ago/2026: US$ 25 (estimativa baixada) + US$ 44,03 (Bank Link) para uma fatura de 44,03 — a de 25 foi apagada em 12/09.' },
      { id: '14.8', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Dinheiro que não passa pela Regions (C6 do BR, cartão pessoal, conta de sócio) fecha pelo comprovante, não pelo extrato: a linha diz de onde saiu, e a falta de casamento na Regions não reabre o processamento.',
        nota: 'Aluguel do galpão de maio/2026 pago pela Connect (C2B), decisão dele em 13/09; multa da Emive paga pelo C6 da Galpão.' },
      { id: '14.9', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Os dois caminhos terminam no mesmo lugar. Com e-mail: o robô detecta a movimentação, processa e lança pelos meios já ensinados, e quando a linha aparece no Plaid ele CASA e fecha. Sem nada antes: a linha do Plaid que nenhum processamento tocou vira o GATILHO e dispara o processamento dessa despesa — descobrir o que é, lançar e casar —, que só fecha casado.',
        fala: 'quando a movimentação aparece no plaid, o robô CASA a movimentação e finaliza o processamento · quando surge uma linha no plaid que não havia sido processada de nenhuma forma prévia, o paid passa a ser o trigger e dispara o processamento desta despesa, até que esteja casada no app',
        onde: 'bank_transactions (match_status NEW, compensada) → etapas 7 a 13 → Bank Link',
        nota: 'Hoje o motor do Bank Link manda a linha sem dono para o balde «A ATRIBUIR» ou deixa NEW; o gatilho que abre o processamento é à mão, pela Claudinha.' },
      { id: '14.10', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Para descobrir o que é uma linha do banco que chegou sem e-mail, o primeiro lugar de busca são os grupos TIME e STAFF do app US: é onde o time posta a foto do recibo, pede a compra e avisa o que pagou.',
        fala: 'o melhor lugar pra buscar o que são estas movimentações são os grupos TIME e STAFF (app do US)',
        onde: 'espelho whatsapp_messages (banco US): 🇺🇸GZ28US Time 🇺🇸 120363422206851200@g.us · GZ28US - STAFF 120363400165413030@g.us — só a linha canônica (duplicate_of nulo)' },
      { id: '14.11', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'O app espelha o Plaid: o que o banco mostra em linha separada vira linha separada no app; o que o banco mostra junto fica junto. O valor do registro é o que saiu ou entrou na conta — imposto cobrado junto entra no valor; tarifa descontada antes de chegar não vira receita.',
        fala: 'se no plaid aparece em linha separada, na invoice em linha separada, se no plaid mostra junto, junto na invoice, tem que ser como é no plaid.',
        nota: 'Casos de 13/09: kit de teste de pressão da Amazon lançado sem o imposto (62,99 → 67,08, o que saiu); entrada do Nasser pela Global66 para a SublimeHell (8.350 lançado → 8.345, o que entrou); pagamentos do Demon Preto com US$ 23 que não saíram no wire.' },
      { id: '14.12', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'A tarifa de wire de SAÍDA da Regions (US$ 23 por wire) não vem no wire: chega no mês seguinte, somada na «ANALYSIS CHARGE» (por volta do dia 9) com a base mensal de US$ 24. A linha do pagamento na invoice leva só o valor do wire, e a analysis charge fica inteira como tarifa bancária. A tarifa de wire de ENTRADA (US$ 15) vem em linha própria, no mesmo dia.',
        onde: 'bank_transactions «ANALYSIS CHARGE MM-AA» · fixed_cost_expenses (fornecedor Regions Bank, motor FEE)',
        nota: 'Medido em 13/09: 09/07 US$ 93 = 24 + 3×23 (wires a partir de 17/06); 10/08 US$ 231 = 24 + 9×23; 09/09 US$ 116 = 24 + 4×23. Esperado por volta de 09/10: US$ 139 = 24 + 5×23 (4 wires para a Surf City e 1 para a TAG). Antes de 15/06 a tarifa vinha em linha própria («DOMESTIC OUT FEE», US$ 30).' },
      { id: '14.13', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Consumível usado em vários carros (gás do A/C, fluido, lixa) conta por unidade inteira e casa pela linha do tempo: cada compra alimenta os usos que vieram DEPOIS dela; o que sobra fica no estoque designado ao carro que vai usar; a mesma unidade nunca entra em dois carros. Uso anterior à compra saiu de estoque que já estava pago em outra linha.',
        fala: 'são 3 latas em cada carro, case pela linha do tempo, não registre nada duplicado no app · usa sempre 3 inteiras e mais um pouco em cada carro',
        nota: 'R-1234YF de set/2026: compra do HellMonster de 07/08 (4 latas) → Colossus 3 (carga de 04/09) + SublimeHell 1; AutoZone 02484257449 de 07/09 (8) → Dracula 3 + WorkTruck 3 + SublimeHell 2; GoldenEye 1586195 de 08/09 (4) intactas. Estoque medido com ele: GoldenEye 4 + SublimeHell 3.' },
      { id: '14.14', estado: 'FURO', desde: '13/09/2026',
        texto: 'Posto pago no CAIXA (MCC 5541) não é combustível: na casa é cigarro do Márcio (pessoal, season US.008), cerveja (insumo CONSUMPTION) ou comida do time (insumo TEAM). Combustível é a BOMBA (MCC 5542). Sem recibo, a linha de caixa vira pergunta, não Frota.',
        onde: 'bank_merchant_rules · def:fuel (lib/bankReconcile.server.ts, RULE_AGE_DAYS)',
        nota: 'Hoje a regra def:fuel manda toda linha de posto para o custo fixo Frota depois de 7 dias, inclusive as de caixa. Medido em 13/09: das cobranças de caixa com recibo, nenhuma era combustível; BP 30,45 (29/08), Wawa 48,10 (31/08) e BP 105,65 (03/09) estavam no Frota: eram cigarro do Márcio (resposta dele, 13/09) — movidos para a season US.008 e recasados.' },
      { id: '14.15', estado: 'NO AR', desde: '13/09/2026',
        texto: 'Cobrança que mistura gasto pessoal e custo da empresa (cigarro + cerveja no mesmo caixa) casa com as duas partes: a pessoal na season da pessoa e a da empresa na tabela dela, somando o valor da linha. Entrada que paga rendas de mais de uma invoice casa do mesmo jeito, com todas as rendas.',
        onde: 'Bank Link · match_mixed (BL 1.6.0): saída com 2 a 10 registros de invoice_expenses, inputs, inventory, assets, staff_expenses e fixed_cost_expenses; entrada só com invoice_incomes',
        nota: 'No ar em 13/09 (App development). Casados na hora: Wawa 5205 US$ 115,44 = Newport ×10 pessoal 90,15 + cerveja 25,29 · wire Tamiami −128.000 = US.049.1 + US.050.1 · wire Elite −36.500 = US.032.1 HellRaisin 35.000 + US.031.1 Joker 1.500. Misto com SINAL (BL 1.6.1): o lado da linha soma e o oposto desconta — repasse da Stripe −1.318,84 = 4 credenciais SEMA em custo fixo negativo (+1.375,00) − tarifas Stripe 56,16, casado em 13/09.' },
      { id: '14.16', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Destinos aprendidos casando a Regions: E85 do dyno vai na invoice do carro que está no dyno (não no Frota); lanche e comida do time vão em insumos TEAM; cerveja, em insumos CONSUMPTION; cigarro do Márcio é gasto pessoal na season dele; compra para o apartamento é APARTMENT; ferramenta e peça comprada para um carro vão na invoice dele.',
        fala: 'comida pro team, como os demais',
        nota: 'Casos de 13/09: RaceTrac 586 (US$ 114,43) e os galões de E85 de 01, 02 e 05/09 → Colossus US.003.1 (os de 01 e 02/09 saíram do Frota); Steak n Shake, McDonald\'s e Wawa 19,47 → TEAM; Coronita ×2 → CONSUMPTION; BP 30,45 e Newport ×10 → season US.008; Ross → APARTMENT; mangueira 5/8" → Colossus; Little Trees → WorkTruck.' },
      { id: '14.17', estado: 'EM CONSTRUÇÃO', desde: '13/09/2026',
        texto: 'Dinheiro que cruza as empresas — PAID FROM ou PAID TO entre GZ28US e GZ28BR, nos dois apps e nas duas direções — só casa com o income ou a despesa que está dentro da SHOPPING INVOICE da empresa no app da outra. Cliente do BR que paga na conta do US vira income numa shopping invoice do GZ28BR no app US, abatendo a dívida; despesa do US paga com dinheiro do BR vira despesa numa shopping invoice do US no app BR. Enquanto a shopping invoice não existe, a linha do banco espera — nunca fecha como transferência nem como ignorada.',
        fala: 'TODA E QUALQUER movimentação financeira entre o US e o BR tem que estar nas shopping invoices · Sempre que os recursos PAID FROM & TO entre US e BR são usados, tem que ter a shopping invoice no app da outra · ISSO É SAGRADO',
        onde: 'shopping invoices 006.xx (US) e a série espelho no BR · página US vs BR Flow',
        nota: 'Pedido ao App development em 13/09. Caso que ensinou: ACH de US$ 1.402,00 da New Times Agency em 25/08 = Corvette C8 do Gabriel (BR.537.1), com o income no app BR e PAID TO GZ28US — a linha segue NEW até a shopping invoice do GZ28BR existir no app US.' },
      { id: '14.18', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Linha do banco sem nome (DEPOSIT, CHECK, Zelle com nome de empresa) só vira pergunta depois da caça inteira: (1) refund já esperado no fornecedor de custo fixo; (2) dinheiro devolvido combinado por e-mail ou WhatsApp; (3) renda CASH/CHECK ainda sem banco; (4) conversa do cliente que tem renda aberta do mesmo valor; (5) e-mail de confirmação do Zelle, que traz o nome real, o valor e a mensagem. O robô vai atrás da resposta onde ela pode estar.',
        fala: 'O App tem que "ser inteligente", procurar onde pode ter as respostas que ele precisa · claro que vc sabe, isso foi refund da progressive',
        nota: 'Casos de agosto: DEPOSIT 442,30 (07/08) = os 2 cheques de refund da Progressive 870429263 (161,31 + 280,99), já anotados no fornecedor · DEPOSIT 3.000 (12/08) = frete do SublimeHell devolvido em dinheiro pela Arizona Motors (e-mail do Márcio ao Robb em 02/08: «send the $3,000 freight money in an envelope with the car») · ZELLE TO ARPM SERVICE 20 (31/07) = Roberta Pirolla, decals RH do JailBreak170 (e-mail do Zelle, conf 5776902815).' },
      { id: '14.19', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Cobrança da Temu paga pelo PayPal é o CHECKOUT, não o pedido: um pagamento cobre vários POs (os que começam com o mesmo prefixo, ex. PO-211-1160…), e o one-click pay parte um PO em duas cobranças. O e-mail do PayPal traz valor, data e o prefixo do PO; casa pela soma exata dos itens livres desse prefixo. Brinde de US$ 2,99 conta. Linha que o Bank Link jogou no balde «Temu (a atribuir)» com os itens já lançados em inputs sai do balde (REMATCH) — senão o custo fica em dobro.',
        nota: 'Agosto: 36,80 = espelho + 2 brindes · 22,89 = sanduicheira + brinde · 26,36 = mandolina + porta-papel · 48,51 = pantufas + tábuas · 30,29 = ganchos + brinde · kit casa 44,44 = 24,23 + 20,21 · baldes 79,91, 56,45, 41,62 e 10,49 trocados pelos itens.' },
      { id: '14.20', estado: 'À MÃO', desde: '13/09/2026',
        texto: 'Destinos aprendidos em agosto: loja de departamento sem recibo depois da mudança pro Luma (Ross, Marshalls, TJ Maxx, HomeGoods, Walgreens) é APARTMENT, uma linha por cobrança, e devolução entra negativa; restaurante com o time (buffet, pizza) é insumo TEAM; recarga do SunPass divide igual entre os carros da conta (RAMbo e GENEZIZ); taxa do cashier’s check vai junto da linha que ele pagou; taxa de cartão da oficina de funilaria vai no extra da linha do serviço.',
        fala: 'All apartment · Both team food · Split 25 / 25',
        nota: 'Casos: 28 cobranças de loja (US$ 1.249,46) · Crazy Buffet 120,54 e Singas Pizza 80,39 · SunPass 50 = 25 + 25 · move-in do Luma 4.015,96 + 10 = 4.025,96 · Auto Body RO 9433 852,80 + 23,02.' },
      { id: '14.21', estado: 'NO AR', desde: '13/09/2026',
        texto: 'Tudo o que está na Regions é GZ28US: registro de gasto casado com linha do banco é PAID FROM GZ28US e renda casada é PAID TO GZ28US, sempre, onde o campo existe. E o avesso: registro PAID FROM ou PAID TO GZ28US sem linha na Regions está errado — ou falta o casamento, ou o pagador é outro e tem que ser designado. Nos dois apps: o que o app BR diz PAID FROM/TO GZ28US também passou pela Regions e casa pela shopping invoice (14.17). A meta é casar TODAS essas linhas.',
        fala: 'todos os gastos que vc vê no plaid do Regions são PAID FROM GZ28US, certo? NUNCA outra opção · tudo que está no PLAID é PAID FROM GZ28US, o que não está no PLAID, não é, temos que designar · tudo que tem no Regions é PAID FROM (expenses) e PAID TO (incomes) GZ28US! Claro que só onde existe este campo no app',
        onde: 'Bank Link 1.7.0 · writeMatch carimba o que o casamento cobre — alvo, purchase_group, expense_group e misto (app/api/bank/reconcile/route.ts) · Data Checker paid-from, paid-no-bank e house-payer (app/adm/check/page.tsx)',
        nota: 'Medido em 13/09: 23 registros casados com a Regions estavam com PAID FROM vazio (8 invoice_expenses, 2 inputs, 6 staff_expenses, 7 fixed_cost_expenses — inclusive os 7 Claude de 11/09 casados pelo motor) → GZ28US, com trilha CERTO (Regions) para o DESFAZER. As 64 rendas casadas já eram PAID TO GZ28US. O furo: casar um registro que já existe não crava o campo, e o card «Paga no app, sem linha no banco» só olha custo fixo. Sem banco e marcados GZ28US: ~300 gastos pagos no US (PAYPAL 132, sem método 117, CASH 33) e 102 rendas; no BR, 42 gastos PAID FROM e 1 renda PAID TO GZ28US. Caso que ensinou: 006.25 do Cesar Tellez, US$ 1.440,90, dizia GZ28BR e saiu do cartão da Regions. NO AR em 14/09 (App development, BL 1.7.0): todo casamento novo crava paid_from GZ28US onde está vazio (inventory só PURCHASED) e paid_to GZ28US na renda, com rastro no backfill e em data_fixes (check_key paid-from), que o DESFAZER devolve; pagador GZ28BR escrito é recusado com 409 antes de gravar. Nada retroativo: os já casados sem pagador (ex.: os 4 créditos SEMA da Stripe) ficam para o card do Data Checker.' },
      { id: '14.22', estado: 'NO AR', desde: '13/09/2026',
        texto: 'Compra em moeda estrangeira gera na Regions uma segunda linha, a INTERNATIONAL SERVICE ASSESSMENT (3%): é custo da mesma compra, não tarifa do banco. Casa com um registro próprio no mesmo lugar da compra — passagem na season de quem viajou, dividida por pessoa quando o bilhete é de mais de um. Passagem vale o valor EXATO de cada passageiro, tirado do e-ticket (PDF anexo do e-mail da Copa), cada um na sua season, nunca misturado.',
        fala: 'olhe no staff members, o Franco é um o Vanza é outro, registre as passagens de cada uma pra cada um, nunca misture · cada membro está com seu valor de passagens exato registrado no app?',
        onde: 'motor FEE do Bank Link 1.7.0: procura a compra-mãe (saída ±2 dias, mesmo comerciante, 3% exato em centavos); mãe casada com UM registro → a tarifa nasce no mesmo lugar (invoice aberta, mesma season e origem, mesmo fornecedor do custo fixo); grupo, gêmea ou nenhuma → custo fixo da Regions',
        nota: 'Casos de 13/09: Vanzela junho 312,33 + 9,37 e julho 356,86 + 10,71 · Franco 403,75 + 12,11 e Jeferson 403,74 + 12,11 (BLTISL) · João Luca e Guilherme 11,46 cada (AZPYJG) · compensação de carbono do Jeferson + 0,19. As 6 tarifas saíram do custo fixo por REMATCH. NO AR em 14/09 (BL 1.7.0; 1.7.1 põe paid_to GZ28US na de custo fixo): nas 19 tarifas históricas o 3% bate exato. Limite: a tarifa é lançada na hora; se a compra-mãe só for casada depois, ela já foi para a Regions e o REMATCH à mão continua valendo. Bilhete de mais de um passageiro (misto ou grupo) segue para a Regions pela regra — dividir por pessoa continua à mão.' },
      { id: '14.23', estado: 'À MÃO', desde: '14/09/2026',
        texto: 'Entrada de cliente só casa com renda — e renda só muda de valor — depois da régua inteira: (1) o comprovante anexado à renda, lido — o mesmo arquivo em várias rendas é um depósito pagando várias, com valores parciais; (2) a pasta do cliente (Sidney: o Excel CONTA CORRENTE, as abas antigas nos backups e os PDFs datados); (3) datas, WhatsApp (privado e grupos do carro) e e-mails; (4) outro depósito no Plaid com o valor exato; (5) pagamento partido — um depósito em várias rendas, uma renda em vários depósitos. Só com certeza a renda é ajustada ao que chegou; sem certeza, a linha fica NEW com as provas.',
        fala: 'Vc checou os comprovantes na pasta? Checou as datas e conversas de whats app? Já viu se não há outro depósito no plaid no valor certo? Viu se este pagamento não está vinculado a mais de um income? · se esta despesa foi do Sidney, está no CONTA CORRENTE, lá tem tudo de recente · aprenda estas estratégias, pois isso pode acontecer várias outras vezes',
        nota: 'Casos de julho (14/09). Wire Fast Builders 9.328 (08/07): o comprovante Wells Fargo OW00007174464549 está na renda da Tornado US.019.3 de 9.259,40, que é o depósito de R$ 50.000 do Sidney creditado a 5,40 (aba «2ª Compra SuperStock Preto»); a diferença de 68,60 é câmbio. Wire Elite 9.628 (16/07): a transferência BofA de «Business Adv Fundamentals - 7259», pedido 622951980, está pendurada em 9 rendas que somam 9.451,89 (BR 006.1–006.5 e 006.11, Panther 1.060, pneus do Calazans 2.799,91, Tornado 176,11); faltam 176,11. As duas ficaram NEW até o Márcio decidir se o crédito do cliente é o dólar que chegou (precedente: Tamiami, 14.600) ou a cotação combinada (a planilha).' },
      { id: '14.24', estado: 'FURO', desde: '14/09/2026',
        texto: 'Linha de posto (RaceTrac, Shell, Sam\'s, 7-Eleven, Texaco, Wawa) só vai para o combustível da frota depois de procurar, em ±3 dias, uma despesa de carro com a foto da bomba ou o recibo: valor igual até uns centavos, mesma loja. A foto manda — o valor do app é acertado ao da bomba (galões × preço saem em quantidade 1 com o total, gelo e loja em preço de prateleira + imposto) e a linha casa com o carro.',
        onde: 'motor RULE «combustível da frota» do Bank Link',
        nota: 'Casos de 14/09 (eu mesma tinha mandado 3 pra frota e desfiz): RaceTrac 58,32 (20/04) = DarkAngel 16,811 gal · Shell Miami 113,06 (28/05) = Panther · Sam\'s 78,43 (07/06) = GoldenEagle · 7-Eleven 102,39 = GoldenEagle · RaceTrac 49,24 (16/03, o motor pôs na frota) = HellCougar · gelo RaceTrac 14,02 e 21,02 e Texaco 19,11 = DarkAngel · Wawa 49,40 = recibo de 29/05 no Panther.' },
      { id: '14.25', estado: 'À MÃO', desde: '14/09/2026',
        texto: 'Entrada sem renda: antes de perguntar, ler as planilhas do Márcio em «GZ28US Tad/Financial Control» — Payment STREAM.xlsx (aba 1, bloco ALREADY PAID: data, carro e valor de cada pagamento recebido) e Cash Celsinho.xlsx (o depósito do Celso rateado em itens). O nome do carro no STREAM às vezes é o apelido antigo (DarkDemon = Apocalypse, GameOver = Tornado, HellKing = Demon Durepóxi da CONTA CORRENTE, Alcatraz US.014.1 = US.015.1).',
        nota: 'Casos de 14/09: Urus −7.045 e Fast Builders −10.000 (28/05) = HellKing «Invoice Due» 27/05 (STREAM + CONTA CORRENTE) · Fast Builders −7.680 = DarkDemon/Apocalypse (renda ajustada de 7.705) · Elite −618,42, Easy Work −8.279 e Fast Builders −2.481,60 = Alcatraz, que não tem renda no app · Elite −41.000 = «valor depositado» do Cash Celsinho · Paulo Pereira −1.930,50 = FireHawk, sem invoice.' },
      { id: '14.26', estado: 'À MÃO', desde: '14/09/2026',
        texto: 'Loja com conta online se lê na fonte. Amazon: a página de pagamentos dá data, cartão, valor e pedido; o Order Details do pedido dá o item e se foi devolvido — pedido devolvido inteiro vira par +/− no mesmo lugar (a cobrança sai do balde por rematch), devolução parcial é um negativo por estorno. AutoZone: o AutoZone Pro está SEMPRE logado no Chrome do Márcio — compra da AutoZone NUNCA vira pergunta a ele antes de ler a nota. Transaction History: marcar as notas e usar Download › .PDF (até 15 numa vez, um PDF combinado, uma página por nota); o View de cada linha mostra a mesma nota, mas o modal às vezes abre vazio. A nota traz loja, itens e core; o VEÍCULO impresso acima dos itens é só o carro que estava selecionado na conta na hora da compra e NÃO prova destino (25/09: juntas de catalisador com «2016 Ram 1500» eram da SpitFire) — o carro sai de pedido/grupo/foto ou vira pergunta; devolução é nota RETURN com a nota original, e core devolvido pode voltar em DINHEIRO, fora do cartão. Duas linhas do app com o MESMO arquivo de recibo são uma compra só.',
        fala: 'descubra o que foi, autozone está SEMPRE logada no chrome, SEMPRE, registre isso nas regras',
        nota: 'Casos de 14/09: 45 linhas da Amazon (fita, presilhas, cooler, ração dos gatos e conexões de vácuo devolvidas) · AutoZone 204,19 Panthera, 107,30 WorkTruck, retentores 8,58 × 2 (lojas 3812 e 6731 no mesmo dia), porcas 189 e kits Z23 devolvidos · Muffler Man 27,96: «2026 carry out» e «Welding» com o mesmo JPEG. 25/09: modal vazio desde 24/09; o Download › .PDF trouxe 9 notas de uma vez — cabo de chupeta 51,99 (oficina), 3M Super 77 ×2 e Goof Off (insumos), 4 juntas de catalisador (nota diz 2016 Ram 1500 → WorkTruck), bateria do RAMbo 199,99 com core de 22 devolvido em dinheiro, e a devolução do MO-339 da SublimeHell.' },
      { id: '14.27', estado: 'FURO', desde: '23/09/2026',
        texto: 'Estoque guarda na UNIDADE QUE SAI, em UMA linha só. Duas regras, as duas obrigatórias. (1) A UNIDADE é a que se usa ou se vende, nunca a embalagem: comprou 2 caixas de óleo e o consumo é por quarto, o estoque tem 24 QUARTOS a US$ 17,32 — jamais «2 caixas a US$ 207,84». Comprado a granel e vendido no varejo entra no varejo. (2) A FORMA é uma linha com a quantidade, nunca N linhas de 1: quantidade é CAMPO. A nota diz «24 × US$ 17,32» → quantity 24, unit_price 17,32. Vale para inventory, inputs e assets. Mesma peça, mesmo preço, mesmo pedido e mesma data = MESMA LINHA; preço ou pedido diferente = linha separada, porque aí é compra diferente. (3) NUNCA numerar a unidade na descrição — «frasco 1/24», «item 3 de 8», «unidade B». Isso transforma UMA peça em N peças diferentes aos olhos do app, e nenhuma tela consegue juntar depois: só mexendo no dado.',
        fala: 'sempre que for algo que é comprado BULK e vendido individualmente, tem que guardar no inventory individualmente na quantidade certa, não em bulk · foi o AutoBook que salvou as 2 caixas de óleo inteiras no estoque, corrija pra que isso não aconteça mais · several lines of the same item with 1 as quantity, the right way is one row with the proper quantity',
        onde: 'inventory (category STOCK) · FROM STOCK no editor de invoice agrupa na exibição desde 23/09 (commit c423565), mas o conserto é não criar as linhas',
        nota: 'Caso que ensinou, 23/09/2026: as 2 caixas de óleo Red Line 5W40 da AutoZone (nota 02484269649 de 18/09, 24 × US$ 17,32 = US$ 415,68) entraram como 24 linhas de quantidade 1, no mesmo purchase_group e com a MESMA nota dizendo «24 ×». A UNIDADE estava certa (quarto, não caixa); a FORMA, não. E o pior: cada descrição terminava com «— frasco N/24», o que fez 24 PEÇAS DIFERENTES — por isso o agrupamento do FROM STOCK (commit c423565) não juntou nada, e o conserto teve de ser no DADO. Consolidadas em 23/09 numa linha de quantidade 24; as 24 linhas inteiras ficaram em JSON na trilha data_fixes «estoque-bulk-uma-linha», com ROLLBACK escrito. Valor intocado: US$ 415,68. Conferido antes de apagar: zero referências em inventory_sales, part_stream_items e data_fixes; o casamento com o banco é por purchase_group, que não mudou.' },
      { id: '14.28', estado: 'FURO', desde: '25/09/2026',
        texto: 'Posto pago na BOMBA (MCC 5542 no extrato — «automated fuel dispenser») é SEMPRE combustível, sem pergunta: casa com a foto da bomba de um carro se houver (14.24), senão vai para o combustível da frota. Nunca vira cigarro, comida ou pessoal. É o outro lado da 14.14: caixa da loja (5541) pergunta; bomba (5542) não.',
        fala: 'se foi na bomba é sempre combustível, registre isso nas regras do AutoBook no app',
        onde: 'lib/bankReconcile.server.ts — mccKlass/classify (hoje 5541 e 5542 caem juntos em FUEL) · regra def:fuel',
        nota: 'Hoje o motor não separa bomba de caixa: 5541, 5542 e a pfc TRANSPORTATION_GAS viram o mesmo FUEL, e um casamento EXACT pode levar uma linha de bomba para pessoal. Medido em 25/09 na Wawa 5205: gasolina do WorkTruck 129,70 (21/09) = 5542, certo; e 78,21 (18/09) = 5542 estava casada como cigarro pessoal do Márcio (AUTO · EXACT) — ele conferiu em 25/09: era combustível do RAMbo. Movida para US.011.1 e recasada; a regra valeu até contra a lembrança dele. Comidas do time e cigarros saem 5541.' },
    ],
  },
]

// ═══ OUTRAS BOCAS — DINHEIRO QUE NÃO ENTRA PELO E-MAIL DE COMPRA ═════════════
export const OUTRAS_BOCAS: Etapa[] = [
  {
    id: 'A',
    titulo: 'ZELLE — RECEITA E PAGAMENTO',
    resumo: 'O dinheiro que entra ou sai por Zelle, lido do aviso do Regions.',
    regras: [
      { id: 'A.1', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Zelle nunca passa batido: a caixa inteira do gz28us@hotmail, em todas as pastas, é lida a cada 5 minutos, antes de qualquer robô arquivar.',
        fala: 'zelle is a serious thing, fix it, so it never happens anymore.',
        onde: 'lib/zelleWatch.server.ts · mail-poll' },
      { id: 'A.2', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Nunca duplica: o número de confirmação do Zelle é procurado nas receitas e nas despesas antes de lançar.',
        onde: 'zelleWatch' },
      { id: 'A.3', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Quem: o nome de quem mandou casa com o cadastro de clientes. Onde: a invoice que ESPERA aquele valor em aberto — não a mais recente.',
        fala: 'Recebeu um Zelle do Jesse McGee, a primeira coisa que o robô tem que fazer é ver se temos um cliente com este nome, se tiver, ele tem que ver se há alguma invoice dele com um valor próximo, tendo, é isso, ele deve cadastrar o income e apagar a linha anterior de income não paga, se houver, anexando o comprovante.',
        onde: 'zelleWatch' },
      { id: 'A.4', estado: 'NO AR', desde: '08/09/2026',
        texto: 'Igual ao centavo e única: lança e APAGA a pendente que quitou. Perto, mas não igual: lança e a pendente FICA, com a diferença no aviso. Empate entre duas: palpite, dito como palpite.',
        onde: 'zelleWatch' },
      { id: 'A.5', estado: 'NO AR', desde: '08/09/2026',
        texto: 'A receita nasce com a BAIXA (paid_at, meio-dia de Orlando). payment_date é só a data prevista, e só a baixa vira caixa.',
        onde: 'zelleWatch · lib/financials.ts' },
      { id: 'A.6', estado: 'NO AR', desde: '08/09/2026',
        texto: 'O comprovante é o próprio aviso do Regions, guardado na linha que recebeu. Falhar em guardar o papel nunca desfaz o lançamento.',
        onde: 'zelleWatch' },
      { id: 'A.7', estado: 'NO AR', desde: '13/08/2026',
        texto: 'Zelle ENVIADO nunca lança sozinho — falta o carro e a invoice: vira aviso com o memo do Zelle.',
        onde: 'zelleWatch' },
      { id: 'A.8', estado: 'EM CONSTRUÇÃO', desde: '08/09/2026',
        texto: 'Receita por wire, PIX ou cartão é caçada do mesmo jeito.',
        fala: 'O AutoBook, depois de pronto, tem que ser capaz de alocar no app qualquer gasto ou receita detectada!',
        nota: 'Hoje só o Zelle tem caçador. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: 'B',
    titulo: 'PAPEL SEM E-MAIL',
    resumo: 'Loja que não manda e-mail nunca acorda o robô. O sinal que sobra é o papel na pasta.',
    regras: [
      { id: 'B.1', estado: 'À MÃO', desde: '09/09/2026',
        texto: 'Loja que não manda e-mail — AutoZone, balcão, loja física, serviço por telefone — nunca dispara o robô: a compra é lançada à mão, a partir do papel salvo na pasta.',
        fala: 'AutoZone não manda email, logo, não há este trigger pras compras dele, faça manualmente agora.' },
      { id: 'B.2', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Arquivo fora do padrão de nome dentro da pasta de uma invoice é suspeita de compra não lançada: o app só renomeia o que tem linha no banco.',
        onde: 'lib/papelOrfao.server.ts · papeisOrfaos' },
      { id: 'B.3', estado: 'NO AR', desde: '09/09/2026',
        texto: 'A varredura conta, por invoice, os papéis na pasta contra os comprovantes no banco e dá o veredito: RECIBO A COLAR (a despesa existe sem comprovante), SUSPEITA DE COMPRA NÃO LANÇADA ou INVOICE FORA DESTE BANCO — sempre dizendo em qual banco perguntou. Só lê: não lança, não apaga, não renomeia.',
        onde: 'GET /api/auto-book?orfaos=1 · papeisOrfaos' },
      { id: 'B.4', estado: 'EM CONSTRUÇÃO',
        texto: 'A varredura roda sozinha, e o que ela acha vira pergunta na fila.',
        nota: 'Hoje só roda quando alguém chama a rota. Ainda não pedido ao App development.' },
    ],
  },
  {
    id: 'C',
    titulo: 'GRUPOS DO WHATSAPP → APP DO BR',
    resumo: 'No BR a compra acontece no grupo: o pedido, o Pix e o comprovante em foto.',
    regras: [
      { id: 'C.1', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Tudo que é comprado E PAGO reportado nos grupos COMPRAS e FINANCEIRO vira linha no app do BR. Pedido não é pagamento: «preciso dessa peça» não lança; «pix para …» e comprovante lançam.',
        fala: 'ensine o robô a registrar tudo que é comprado e pago reportado no grupo compras e financeiro, pro app do BR.',
        nota: 'Especificação entregue ao App development em 09/09.' },
      { id: 'C.2', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'O *asterisco* é o carro. Casa pelo conjunto de palavras do nome do carro, nunca por pedaço — «FireHawk» não é o «Hawk».',
        nota: '72 dos 94 rótulos usados desde 01/07 não casam exato com o nome do carro no app: falta um cadastro de apelidos por carro.' },
      { id: 'C.3', estado: 'EM CONSTRUÇÃO', desde: '09/09/2026',
        texto: 'Antes de tudo, descarta as mensagens do próprio número e os reports que o app manda no grupo — senão o robô lê o próprio relatório e lança de novo.' },
      { id: 'C.4', estado: 'NO AR', desde: '09/09/2026',
        texto: 'Mensagem repetida é dado: a mesma mensagem vista pelos dois números nasce marcada como repetida, e quem lê pergunta a um campo só.',
        fala: 'o app tem que identificar se é repetido',
        onde: 'whatsapp_messages.duplicate_of',
        nota: 'Medido em 10/09: 2.619 mensagens marcadas.' },
      { id: 'C.5', estado: 'NO AR', desde: '27/07/2026',
        texto: 'FINANCEIRO é foto de comprovante: o valor sai da imagem, lido pelo mesmo leitor do botão SCAN; a legenda diz para que foi.',
        fala: 'i want this feature to be done by the app, not by you here, automatically, with the PC closed',
        onde: 'financeiro_inbox (banco US) · app BR /api/cron/financeiro' },
      { id: 'C.6', estado: 'NO AR', desde: '27/07/2026',
        texto: 'Só lança sozinho com o CARRO identificado e o VALOR lido; sem os dois, a mensagem espera gente.',
        onde: 'app BR /api/cron/financeiro',
        nota: 'Medido em 10/09, últimos 14 dias: 128 posts — 1 lançado (29/08), 65 esperando gente, 62 descartados.' },
      { id: 'C.7', estado: 'À MÃO', desde: '11/09/2026',
        texto: 'Compra do BR que chega por e-mail (Mercado Livre, Uber) acha o carro e o pagamento nos grupos: o pedido e o *carro* no COMPRAS, a foto do Pix no FINANCEIRO.',
        fala: 'As compras do BR vc vai encontrar nos grupos COMPRAS e FINANCEIRO',
        onde: 'espelho whatsapp_messages (banco US): «GZ28 Tpec - COMPRAS» e «GZ28 Tad - FINANCEIRO», só a linha canônica (duplicate_of nulo) · financeiro_inbox',
        nota: 'O e-mail da NF-e do Mercado Livre não traz o valor; o valor sai do Pix no FINANCEIRO. O recibo da Uber traz o trajeto, e é o trajeto que casa com a legenda no COMPRAS.' },
      { id: 'C.8', estado: 'À MÃO', desde: '24/09/2026',
        texto: 'Os grupos PRINCIPAIS são três: FINANCEIRO, CONTAS e COMPRAS. Os grupos dos TIMES (os chats «GZ28BR T…», um por time do STAFF) também são lidos. O histórico completo dos três principais está exportado na pasta Volante do GZ28BR — é consulta e prova, não lançamento retroativo.',
        fala: 'The FINANCEIRO, CONTAS and COMPRAS groups are the MAIN ONES! The Team Groups (search the app for them), should be read too! FINANCEIRO, CONTAS and COMPRAS exported to VOLANTE at GZ28BR folder.',
        onde: 'espelho whatsapp_messages (banco US): «GZ28 Tad - FINANCEIRO», «GZ28 Tad - CONTAS», «GZ28 Tpec - COMPRAS» e os «GZ28BR T…» · Dropbox/000 - GZ28BR/Volante/*.zip',
        nota: 'Hoje o robô (financeiro_inbox) só lê o FINANCEIRO. CONTAS e os grupos dos times ainda não têm leitor automático.' },
    ],
  },
]
