// Versão do BANK LINK — a ponte com o banco (Plaid → Regions → bank_transactions),
// produto próprio desde 21/ago/2026 (batizado pelo Márcio). Contagem própria,
// independente de FINANCIAL HUB (lib/finVersion) e DATA CHECKER (lib/dcVersion).
// Todo patch do BANK LINK bumpa BL_VERSION e acrescenta uma linha no changelog.
export const BL_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'ALPHA'
export const BL_VERSION = '0.5.4'

export const BL_CHANGELOG: { version: string; date: string; notes: string }[] = [
  { version: '0.5.4', date: '2026-08-26', notes: "REPASSE DE TARIFA DE WIRE (desenho do João na sessão): a tarifa pertence ao projeto que a causou. Quando o motor FEE for lançar uma tarifa de wire e existir UM wire no dia (±1, mesma direção: INCOMING fee ⇐ wire que entrou, OUT fee ⇐ wire que saiu) já CASADO com uma invoice, a tarifa vira DESPESA daquela invoice — custo interno: o cliente não vê linha nenhuma (\"o preço de pagar por wire\"), a margem do projeto absorve, e o DRE a conta no CPV do projeto em vez de Tarifas bancárias. Ambíguo (0 ou 2+ wires no dia) ⇒ Regions Bank (BANK), como sempre. Nota do A CONFERIR diz \"repasse → US.xxx\"; DESFAZER apaga a despesa criada (o marcador \"(auto Bank Link)\" protege linha humana). As tarifas JÁ lançadas ganham atribuição retroativa quando os wires forem casados e o motor rodar de novo? Não — ficam como estão; retrofit sob demanda." },
  { version: '0.5.3', date: '2026-08-26', notes: "Par do FIN 0.11.2: o motor FEE passa a criar o fornecedor Regions Bank com cost_type BANK — tarifa bancária é despesa operacional com linha própria, não \"custo fixo\". Nada muda no casamento em si: mesma vocabulário, mesmo teto, mesmo link bank_transaction_id." },
  {version: "0.5.2",date: "2026-08-26",notes: "Sessão de limpeza, fricção do João: INPUT ganha a CATEGORIA no selo — “INPUT · APARTMENT · HUANUO Lap Desk…” — pra dizer de onde o insumo vem (apartamento, gatos, oficina) sem abrir nada. Vale no seletor e no painel CONFERIR."},
  {version: "0.5.1",date: "2026-08-26",notes: "Fricção do Márcio na sessão de limpeza: despesa de projeto era a ÚNICA origem SEM selo no seletor de candidatos — a linha começava direto no código da invoice (US.013.3 · item · fornecedor) enquanto todas as outras se anunciam (INCOME, FIXO, GOODS, INPUT, STOCK, PART CUSTO, PEDIDO, CAPITAL, EMPRÉSTIMO) — virava jogo de adivinhação. Agora: EXPENSE · , o espelho do INCOME. Casamentos novos gravam a nota já com o selo; os antigos em A CONFERIR mantêm o rótulo da época."},
  { version: '0.5.0', date: '2026-08-25', notes: "TRIAGEM POR FAMÍLIA (João: \"a conciliação parece grande demais\" — e a medição deu razão): das 1.217 saídas NEW, ~700 são cartão do dia a dia (AMAZON ×178, COMBUSTÍVEL ×120, AUTO/FERRAMENTA ×113, MERCADO ×111, TEMU, ROUPA…) que NUNCA terão linha no app — não é casamento, é decisão. Chips de família em cima do SEM CASAMENTO: clica no chip (vira filtro), confere a lista, escreve a nota e EXPLICAR TODAS → TO BOOK (QUEUED) de uma vez, com guarda (só NEW não-pendente) e trilha. Reverter linha a linha: action unqueue. O que sobra no SEM CASAMENTO é o que interessa casar: 23 WIREs somando $851k, Zelle $60k, PayPal $137k. Ideia descartada com medição: casar recorrência com custo fixo do mês — só 3 linhas batiam, não vale um motor." },
  {version: "0.4.4",date: "2026-08-25",notes: "Plaid aprovou o produto Balance — o tempo real JÁ estava rodando (linhas 'tempo real' em cash_balances desde 24/ago, o auto-switch da v0.4.1 funcionou sozinho). Caso do João ('o banco diz $493,28'): o número dele era o DISPONÍVEL do app do banco; a nossa manchete mostrava o CURRENT ($1.638,46), que inclui o que ainda não postou. Conferido contra o feed: âncora + linhas postadas = current do Plaid no centavo, e com pendências = available no centavo — dado certo, manchete errada. Agora a manchete do CAIXA CONSOLIDADO (e o número grande de cada conexão) é o DISPONÍVEL — o mesmo número que o app do banco mostra — com o current na linha de baixo."},
  { version: '0.4.3', date: '2026-08-25', notes: 'UX da 1ª rodada (João): todo candidato do pool agora carrega a FONTE — de que tabela veio, em palavras de gente ("DESPESA da invoice US.013.3", "CUSTO do part vendido", "RECEBIMENTO · cliente"), a composição (preço×qtd+tax), as datas, e o link que abre o registro real.' },
  { version: '0.4.2', date: '2026-08-24', notes: 'Ponto cego achado pelo João e pelo Márcio na PRIMEIRA rodada de conciliação (caso JESSEES): o pool olhava as tabelas de despesa mas nunca o CUSTO dos invoice_parts — o part tem preço de venda (unit_price) e custo (base_cost), e é o custo que aparece no banco. Medido: 102 linhas NEW batem com algum base_cost. Agora: invoice_parts entra no pool pelo base_cost×qtd (rótulo PART CUSTO), kit (kit_group) vira UMA cobrança somada (KIT CUSTO) com membros, backfill/DESFAZER de payment_date incluídos. Quatro olhos humanos > 60 agentes de revisão.' },
  { version: '0.4.1', date: '2026-08-23', notes: 'Revisão adversarial: rotas /api/plaid/link-token, exchange e history-probe exigiam ZERO sessão (qualquer um podia plugar um banco) e o cron bank-sync devolvia saldo aberto — tudo trancado (sessão / CRON_SECRET, resposta enxuta). Lançamento manual de hoje não cega mais a leitura ao vivo (só segura a escrita); linha REMOVED sai do saldo implícito e das saídas; tolerância da régua conta entradas pendentes e o veredito é por conexão (gaps opostos não se cancelam); teto de consultas pagas degrada pra leitura grátis em vez de dar erro, e o slot só conta se a chamada paga aconteceu; erro do tempo real aparece na tela (e some sozinho quando o produto Balance for aprovado); erro de rede não apaga mais o saldo da tela; conexão sem resposta aparece ao lado do total em vez de sumir dele.' },
  { version: '0.4.0', date: '2026-08-22', notes: 'SALDO REAL: o CAIXA CONSOLIDADO passa a ser o que o BANCO diz agora (Plaid /accounts/balance/get — current e disponível, hora da consulta, botão atualizar; cache de 10 min porque o Plaid cobra por chamada) em vez do último saldo gravado — que era o extrato de junho, porque a gravação diária do Plaid falhava em silêncio desde a v0.2.0 (João pegou: $28k na tela, $1.638 no banco). O FEED BATE?: último extrato lançado + linhas do Bank Link desde então = saldo implícito; diferença com o real, descontado o pendente, vira BATE / NÃO BATE. Nova rota /api/plaid/balance (grava o saldo do dia, nunca sobrescreve lançamento manual); sync devolve o erro do saldo em vez de engolir. CUSTO (João): a tela e o Data Checker leem de graça (/accounts/get = saldo da última atualização do item); a consulta paga em tempo real (/accounts/balance/get, produto Balance) só 1×/dia no primeiro sync e no botão "consultar o banco agora ($)", com confirmação e teto de 3/dia; sem o produto habilitado cai na leitura grátis. ~$3/mês no piloto automático.' },
  { version: '0.3.1', date: '2026-08-22', notes: 'Revisão adversarial da v0.3.0 (34 agentes, 25 defeitos confirmados, nenhum disparava na primeira rodada): MATCH agora TRANCA a linha do banco antes de tocar o app (0 linhas = já decidida) e guarda em `backfill` exatamente o que escreveu — DESFAZER reverte só isso (antes podia zerar uma data que já existia); tarifa criada é apagada se a trava falhar; nome ignora vocabulário genérico (card/purchase/zelle/orlando/números) e em Zelle/wire exige o beneficiário; alias é palavra inteira (posto de gasolina não casa bomba de combustível); tarifa já lançada só conta com fornecedor Regions, 2+ lançadas = ambígua (fica pro humano); grupo ⇄ item se excluem dentro do plano; backfill de grupo só nos membros que formaram o total; PENDING não casa; TRANSFER/IGNORE/EXPLAIN exigem NEW; APLICAR roda o plano MOSTRADO (hash) em fatias de 150 com paralelismo 6 e 300 s; índice único (matched_table, matched_id). Migration atualizada (backfill + índice).' },
  { version: '0.3.0', date: '2026-08-22', notes: 'MOTORES AUTOMÁTICOS ("Go!" do Márcio). FEE: tarifa da Regions (wire fee, analysis charge, international assessment, ≤ $300) vira custo fixo do fornecedor "Regions Bank" (FIXED — o DRE soma) ligado à linha do banco, ou casa com tarifa já lançada. EXACT: centavos iguais + candidato único no app (±30d) + linha única no banco (±30d) + ≤3 dias + nome/alias batendo + candidato datado e não pendente; valor redondo só ≥ $1.000; série (≥3× em 45d) nunca. PLANEJAR mostra a seco (com motivos de recusa), APLICAR roda numa rodada; tudo fica em A CONFERIR com OK/DESFAZER por linha, DESFAZER LOTE por rodada e OK TODAS só pras tarifas (apaga a tarifa criada ao desfazer). Pool corrigido: paid_from/paid_to GZ28BR fora, lançamento datado no futuro fora, invoice_expenses agrupa por purchase_group, nome do cliente entra no rótulo das entradas. Enter no seletor = MATCH. Migration: MIGRATION_bank_reconcile_v030.sql.' },
  { version: '0.2.3', date: '2026-08-22', notes: 'Origem visível: linha do extrato em PDF (908, Nov/2025 → mai/2026) ganha selo STATEMENT; linha do Plaid é o normal e não ganha selo (Márcio: seria redundante). Cabeçalho da tabela diz quantas vieram do extrato. O placar "NEW: 1662" sai de baixo do CAIXA CONSOLIDADO — não era "linhas novas", era conciliação: vira RECONCILIATION junto da tabela, NEW → UNMATCHED, QUEUED → TO BOOK, com atalho → DATA CHECKER.' },
  { version: '0.2.2', date: '2026-08-22', notes: 'CAIXA TOTAL vira CAIXA CONSOLIDADO e sai do formato de card: é a manchete da página, logo abaixo do título, com número grande e régua — só os bancos conectados são cards. Legenda diz quantas conexões têm saldo, a posição mais antiga e se algum saldo ainda é de extrato (não Plaid).' },
  { version: '0.2.1', date: '2026-08-21', notes: 'Tela no ecossistema: ← FINANCIAL HUB, selo junto do título, BALANCE por conexão e CAIXA TOTAL de todas as conexões (último saldo de cash_balances — Plaid ou extrato); BANK LINK no topo do ADM e CHANGELOG no dropdown DEV. Revisão adversarial (22 agentes): MATCH re-deriva o candidato no servidor (fecha o buraco de casar a mesma linha do app em duas do banco, grupo ⇄ item incluído); UNMATCH desfaz o backfill; estorno negativo vai pro pool oposto; leitura pagina além de 1.000; rota /api/plaid/accounts passa a exigir sessão (estava aberta — expunha o extrato e disparava sync cobrado); saldo do dia conta só depósito (cartão subtrai) e nunca sobrescreve lançamento manual.' },
  { version: '0.2.0', date: '2026-08-21', notes: 'Histórico completo: 908 linhas de Nov/2025 a 25/mai/2026 importadas dos extratos PDF da Regions (checksum por extrato + 220/220 conferidas contra o Plaid em junho), ids stmt:. Saldo do dia via Plaid → cash_balances (uma chamada/dia, source PLAID) — o Caixa do Balanço vive sozinho. API /api/bank/reconcile: candidatos no app por valor/data/grupo de compra e ações MATCH/TRANSFER/IGNORE/EXPLAIN com backfill de payment_date. SHOW ALL pagina além de 1.000.' },
  { version: '0.1.2', date: '2026-08-21', notes: 'FULL HISTORY removido: a Regions só serve 90 dias online (conferido no app do banco) e o Plaid não estende item existente — o passado entra por extrato. Token segue pedindo 730 dias pra conexões novas. Sonda de histórico fica como diagnóstico.' },
  { version: '0.1.1', date: '2026-08-21', notes: 'Histórico: link token pede 730 dias (máximo do Plaid; o original pedia 90, por isso a Regions começa em 26/mai). Botão FULL HISTORY em update mode — a sonda (/api/plaid/history-probe) provou que o Plaid NÃO estende conexão existente; o caminho é religar do zero. Lista da tela de 60 → 300 com SHOW ALL (parava em 17/ago).' },
  { version: '0.1.0', date: '2026-08-21', notes: 'Nasce o BANK LINK: Regions via Plaid (OAuth no nome da LLC), access token trancado por RLS, sync por cursor (/transactions/sync) idempotente, webhook do Plaid + cron 6/6h como rede de segurança, tela ADM → BANK com conexões, placar e transações. 754 linhas desde 26/mai/2026, todas NEW — o universo contra o qual o app vai se conferir.' },
]
