// Versão do CREW CHIEF — o cérebro de produção (blueprints → packs → duties →
// capacidade), nascido 26/ago/2026 sobre o passo do Márcio (packs carregam
// STAFF DUTIES, commit 06aa989). Contagem própria, como FIN/DC/BL/WA.
// Todo patch do CREW CHIEF bumpa CC_VERSION e acrescenta uma linha aqui.
export const CC_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'ALPHA'
export const CC_VERSION = '0.2.3'

export const CC_CHANGELOG: { version: string; date: string; notes: string }[] = [
  { version: '0.2.3', date: '2026-08-26', notes: 'Taxonomia final do João: PACK · ADD-ON · SERVICE (BLOCK renomeado — o terceiro tipo é serviço avulso/manutenção: troca de óleo, revisão; o carro da casa que volta só pra isso escolhe o SERVICE direto). E o ADD-ON fecha o ciclo de venda: a quote nova mostra o dropdown de packs como sempre (PACKs + SERVICEs) E uma lista de OPTIONAL ADD-ONS com checkbox — marca zero ou mais, cada um aplicado POR CIMA via o mesmo applyPack do Márcio (as duties do add-on entram com a própria numeração NN, mais uma frente de trabalho, padrão que já existia nas invoices reais). Migration atualizada (BLOCK→SERVICE, auto-corretiva); catálogo com seções PACKS / ADD-ONS — OPTIONALS / SERVICES & MAINTENANCE.' },
  { version: '0.2.2', date: '2026-08-26', notes: 'IMPORT A BLOCK removido (João: "seems unnecessary" — e tinha razão: foi inferência minha, não pedido; pro fluxo real de construção o DUPLICATE já cobre "começar de algo", e cópia é a versão fraca da composição). O conceito de BLOCK fica (KIND continua com PACK/ADDON/BLOCK, seção própria no catálogo); a composição de verdade — referência VIVA, bloco atualiza e os packs sabem, horas do bloco acumulando através dos packs que o usam — é o desenho certo e fica pro CC 0.3+, se a falta aparecer.' },
  { version: '0.2.1', date: '2026-08-26', notes: 'ADD-ONs (João): "não é um pack — é um serviço OPCIONAL de venda", tipo Demonized PLUS Lowering Springs. Nasce o KIND (PACK · ADDON · BLOCK) — mesma anatomia e mesma máquina (editor, duties, estimativas, IMPORT A BLOCK, aplicação em invoice), mas espécies separadas em tudo que se vê: o catálogo ganha seções próprias (PACKS / ADD-ONS & OPTIONAL SERVICES / BLOCKS — BUILDING UNITS) e selos ADD-ON (roxo) e BLOCK (teal) na FULL LIST. Requer MIGRATION_pack_kind.sql (coluna aditiva com default PACK, segura pro BR); o editor detecta a coluna e só envia kind quando ela existe — sem migration, nada quebra.' },
  { version: '0.2.0', date: '2026-08-26', notes: 'BLOCKS v0 (João, em plena reconstrução do Packs DB: "where should I build the blocks?"): um BLOCO é um pack pequeno — Engine Build, Crank Pinning, Troca de Óleo HEMI — criado normal no Packs DB, com platform, duties e estimativas. O editor ganhou 🧱 IMPORT A BLOCK: escolhe outro pack e o conteúdo dele FUNDE no formulário atual — parts/expenses com kit_groups novos (importar 2× = 2 kits), services, e as duties renumeradas em sequência DEPOIS das existentes. Nada grava no banco até o SAVE (arrependeu, sai sem salvar). Compor pack grande = criar os blocos primeiro e importá-los em ordem. É a materialização v0 do design de blocos da visão (v1.5: bloco = unidade de reuso e aprendizado); a formalização com referência viva (bloco atualiza → packs sabem) fica pro CC 0.3+.' },
  { version: '0.1.9', date: '2026-08-26', notes: 'Título do cartão BY PACK volta a mostrar o nome INTEIRO (o João notou o Z1000 escondido no CatAholic): os Z-codes reais das variantes entram no título. Z-codes divergentes na mesma família eram BAGUNÇA, não intenção — João, 26/ago: os packs foram todos deletados e o Packs DB está sendo recriado do zero, limpo; no dado novo cada família tem um Z-code só. Nota de vergonha honesta: a primeira versão desta linha do changelog tinha um apóstrofo mal escapado que QUEBROU o build em produção por alguns minutos (e o commit passou porque o comando não travava no erro do typecheck — os dois erros meus, os dois corrigidos).' },
  { version: '0.1.8', date: '2026-08-26', notes: 'Vocabulário de plataforma corrigido pelo João: GEN V SM (GM Gen V Small Block) é a plataforma — LT1/LT4 são códigos de motor DENTRO dela, puxados pelo carro. Datalist do editor e o platformOf do minerador atualizados (tokens LT1/LT4 em nomes mapeiam pra GEN V SM). Lista oficial completa de plataformas pendente do João — quando ditar, vira lei hard-coded.' },
  { version: '0.1.7', date: '2026-08-26', notes: 'Selo de PLATFORM sobe pro cartão do PACK (João: "CatAholic IS for the HELLCAT platform" — platform é métrica do pack, não da variante). Chave de agrupamento do BY PACK agora é NOME+PLATAFORMA: Poltergeist LT4 e LT1 viram dois cartões (dois blueprints, como manda a visão); as linhas de dentro variam por CARRO (Durango vs TRX) e perdem o selo individual. SEM PLATFORM em vermelho no cartão enquanto o refresh não preenche.' },
  { version: '0.1.6', date: '2026-08-26', notes: 'PACKS DB abre em BY PACK (João): um cartão por PRODUTO — família extraída do nome (cai o Z-code, o parêntese e o " - variante") — com as variantes dentro (selo de plataforma ou SEM PLATFORM em vermelho, status, total, carros que ela serve, VIEW·EDIT·REMOVE·DUPLICATE). A lista completa com nomes repetidos virou FULL LIST, só quando clicada de propósito. Hierarquia confirmada na conversa: FAMÍLIA (produto) → PLATFORM (variante de motor, eixo de mineração) → CARS (encaixe de chassi; headers diferentes C7 vs Camaro = bloco de carro no P2, não redundância da platform).' },
  { version: '0.1.5', date: '2026-08-26', notes: 'Visão POR PLATAFORMA no PACKS DB (ideia do João): chips de plataforma derivados ao vivo dos próprios packs, com contagem — clica e vê só os packs daquela plataforma; selo de plataforma no cartão distingue na hora os xarás (Demonized Durango vs TRX). O balde SEM PLATFORM é a dívida do refresh ficando visível: esvazia conforme Márcio+João preenchem o campo novo do editor. Sinergia de propósito com o CC 0.1.3.' },
  { version: '0.1.4', date: '2026-08-26', notes: 'BLUEPRINTS na LEI DE LAYOUT da casa — o 0.1.2 acertou as cores mas não o esqueleto: a tela era uma coluna estreita centralizada com controles miúdos (João: "layout is off"). Agora: main p-8 largura total, título text-4xl com selo, parágrafo-intro, faixa de chips de totais (famílias/candidatos/packs sem duties/duties no corpus, padrão TARIFAS), cartões rounded-3xl p-6, botões px-5 py-3 rounded-2xl font-bold, inputs no padrão exato do editor de packs. Zero mudança de lógica.' },
  { version: '0.1.3', date: '2026-08-26', notes: 'Campo PLATFORM no editor de packs — a coluna packs.platform existia desde a migration de parts identity mas NENHUMA UI escrevia nela (sonda: 38 packs US, 38 sem platform). O refresh combinado do Márcio+João precisa preenchê-la (é o índice de famílias/variantes do CREW CHIEF: mesmo pack, base ± blocos — Poltergeist LT4 vs LT1). Input texto-livre com sugestões (D170, TRX, HELLCAT, REDEYE, DURANGO, LT4, LT1), salvo em UPPERCASE. Toque mínimo no editor do Márcio, autorizado pelo João (26/ago, resposta 1). BÔNUS: re-pousa o 0.1.2 — o commit 568f934 (worktree defasado do Dropbox no PC do Márcio) tinha revertido sem querer o re-skin dark da tela BLUEPRINTS e este changelog.' },
  { version: '0.1.2', date: '2026-08-26', notes: 'BLUEPRINTS entra no uniforme da casa: a tela nasceu em tema claro (fundo branco — João estranhou na hora, com razão) e o app inteiro é preto com cartões gray-900. Re-skin completo: fundo bg-black, cartões bg-gray-900/rounded-2xl, inputs gray-800, chips e textos nas variantes dark. Zero mudança de comportamento.' },
  { version: '0.1.1', date: '2026-08-26', notes: 'Conserto do primeiro clique do João: invoices não tem coluna status (é live_status) — o select pedia uma coluna fantasma e a tela morria no carregamento. Todos os outros cinco selects auditados contra as colunas reais do banco (sonda read-only) e batem. De quebra, a sonda confirmou que invoices.service EXISTE — a fonte de família que o plano original citava — e agora entra no palheiro do matching de famílias junto com serviços e parts.' },
  { version: '0.1.0', date: '2026-08-26', notes: 'NASCE O CREW CHIEF — P1: o minerador de blueprints com curadoria. A mineração é computada ao vivo (nada é gravado): famílias por pack, blocos de KIT recorrentes (kit_name × invoices), espinhas de duties por exemplar (o prefixo "NN." reinicia por frente de trabalho — nunca ordenar o invoice inteiro por ele), vocabulário normalizado (171 descrições, 34 recorrentes) e dicas de tempo por descrição — regra do João: o suspeito é o STINT (>10h contínuas = timer esquecido, mesma régua do DUTY WATCH), nunca o total da duty; com corpus crescendo, o desvio vira relativo à mediana. ADOTAR cria o candidato (tabela nova blueprint_candidates, US-only, com proveniência completa); o humano cura (texto canônico com as variantes absorvidas, ordem via "NN.", prioridade, estimativa pré-carregada da mediana); PROMOVER vira um PACK de verdade (DRAFT · zone US, na forma exata do editor do Márcio — intocado) ou ENRIQUECE um pack existente sem duties (os 11 da família Demon-170 nasceram vazios). Sequência combinada: Márcio+João atualizam os 38 packs primeiro; a mineração roda no dado limpo. MODO GUIADO da curadoria e os fiscais do Data Checker ficam pro CC 0.2.0 — um passo de cada vez (João).' },
]
