// Versão do DATA CHECK — produto próprio desde 20/ago/2026, quando saiu do
// FINANCIAL e virou ferramenta de organização do app inteiro (ADM → DATA
// CHECK). Contagem NOVA, independente do lib/finVersion: todo patch do DATA
// CHECK bumpa DC_VERSION e acrescenta uma linha no topo do changelog.
// A era anterior (dentro do FINANCIAL v0.4.0–v0.9.x) está no changelog de lá.
export const DC_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'BETA'
export const DC_VERSION = '1.34.1'

export const DC_CHANGELOG: { version: string; date: string; notes: string }[] = [
  { version: '1.34.1', date: '2026-08-25', notes: "Card da frota ganha a quinta classe: COLECIONÁVEL — chassi ao custo (a valorização fica fora dos livros até a venda), experimentos depreciam. Nascida do caso Devil170 (Demon 170, produção única)." },
  { version: '1.34.0', date: '2026-08-25', notes: "Pilar DATA CHECK no G4 recém-nascido: card novo \"Carro da frota sem natureza de ativo\" — todo OWN/TOOL novo cai nele até ganhar classe (TRABALHO/DESENVOLVIMENTO depreciam; MONUMENTO/RESERVA ao custo), com o conserto na própria linha. Só aparece depois da MIGRATION_g4_fleet.sql (sem falso alarme antes)." },
  { version: '1.33.0', date: '2026-08-25', notes: "Fase 4, o carro-chefe da reforma: MODO GUIADO. Todo card com 2+ itens ganha \"▶ um de cada vez\": a fila vira UM item grande — código, valor, data, contexto, ABRIR REGISTRO ↗ (e ANÚNCIO ↗ quando há) — com o conserto na cara: a sugestão vem PRÉ-CARREGADA (um Enter resolve), data prevista idem, e VOLTAR/PULAR navegam. Barra de progresso + \"N resolvido(s) agora\"; fila zerada vira comemoração. Os filtros do card valem no guiado (filtre pre-open e guie só por eles). Tudo passa pelo applyFix de sempre — trilhas, APIs e guardas do dia inteiro, nada novo pra errar. A sessão de limpeza vira jogo, não planilha." },
  { version: '1.32.0', date: '2026-08-25', notes: "Fase 3 da reforma de UX: COMECE AQUI — a tela agora diz a ORDEM de ataque em vez de despejar 8 grupos de uma vez. Três missões calculadas (não adivinhadas): a régua primeiro (caixa não bate = nada mais vale), os casamentos do motor aguardando OK, as respostas prontas de um clique (PREENCHER CERTOS, começando pelo card com mais provas), e — quando couber — a triagem por família ou o maior valor parado. Clicou na missão, a tela filtra e abre o card certo. Placar-lite junto do contador: \"N conserto(s) hoje\" (da trilha data_fixes). Falta da proposta original: o MODO GUIADO (um item por vez) — a próxima fase." },
  { version: '1.31.0', date: '2026-08-25', notes: "Fricção final da rodada do João: o card do TAX \"confunde — não sei o que é, o que faz, nem por que existe; parece só uma lista\". Ele quebrava as duas regras do dia: não se explicava e as linhas não agiam. Agora o porquê conta a LEI do zero (pagou pessoa $600+/ano por SERVIÇO → 1099-NEC até 31/jan + W-9; multa se não; mercadoria/corporação/pessoal = nada) e a linha trabalha: classificar (5 opções em palavras de gente) e marcar o W-9 acontecem ali mesmo, pela API do TAX SHIELD, com o cuidado de carregar os valores atuais no upsert (classificar não zera mais o W-9). O UNIR (juntar grafias) continua na tela cheia." },
  { version: '1.30.0', date: '2026-08-25', notes: "João desconfiou do tamanho do \"Quem pagou esta conta?\" (937!) e a auditoria deu razão: 310 linhas NÃO PAGAS (quem pagou? ninguém ainda — só linha paga entra agora) e 104 com o SOURCE legado preenchido — o campo que ERA o quem-pagou antes do paid_from existir. Valor limpo do SOURCE (GZ28US/GZ28BR/RAFA/BETO; \"Regions\" = conta GZ28US) agora é CERTO por linha e entra no PREENCHER CERTOS (que passou a aplicar o valor DE CADA linha, não um só); banco × SOURCE discordando vira CONFLITO pro humano. A fila honesta caiu de 937 pra ~523 — grande, mas verdadeira: é o legado que o Márcio sabia que existia." },
  { version: '1.29.0', date: '2026-08-25', notes: "João: \"Esta peça é qual peça do catálogo?\" tinha a mesma doença do fornecedor — só os candidatos achados, e sem candidato virava beco (\"quase inútil\"). Mesma receita: além dos candidatos (✓ certo, ≈ palpite), 🔎 BUSCAR NO CATÁLOGO INTEIRO abre o PartPicker no próprio painel (2+ letras, acha por PN/nome/apelido, 🔒 nas travadas) e ➕ CRIAR faz a entrada MÍNIMA (nasce MANUAL, sem PN de propósito) já linkada — as filas de higiene perseguem até completar. Bônus: o 🔒 do PartPicker tinha morrido na migration untangle (testava LOCKED, que virou locked_at) — ressuscitado." },
  { version: '1.28.0', date: '2026-08-25', notes: "Par do FIN 0.9.7 (encerramento formal): card novo \"Assinatura encerrada com conta ainda agendada\" — conta não paga agendada DEPOIS do date_conclusion é despesa fantasma de serviço morto; o conserto é o novo APAGAR (primeiro fix destrutivo do Data Checker: painel de confirmação + trilha com o que era). A vencida de assinatura encerrada ganha o aviso \"pague ou apague (write-off)\" e sai do card de vencidas quando é posterior ao encerramento. DATA CHECK como pilar: o rito novo nasceu já com o seu fiscal." },
  {version: "1.27.0",date: "2026-08-25",notes: "Custo fixo & folha ganham o mesmo modelo (conferido pelo João no caso das 7 Warehouse Lease idênticas): conta futura agendada é Future Flow, não pendência — fora do card. Entram só a VENCIDA, agora dizendo prevista + há quantos dias, e a SEM DATA NENHUMA (3 Food da folha nem o mês têm). Medido: 77 fixas viravam 9 de verdade; as 7 Warehouse Lease eram 1 vencida + 6 meses futuros que ninguém distinguia porque a linha não mostrava a data. Regra da casa nova: TODA linha se distingue da irmã (a prevista/comprado entra no rótulo). Compra de estoque: João conferiu, o card estava CERTO (1 linha sem data nenhuma) — só ganhou a regra da distinção."},
  {version: "1.26.0",date: "2026-08-25",notes: "O João pegou o Data Checker entendendo errado o modelo do Márcio (caso US.047.1): no invoice builder, payment_date vazio É o estado Not paid yet — normal, vive em Fornecedores a pagar — e o card Despesa de projeto: pagamos quando? listava TODAS: medido, 299 das 334 eram falso positivo. O card virou detector de VENCIDA: só entra a linha cuja data prevista (parcela agendada ou espelho legado expense_date) já passou sem pagamento lançado — hoje, zero (as 4 parcelas do Demon 170 #283 entram sozinhas se vencerem sem baixa). Se pagou, registra a data; se atrasou, é cobrança, não conserto. Suspeita anotada: custos fixos, folha e estoque podem ter o mesmo vício de modelo — um de cada vez."},
  {version: "1.25.1",date: "2026-08-25",notes: "Detalhe achado pelo João: a legenda ao lado de PREENCHER CERTOS dizia “linhas já casadas com a Regions” em TODOS os cards — resíduo de quando só o “Quem pagou esta conta?” tinha bulk de certos. Agora cada card declara a SUA prova: PN no próprio texto (identidade), nome/apelido/identidade dura (fornecedor), casamento com a Regions (quem pagou)."},
  { version: '1.25.0', date: '2026-08-25', notes: "PN DE ANÚNCIO (observação da rodada do eBay, aprovada pelo João): em linha eBay, um \"PN\" de 9–13 dígitos é o número do anúncio, não a peça — o caso \"366091257445\" com o PN real (12673134) escondido no texto do item. Novo item no card de identidade: selo PN ANÚNCIO, palpite do PN real puxado do texto (8 dígitos GM primeiro), ANÚNCIO ↗ pra conferir na página, e o conserto grava part_number com trilha (o nº do anúncio fica como old_value). Identidade é cirurgia: sempre um a um, sem bulk; se o novo PN colidir com outra linha, o check de PN duplicado pega na rodada seguinte." },
  { version: '1.24.0', date: '2026-08-25', notes: "Refinamento do João na gramática do eBay: linha \"eBay\" SEM vendedor à vista não pode mais cair no genérico — \"eBay\" seco casava CERTO com o fornecedor Ebay e jogava a informação fora. Agora NENHUMA linha eBay sugere o genérico (quem precisar dele acha na lista completa, à mão). E o card abre o caminho pro vendedor real: o número do anúncio (que ficou gravado como \"PN\", 9–13 dígitos) vira o botão ANÚNCIO ↗ — ebay.com/itm/<número> mostra o vendedor na página; sem anúncio, a linha manda pro histórico de compras do eBay. Selo EBAY? marca as sem-vendedor. Achou o nome → ➕ criar (via eBay, apelidos ensinados) fecha o ciclo sem sair da tela." },
  { version: '1.23.0', date: '2026-08-25', notes: "A GRAMÁTICA DO EBAY (João achou o padrão): compra no eBay traz o handle do vendedor — minúsculas, sem espaço (\"atozwholesaleautoparts\" = Atoz Wholesale Auto Parts). Decisão de arquitetura: fornecedor = vendedor REAL; eBay = canal (ordering_method, coluna que já existia — zero migration). O card agora detecta o handle (inclusive \"eBay - handle\" e \"handle (eBay)\"), procura por ele com a identidade dura (handle e nome bonito são iguais sem espaços), SUPRIME o genérico Ebay quando o vendedor real está no texto, marca a linha com selo EBAY, e o criar-novo já vem com o handle no prompt, grava via eBay e ensina handle + grafia como apelidos. Medido: 91 linhas com eBay no texto, 10 só-handle, 0 linkadas ao genérico — retrofit desnecessário, a decisão saiu de graça." },
  { version: '1.22.0', date: '2026-08-25', notes: "Fricção #4 do João: linha sem candidato mandava \"cadastre em SUPPLIERS\" — trabalho em outra tela. Agora resolve AQUI: o dropdown traz os candidatos (✓ certo, ≈ palpite), depois a lista oficial INTEIRA, e por fim \"➕ criar fornecedor novo\" — o prompt já vem com a grafia da linha, cria (ou REUSA por identidade dura, sem duplicata) e liga a peça na hora. Bônus que fecha o ciclo: toda escolha manual ensina a grafia como APELIDO do fornecedor — o \"sem candidato\" de hoje é o CERTO de amanhã. Tudo na trilha (supplier_id, aliases)." },
  { version: '1.21.0', date: '2026-08-25', notes: "Fricção #3 do João: em 'Peça sem fornecedor oficial', 'O&J PERFORMANCE INC' não achava 'OJ Performance' — o casador exigia igualdade exata e tropeçava em &, pontuação e sufixo legal. Novo nível de identidade DURA: só letras/números e sem INC/LLC/CORP no fim; igualdade dura = mesma empresa = CERTO. Medido no catálogo real antes de publicar: 314 → 380 linhas CERTAS (+66), incluindo as 18 do O&J, 34 da High Horse 'Inc.' e 12 da Titan 'Inc.' — um clique em PREENCHER CERTOS resolve tudo." },
  { version: '1.20.0', date: '2026-08-25', notes: 'Reforma de UX, iteração 2 (plano aprovado pelo João: uma fricção por vez). PALAVRAS DE GENTE: todo card vira a pergunta que o humano reconhece — "Quem pagou esta conta?", "Esta peça é qual peça do catálogo?", "O caixa do app bate com o banco?" — e os codinomes internos (G1, D9, R1, LINKER) saem da tela. "trava:" vira "se ignorar:" com a consequência em palavras simples. UMA LINHA, NÃO UM PARÁGRAFO: o porquê completo de cada checagem sai da frente do trabalho e fica atrás de "entender esta checagem ▾".' },
  { version: '1.19.0', date: '2026-08-25', notes: 'Começa a reforma de UX (fricções da 1ª rodada real do João+Márcio). Fricção #1: "a linha é só dados, não dá pra conferir de onde vem". Cada linha da conciliação ganha o expansor ▸ CONFERIR: lado a lado, o que o BANCO diz (nome cru, data, saiu/entrou, extrato ou Plaid, pendente) e o que o APP tem (fonte em palavras de gente, composição, datas, e ABRIR REGISTRO ↗ que abre a invoice/estoque/insumo de verdade em aba nova). No A CONFERIR (casamentos do motor), cada linha ganha ABRIR ↗ direto pro registro casado. Conferir deixa de ser obstáculo e vira um clique.' },
  { version: '1.18.0', date: '2026-08-24', notes: '"Fill and untangle" (João+Márcio): card CATEGORIA — vocabulário fechado de 13 (lib/partsMeta), 650 peças vazias ganham palpite por palavra-chave e FIX um a um (palpite não é prova: sem bulk). E o UNTANGLE do source_type: cadeado passa a morar em locked_at (isLockedPart tolera o legado até a migration), kit em is_kit, source_type volta a ser só ORIGEM com constraint — MIGRATION_parts_untangle.sql migra LOCKED→locked_at (autor legacy), KIT→is_kit, nulos→MANUAL e normaliza as categorias já preenchidas. TRAVAR/DESTRAVAR não mexe mais na origem.' },
  { version: '1.17.0', date: '2026-08-24', notes: 'Catálogo R1 (perfil de 687 peças): card novo em INVENTORY — fornecedor com identidade (188 grafias → 40 oficiais; nome/apelido exato = certo com bulk, resto FIX um a um; destrava o lead time por fornecedor do Crew Chief), MAP < custo (32 peças ferindo a lei do preço, com o tamanho da ferida), source_type vazio (23) e KIT × is_kit em desacordo. Migration: MIGRATION_parts_refinement_r1.sql (parts_database.supplier_id → suppliers). Fase 2 com o Márcio: separar origem/estado/forma do source_type e vocabulário de categorias.' },
  { version: '1.16.0', date: '2026-08-24', notes: 'Pré-P1 do Crew Chief: card LINKER (grupo INVENTORY) — estoque e stream sem part_id ganham candidatos do catálogo (PN da peça no próprio texto = CERTO, com bulk; nome/apelido = sugestão com FIX um a um; medido antes: inventory achava a peça em 5/47, stream em 21/178). Higiene do catálogo no mesmo card: 142 peças sem part number e PNs duplicados (regra uma-linha-por-PN). Migration: MIGRATION_parts_identity.sql (part_id em inventory/part_streams/invoice_expenses, cadeado locked_at/locked_by na própria peça, platform nos packs).' },
  { version: '1.15.0', date: '2026-08-23', notes: 'Caso Jeferson (69h): o STAFF DUTY WATCH agora olha o HISTÓRICO — segmento FECHADO acima de 10h vira pendência com FIX APARAR (você diz o fim real, o app desconta só o excesso que o segmento bancou, grava trilha duty-trim e um evento TRIMMED); e a COMPENSAÇÃO SILENCIOSA (2+ dias sem nenhum timer logo depois do estouro) é acusada — compensar transforma um registro errado em vários: o total fecha, mas o custo por carro e por dia mente. A varredura já pegou 3: Marcelo 78h, Jeferson 69h, Guilherme 22,8h. Regra da casa: nunca compensa — avisa, que o sistema conserta o registro.' },
  { version: '1.14.0', date: '2026-08-23', notes: 'Estreia a categoria STAFF com o STAFF DUTY WATCH (ideia do Márcio — STAFF no nome porque DUTY WATCH já é o vigia do imposto de importação): duty rodando além de 10h, duas duties da mesma pessoa ao mesmo tempo, ou timer que virou a noite ligado. Cron de 30 em 30min avisa a PRÓPRIA pessoa no WhatsApp (DM pelo staff.phone; sem telefone vai pro grupo GZ28US - STAFF), um aviso por duty por dia, janela 07–22h de Orlando, e escala pro grupo se seguir rodando 60min depois — trilha completa em data_fixes (duty-nudge). O card mostra o retrato de agora e o status do aviso; o conserto é na tela DUTIES. v2 na fila: responder PAUSAR no WhatsApp pausa de verdade (webhook já existe).' },
  { version: '1.13.0', date: '2026-08-23', notes: 'Estreia a categoria TAX com o card "1099-NEC": beneficiário pago por Zelle/wire/cheque com $600+ num ano sem classificação, ou classificado SERVIÇO sem W-9 em arquivo — com o prazo (31/jan) e o valor. A classificação acontece no TAX SHIELD novo (ADM → TAX SHIELD, ALPHA v0.1.0); o card cobra. Sinal indisponível não é verde, migration pendente aparece como item.' },
  { version: '1.12.0', date: '2026-08-23', notes: 'CATEGORIAS (nomes em inglês, padrão do app — João): BANK · FINANCIAL · RIDES · INVOICES · INVENTORY · STAFF · TAX · SYSTEM. Chips no topo com contagem viva (✓ = categoria limpa) filtram a tela; cada categoria vira uma seção com seus cards — a conciliação mora em BANK. STAFF, TAX e SYSTEM já estão na ordem esperando seus cards (duty timer com aviso no WhatsApp, 1099-NEC, FL sales tax): toda feature nova chega com as suas checagens.' },
  { version: '1.11.1', date: '2026-08-23', notes: 'Revisão adversarial (29 agentes, 24 defeitos confirmados) sobre o PAID FROM e a régua: item de pedido CASADO com a Regions agora é certo (96 linhas estavam sugerindo GZ28BR com prova de GZ28US!); pedido somado é procurado no extrato pelo TOTAL; SOURCE contradizendo o sinal vira CONFLITO (o ternário antigo dava GZ28BR dos dois lados); antes da conta abrir fica SEM palpite (GZ28BR ou BETO — decisão de gente); filtro de sinal vira dropdown exato ("consta" não pega mais "não consta") e o texto busca também a data; só par sólido (humano ou motor conferido) conta como prova, e DESFAZER um casamento apaga o paid_from que ele justificou; régua tolera entradas pendentes e acusa quando o sinal do banco nem carregou; âncora de extrato com 45+ dias pede o extrato do mês; FIX da milhagem aceitava só 1 dígito (regex sem barras).' },
  { version: '1.11.0', date: '2026-08-22', notes: 'Card "Caixa não bate (banco real × linhas do Bank Link)": o saldo que o Plaid traz do banco agora contra o saldo implícito (último extrato lançado + linhas desde então); diferença além do pendente vira pendência com o tamanho do buraco e a direção (faltam entradas ou saídas). É a régua de tudo — ideia do João (22/ago): se o caixa não bate, nenhum outro número vale. Também acusa Plaid sem resposta e conta sem âncora de extrato.' },
  { version: '1.10.0', date: '2026-08-22', notes: 'PAID FROM com o sinal da Regions: além de "casada" (certo), cada linha diz se é de antes da conta abrir (10/nov/2025 — não foi GZ28US), se "não consta na Regions" (valor igual em ±10d não existe — provavelmente BR ou Beto) ou se "consta" (provavelmente GZ28US); a sugestão pré-carregada segue o sinal. Filtro por mês/invoice/fornecedor/sinal e MARCAR OS N FILTRADOS como GZ28US/GZ28BR/BETO/RAFA de uma vez (só linhas vazias, tudo na trilha). Pensado pra sessão a dois (João + Márcio): decide-se um mês ou um invoice, varre-se de um golpe.' },
  { version: '1.9.0', date: '2026-08-22', notes: 'Card "Lançamentos sem PAID FROM (quem pagou?)": despesas de projeto, custos fixos, folha, goods, inputs e estoque sem paid_from, com FIX por linha (GZ28US/GZ28BR/RAFA/BETO). Linha já casada com a Regions (Bank Link) é GZ28US na certa — botão PREENCHER CERTOS resolve todas de uma vez com trilha; as demais trazem o SOURCE como sugestão pré-carregada. Motivo: paid_from vazio é ruído no pool do motor de conciliação e cega o DFC por caixa.' },
  { version: '1.8.1', date: '2026-08-22', notes: 'Card do banco pós-revisão: nada fica clicável durante um lote (busy é conjunto), plano some quando os dados mudam e APLICAR só roda o plano mostrado, falha no APLICAR recarrega (o servidor pode ter aplicado parte), progresso por fatia, PENDING não deixa casar, chip "data preenchida" em A CONFERIR, contagem do cabeçalho vem do estado.' },
  { version: '1.8.0', date: '2026-08-22', notes: 'Card do banco ganha os motores do Bank Link v0.3.0: bloco MOTORES AUTOMÁTICOS (PLANEJAR → APLICAR), seção A CONFERIR com OK/DESFAZER por linha, DESFAZER LOTE e OK TODAS AS TARIFAS, filtro por motor, chip TARIFA nas linhas que o motor cuida (escondidas por padrão), Enter casa no seletor e no EXPLAIN. Histórico registra cada casamento automático como bank-auto.' },
  { version: '1.7.1', date: '2026-08-21', notes: 'Card do banco: recarrega depois de cada MATCH (candidatos são do servidor), erro de rede/401 aparece no cabeçalho com "tentar de novo" em vez de "carregando" eterno, falha de resposta avisa antes de repetir.' },
  { version: '1.7.0', date: '2026-08-21', notes: 'Card "Banco sem casamento": cada linha da Regions sem par no app, com candidatos automáticos (mesmo valor, data próxima, pedido somado) e decisão na própria linha — MATCH preenche a data de pagamento do app que faltava, TRANSFER/IGNORE tiram da fila, EXPLAIN guarda o que foi. Filtro por nome/valor/data, tudo na trilha.' },
  { version: '1.6.1', date: '2026-08-21', notes: 'Relógio = Orlando: "hoje" dos recebimentos vencidos e do corte de saldo envelhecido deixa o UTC (que vira amanhã depois das 20h) e segue a regra do app.' },
  { version: '1.6.0', date: '2026-08-20', notes: 'Contexto nas linhas: toda pendência de invoice identifica carro · cliente e diz O QUE a linha é — «006.8 Pending balance» virou «006.8 · [cliente] — income Pending balance, vencido em X». Tooltip com o contexto completo.' },
  { version: '1.5.0', date: '2026-08-20', notes: 'Ciclo de entrega: delivery_date e EXPORTED se validam — entrega no passado (invoice fechada) sem selo EXPORTED pede confirmação de um clique (FIX tipo flag, novo); EXPORTED sem delivery date pede o quando. Delivery em invoice aberta é promessa (PROMISED TO) e não conta como saída.' },
  { version: '1.4.0', date: '2026-08-20', notes: 'Insight do Márcio encerra o backfill de conclusion date: CLOSED já exige incomes datados e recebidos, então o mês do resultado DERIVA do último recebimento. O card vira raridade (fechada sem NENHUMA data derivável); conclusion_date explícita continua valendo mais e a trava do fechamento continua capturando ela de graça.' },
  { version: '1.3.0', date: '2026-08-20', notes: 'Sugestão inteligente no conserto de CONCLUSION DATE: o FIX abre pré-carregado com a última atividade do invoice (pagamento recebido ou despesa) — confirma ou ajusta, em vez de reconstruir de memória.' },
  { version: '1.2.0', date: '2026-08-20', notes: 'Conclusion date com semântica certa: só invoice FECHADA sem data é pendência — job em andamento não tem data mesmo, ela nasce no fechamento. E o fechamento agora trava sem a data (oferece hoje com um clique), então o card só encolhe.' },
  { version: '1.1.0', date: '2026-08-20', notes: 'FIX aprende números: card novo "Export sem ADMISSION MILEAGE" lança a milhagem inline (os 24 carros de export sem sair da tela); DESTINY REVIEW fica só com contradições (≥ 100 mi).' },
  { version: '1.0.0', date: '2026-08-20', notes: 'DATA CHECK vira produto próprio, promovido a BETA: bancada de conserto com FIX inline (datas, destinos, tipos, baixas), trilha data_fixes agrupada por sessão, DESTINY REVIEW com a lei do 0km (ADMISSION MILEAGE < 100 mi pros dois tipos de export) e ciclo EXPORTED. Missão: manter os dados do app inteiro completos e corretos — sobre tudo.' },
]
