// Versão do DATA CHECK — produto próprio desde 20/ago/2026, quando saiu do
// FINANCIAL e virou ferramenta de organização do app inteiro (ADM → DATA
// CHECK). Contagem NOVA, independente do lib/finVersion: todo patch do DATA
// CHECK bumpa DC_VERSION e acrescenta uma linha no topo do changelog.
// A era anterior (dentro do FINANCIAL v0.4.0–v0.9.x) está no changelog de lá.
export const DC_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'BETA'
export const DC_VERSION = '1.14.0'

export const DC_CHANGELOG: { version: string; date: string; notes: string }[] = [
  { version: '1.14.0', date: '2026-08-23', notes: 'Estreia a categoria STAFF com o STAFF DUTY WATCH (ideia do Márcio — STAFF no nome porque DUTY WATCH já é o vigia do imposto de importação): duty rodando além de 10h, duas duties da mesma pessoa ao mesmo tempo, ou timer que virou a noite ligado. Cron de 30 em 30min avisa a PRÓPRIA pessoa no WhatsApp (DM pelo staff.phone; sem telefone vai pro grupo GZ28US - STAFF), um aviso por duty por dia, janela 07–22h de Orlando, e escala pro grupo se seguir rodando 60min depois — trilha completa em data_fixes (duty-nudge). O card mostra o retrato de agora e o status do aviso; o conserto é na tela DUTIES. v2 na fila: responder PAUSAR no WhatsApp pausa de verdade (webhook já existe).' },
  { version: '1.13.0', date: '2026-08-23', notes: 'Estreia a categoria TAX com o card "1099-NEC": beneficiário pago por Zelle/wire/cheque com $600+ num ano sem classificação, ou classificado SERVIÇO sem W-9 em arquivo — com o prazo (31/jan) e o valor. A classificação acontece no TAX HUB novo (ADM → TAX HUB, ALPHA v0.1.0); o card cobra. Sinal indisponível não é verde, migration pendente aparece como item.' },
  { version: '1.12.0', date: '2026-08-23', notes: 'CATEGORIAS (nomes em inglês, padrão do app — João): BANK · FINANCIAL · RIDES · INVOICES · INVENTORY · STAFF · TAX · SYSTEM. Chips no topo com contagem viva (✓ = categoria limpa) filtram a tela; cada categoria vira uma seção com seus cards — a conciliação mora em BANK. STAFF, TAX e SYSTEM já estão na ordem esperando seus cards (duty timer com aviso no WhatsApp, 1099-NEC, FL sales tax): toda feature nova chega com as suas checagens.' },
  { version: '1.11.1', date: '2026-08-23', notes: 'Revisão adversarial (29 agentes, 24 defeitos confirmados) sobre o PAID FROM e a régua: item de pedido CASADO com a Regions agora é certo (96 linhas estavam sugerindo GZ28BR com prova de GZ28US!); pedido somado é procurado no extrato pelo TOTAL; SOURCE contradizendo o sinal vira CONFLITO (o ternário antigo dava GZ28BR dos dois lados); antes da conta abrir fica SEM palpite (GZ28BR ou BETO — decisão de gente); filtro de sinal vira dropdown exato ("consta" não pega mais "não consta") e o texto busca também a data; só par sólido (humano ou motor conferido) conta como prova, e DESFAZER um casamento apaga o paid_from que ele justificou; régua tolera entradas pendentes e acusa quando o sinal do banco nem carregou; âncora de extrato com 45+ dias pede o extrato do mês; FIX da milhagem aceitava só 1 dígito (regex sem barras).' },
  { version: '1.11.0', date: '2026-08-22', notes: 'Card "Caixa não bate (banco real × linhas do Bank Link)": o saldo que o Plaid traz do banco agora contra o saldo implícito (último extrato lançado + linhas desde então); diferença além do pendente vira pendência com o tamanho do buraco e a direção (faltam entradas ou saídas). É a régua de tudo — ideia do João (22/ago): se o caixa não bate, nenhum outro número vale. Também acusa Plaid sem resposta e conta sem âncora de extrato.' },
  { version: '1.10.0', date: '2026-08-22', notes: 'PAID FROM com o sinal da Regions: além de "casada" (certo), cada linha diz se é de antes da conta abrir (10/nov/2025 — não foi GZ28US), se "não consta na Regions" (valor igual em ±10d não existe — provavelmente BR ou Beto) ou se "consta" (provavelmente GZ28US); a sugestão pré-carregada segue o sinal. Filtro por mês/invoice/fornecedor/sinal e MARCAR OS N FILTRADOS como GZ28US/GZ28BR/BETO/RAFA de uma vez (só linhas vazias, tudo na trilha). Pensado pra sessão a dois (João + Márcio): decide-se um mês ou um invoice, varre-se de um golpe.' },
  { version: '1.9.0', date: '2026-08-22', notes: 'Card "Lançamentos sem PAID FROM (quem pagou?)": despesas de projeto, custos fixos, folha, goods, inputs e estoque sem paid_from, com FIX por linha (GZ28US/GZ28BR/RAFA/BETO). Linha já casada com a Regions (Bank Link) é GZ28US na certa — botão PREENCHER CERTOS resolve todas de uma vez com trilha; as demais trazem o SOURCE como sugestão pré-carregada. Motivo: paid_from vazio é ruído no pool do motor de conciliação e cega o DFC por caixa.' },
  { version: '1.8.1', date: '2026-08-22', notes: 'Card do banco pós-revisão: nada fica clicável durante um lote (busy é conjunto), plano some quando os dados mudam e APLICAR só roda o plano mostrado, falha no APLICAR recarrega (o servidor pode ter aplicado parte), progresso por fatia, PENDING não deixa casar, chip "data preenchida" em A CONFERIR, contagem do cabeçalho vem do estado.' },
  { version: '1.8.0', date: '2026-08-22', notes: 'Card do banco ganha os motores do Bank Link v0.3.0: bloco MOTORES AUTOMÁTICOS (PLANEJAR → APLICAR), seção A CONFERIR com OK/DESFAZER por linha, DESFAZER LOTE e OK TODAS AS TARIFAS, filtro por motor, chip TARIFA nas linhas que o motor cuida (escondidas por padrão), Enter casa no seletor e no EXPLAIN. Histórico registra cada casamento automático como bank-auto.' },
  { version: '1.7.1', date: '2026-08-21', notes: 'Card do banco: recarrega depois de cada MATCH (candidatos são do servidor), erro de rede/401 aparece no cabeçalho com "tentar de novo" em vez de "carregando" eterno, falha de resposta avisa antes de repetir.' },
  { version: '1.7.0', date: '2026-08-21', notes: 'Card "Banco sem casamento": cada linha da Regions sem par no app, com candidatos automáticos (mesmo valor, data próxima, pedido somado) e decisão na própria linha — MATCH preenche a data de pagamento do app que faltava, TRANSFER/IGNORE tiram da fila, EXPLAIN guarda o que foi. Filtro por nome/valor/data, tudo na trilha.' },
  { version: '1.6.1', date: '2026-08-21', notes: 'Relógio = Orlando: "hoje" dos recebimentos vencidos e do corte de saldo envelhecido deixa o UTC (que vira amanhã depois das 20h) e segue a regra do app.' },
  { version: '1.6.0', date: '2026-08-20', notes: 'Contexto nas linhas: toda pendência de invoice identifica carro · cliente e diz O QUE a linha é — «006.8 Pending balance» virou «006.8 · [cliente] — income Pending balance, vencido em X». Tooltip com o contexto completo.' },
  { version: '1.5.0', date: '2026-08-20', notes: 'Ciclo de entrega: delivery_date e EXPORTED se validam — entrega no passado (invoice fechada) sem selo EXPORTED pede confirmação de um clique (FIX tipo flag, novo); EXPORTED sem delivery date pede o quando. Delivery em invoice aberta é promessa (PROMISED TO) e não conta como saída.' },
  { version: '1.4.0', date: '2026-08-20', notes: 'Insight do Márcio encerra o backfill de conclusion date: CLOSED já exige incomes datados e recebidos, então o mês do resultado DERIVA do último recebimento. O card vira raridade (fechada sem NENHUMA data derivável); conclusion_date explícita continua valendo mais e a trava do fechamento continua capturando ela de graça.' },
  { version: '1.3.0', date: '2026-08-20', notes: 'Sugestão inteligente no conserto de CONCLUSION DATE: o FIX abre pré-carregado com a última atividade do invoice (pagamento recebido ou despesa) — confirma ou ajusta, em vez de reconstruir de memória.' },
  { version: '1.2.0', date: '2026-08-20', notes: 'Conclusion date com semântica certa: só invoice FECHADA sem data é pendência — job em andamento não tem data mesmo, ela nasce no fechamento. E o fechamento agora trava sem a data (oferece hoje com um clique), então o card só encolhe.' },
  { version: '1.1.0', date: '2026-08-20', notes: 'FIX aprende números: card novo "Export sem ADMISSION MILEAGE" lança a milhagem inline (os 24 carros de export sem sair da tela); DESTINY REVIEW fica só com contradições (≥ 100 mi).' },
  { version: '1.0.0', date: '2026-08-20', notes: 'DATA CHECK vira produto próprio, promovido a BETA: bancada de conserto com FIX inline (datas, destinos, tipos, baixas), trilha data_fixes agrupada por sessão, DESTINY REVIEW com a lei do 0km (ADMISSION MILEAGE < 100 mi pros dois tipos de export) e ciclo EXPORTED. Missão: manter os dados do app inteiro completos e corretos — sobre tudo.' },
]
