// Versão da seção FINANCIAL — UM lugar só. Todo patch bumpa FIN_VERSION e
// acrescenta uma linha no topo do changelog (o hub lista, o PDF carimba).
// Quando as demonstrações merecerem, troca FIN_STAGE para 'BETA' aqui e o
// selo muda em todas as telas e relatórios de uma vez.
export const FIN_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'ALPHA'
export const FIN_VERSION = '0.11.6'

export const FIN_CHANGELOG: { version: string; date: string; notes: string }[] = [
  {version: "0.11.6",date: "2026-08-26",notes: "Caso Heraldo/Advanced Transports: o contrato de empréstimo do LEDGERS SALVAVA description mas nunca renderizou a caixa — bug de omissão. Agora NOTES no formulário do contrato (a proveniência mora ali: quem mandou, conf do Zelle, held as CREDIT) e a descrição aparece no card do contrato. O evento (RECEBEU/AMORTIZOU/JUROS) já tinha DESCRIPTION."},
  { version: '0.11.5', date: '2026-08-26', notes: "Sugestão do João no CAPITAL DOS SÓCIOS (LEDGERS): MEMBER vira PARTNER, dropdown com os 3 sócios (Dema, Beto, Heraldo — âmbar enquanto vazio); METHOD vira dropdown do vocabulário universal de pagamento (PAYMENT_METHODS — o mesmo de todo formulário do app), com a opção-fantasma pra valores legados. Vocabulário fechado > texto livre: a lição que a semana inteira ensinou (o campo SOURCE virou lixo de anotações justamente por ser livre)." },
  { version: '0.11.4', date: '2026-08-26', notes: "O TERCEIRO SÓCIO (revelação do João no caso 031.1): a GZ28US tem TRÊS sócios — Marcio/Dema, Beto e HERALDO. Heraldo vira cidadão de primeira classe: opção no PAID FROM (conta paga do bolso dele = empréstimo à LLC), espelho de financiamento no DFC (FUND_HERALDO) e linha própria no passivo do Balanço, exatamente como o Beto. O caso que revelou tudo: os $1.100 da 031.1 são dinheiro do Heraldo parado na conta — nunca foram receita nem adiantamento de cliente; o lugar certo é o LIVRO de empréstimos (financing, credor Heraldo — sócio), e a invoice-recibo se esvazia e morre." },
  {version: "0.11.3",date: "2026-08-26",notes: "A CASA das tarifas (João: “precisamos de um lugar pra elas morarem”): COSTS → BANK FEES (/costs/bank), mesmo padrão de APPS e ASSETS & MKT — totais (desde o início, mês, por família), lista com o selo ⛓ BANCO (linkada à linha que a cobrou) e aviso enquanto o fornecedor não virar cost_type BANK. A listagem FIXED para de mostrar fornecedor BANK; DRE/DFC apontam pra casa nova. O fornecedor Regions Bank continua editável em /costs/fixed/[id]."},
  { version: '0.11.2', date: '2026-08-26', notes: "João, na sessão: \"o motor FEE criou tarifa de wire como CUSTO FIXO?\" — e tinha razão: $1.797 de tarifas bancárias moravam em \"Ocupação, seguros & profissionais\". Nasce o cost_type BANK: linha própria \"(−) Tarifas bancárias\" no OPEX do DRE, linha própria no DFC, opção nas telas de fornecedor, e o motor FEE cria o Regions Bank já como BANK (o existente muda com um update de uma linha). Buraco fechado de quebra: o OPEX dropava cost_type VARIABLE em silêncio (0 fornecedores usam hoje, mas a lista oferecia). PENDENTE DO MÁRCIO: o repasse — wire fee de RECEBIMENTO é causada pelo pagamento do cliente e pode virar despesa da invoice (cobrável); desenhado, não construído, porque mexe em documento de cliente." },
  { version: '0.11.1', date: '2026-08-25', notes: "Classe COLECIONÁVEL (João pegou na hora: Devil170 é Demon 170, produção de UM ano — vai VALORIZAR, não depreciar). Resposta contábil: valorização não entra em livro de custo — fica fora até ser REALIZADA (vira ganho na venda; conservadorismo que a Drummond e o IRS querem) — mas depreciar o chassi seria errado ativo: residual ≥ custo = depreciação zero. A classe separa POR LINHA com o mesmo isCarLine validado: o CHASSI (linhas de carro) ao custo para sempre; os EXPERIMENTOS (mods, motores, dyno) depreciam na vida útil. MIGRATION_g4_colecionavel.sql reclassifica o Devil170." },
  { version: '0.11.0', date: '2026-08-25', notes: "G4 NASCE — o João classificou a frota carro a carro e a última nota de rodapé pendente do DRE virou número vivo. Classes: Devil170 = DESENVOLVIMENTO (laboratório que faz marketing de quebra, 60m), RAMbo = TRABALHO (60m), Trailer = TRABALHO (120m), GENEZIZ = MONUMENTO (a alma da oficina — ao custo, nunca vendido), HellBull e RAM170 = RESERVA (ativo em carteira). Depreciação LINEAR POR LINHA DE CUSTO: cada gasto do carro deprecia da sua própria data — nada de chute de data única. DRE: linha (−) Depreciação da frota viva nas duas visões; Balanço: frota líquida de depreciação com o acumulado no rótulo; MIGRATION_g4_fleet.sql cria as colunas e grava os vereditos. Data Checker fiscaliza: carro OWN/TOOL novo sem classe cai no card novo." },
  { version: '0.10.1', date: '2026-08-25', notes: "João cobrou a promessa que o rodapé do CPV fazia desde o dia 1 (\"inclui frota própria — sai quando D2/D3 fecharem\"): fechou o D2/D3, saiu. Build de carro NOSSO (OWN/TOOL) não é custo de venda — nada foi vendido; é capitalização, e o Balanço já o carrega como Imobilizado — veículos. Agora o CPV exclui a frota própria nas DUAS visões (SÓ A OFICINA e COMPLETO); ela volta ao resultado só via depreciação quando o G4 nascer. DRE e Balanço param de discordar sobre o mesmo dinheiro." },
  { version: '0.10.0', date: '2026-08-25', notes: "CARROS × OFICINA (João resolveu o D2/D3 que estava pendente desde o blueprint): o carro de export passa em valor bruto pela receita e pelo custo e afogava a operação. Detector POR LINHA (≥$15k + vocabulário de carro OU o apelido do próprio ride, com guarda de peça), validado um a um contra as 41 linhas ≥$15k reais — os dois erros achados na validação (Joker pago à KR TX Chrysler sem palavra de carro; Demon 170 Full Engine que é peça) viraram as duas regras extras. DRE: toggle SÓ A OFICINA (padrão — a margem real da operação) × COMPLETO, com o card CARROS (EXPORT) sempre à vista e o PDF carimbando a visão. DFC: seção própria CARROS (recebimentos de invoices com carro — separação de entrada é por invoice, a nota confessa — e compra de carros por linha). Balanço: WIP aberto em oficina × carros de export." },
  { version: '0.9.9', date: '2026-08-25', notes: "A pergunta do João (\"o acumulado não deveria bater com o banco agora?\") é a condição de vitória do sistema inteiro — e virou RÉGUA no topo do DFC: acumulado × saldo do banco (extrato + linhas postadas, leitura grátis), BATE ✓ ou a distância em dólares, com o caminho pra encolhê-la (lançar o TO BOOK e responder o quem-pagou no Data Checker). Medido no dia do lançamento: DFC −$217k × banco +$3k — distância de ~$220k, sendo ~$105k de banco ainda não lançado (entradas de clientes principalmente) e o grosso do resto o paid_from não respondido do legado. Quando esta régua bater, os três demonstrativos e o banco contam a mesma história." },
  { version: '0.9.8', date: '2026-08-25', notes: "DFC honra o QUEM PAGOU (João decidiu a pendência #21 das revisões adversariais — ~$510k de distorção): despesa paga pela GZ28BR, pelo Rafa (entra pela conta corrente BR, decisão de 22/ago) ou pelo Beto NÃO é caixa saindo da GZ28US — a saída operacional fica (o custo é nosso) e nasce a entrada de financiamento espelhada: \"Conta corrente GZ28BR (bancou/recebeu por nós)\" e \"Empréstimo de sócio — Beto\". Recebimento que ficou na GZ28BR ganha o espelho oposto. Efeito no caixa: zero — o DFC finalmente joga no mesmo time do banco (Bank Link) e do Balanço (que já declarava os dois passivos desde a 0.9.6). paid_from vazio segue valendo GZ28US; o card \"Quem pagou?\" do Data Checker encolhe essa incerteza a cada sessão." },
  { version: '0.9.7', date: '2026-08-25', notes: "ENCERRAMENTO FORMAL de assinatura/contrato (João, caso Disney+ que vivia de nota \"deixar morrer\" na descrição): o campo já existia (END DATE / date_conclusion — o gerador de contas para nele), faltava o rito. Botão ENCERRAR na página do fornecedor fixo: grava a data e APAGA as contas agendadas não pagas depois dela (com trilha em data_fixes); selo ENCERRADA no lugar do botão. A vencida anterior ao encerramento continua devida: pague ou apague (write-off), decisão humana. Sem migration — só o rito que faltava pro campo que já existia." },
  { version: '0.9.6', date: '2026-08-22', notes: 'Balanço: "Empréstimo de sócio — Beto" no passivo — contas da LLC pagas do bolso do Beto (paid_from = BETO) deixam de passar por caixa da empresa e viram dívida com o sócio. RAFA era sócio da GZ28BR e fica fora do Balanço dos EUA. Conta corrente GZ28BR inalterada. Ainda depende do Data Checker preencher o PAID FROM (950 linhas vazias em 22/ago).' },
  { version: '0.9.5', date: '2026-08-20', notes: 'G1 destravado (insight do Márcio): recognitionDate() deriva o mês do resultado de invoice fechado — conclusion_date explícita > delivery_date > último recebimento. DRE por período fica pronta pra nascer junto com D1/D2.' },
  { version: '0.9.4', date: '2026-08-20', notes: 'Fechar invoice exige CONCLUSION DATE (a trava oferece hoje com um clique); aviso G1 da DRE conta só as fechadas sem data — job em andamento é WIP sob D2, não pendência.' },
  { version: '0.9.3', date: '2026-08-20', notes: 'Hub: os 4 cards em 2×2 folgado (4 numa linha espremia título, selo e descrição), selo de status sem quebra de linha, texto de intro atualizado e changelog alinhado à grade.' },
  { version: '0.9.2', date: '2026-08-20', notes: 'Conserto do hub FINANCIAL (a remoção do card DATA CHECK tinha duplicado o LEDGERS e mantido o CHECK) e DATA CHECK à prova de migration: rides agora via select(*) — coluna ainda não migrada (caso exported) vira undefined em vez de derrubar a tela.' },
  { version: '0.9.1', date: '2026-08-20', notes: 'DATA CHECK promovido a ferramenta de organização do app inteiro: sai do hub FINANCIAL e vira item próprio do ADM (/adm/check, com redirect do caminho antigo).' },
  { version: '0.9.0', date: '2026-08-20', notes: 'Status EXPORTED (MIGRATION_ride_exported.sql): checkbox nos dois tipos de export marcando o embarque — fim do ciclo na GZ28US. Num GZ28 EXPORT o carro sai do nome da LLC (vira ride da GZ28BR). Badge EXPORTED no ride, custo do job sai do WIP do Balanço e da nota da DRE; DESTINY REVIEW acusa EXPORTED em destino que não é de exportação.' },
  { version: '0.8.0', date: '2026-08-20', notes: 'Destinos renomeados: EXPORT vira GZ28 EXPORT e OWNER HANDLES vira 3RD PARTY EXPORT — a frota legada sempre foi exportação por terceiro. DELIVERY MILES vira fato medido: campo ADMISSION MILEAGE no ride (MIGRATION_ride_admission_mileage.sql) substitui o checkbox; entrada < 100 mi pode exportar, >= 100 não pode — regra vale pros DOIS tipos de export no DESTINY REVIEW.' },
  { version: '0.7.0', date: '2026-08-20', notes: 'Nova categoria de destino: DONOR — PART-OUT (carcaça comprada pra virar estoque de peças, casos C7 Burnt e ScatPrisionPack). Balanço ganha a linha Carros doadores; doador não gera A/R nem adiantamento (crédito de peça puxada é normal). DATA CHECK passa a listar TODA ride real sem destino, mesmo sem invoice.' },
  { version: '0.6.3', date: '2026-08-20', notes: 'Selo renomeado: BRAND NEW (0 KM) vira DELIVERY MILES — mesmo campo (rides.is_brand_new), só o nome de cara em edit, detalhe e DESTINY REVIEW.' },
  { version: '0.6.2', date: '2026-08-20', notes: 'Selo BRAND NEW (0 KM) declarado no ride (checkbox no edit, badge no detalhe — MIGRATION_ride_brand_new.sql): milhagem sozinha não prova carro novo (0km chega com 9 ou 46 mi). DESTINY REVIEW passa a exigir o selo em EXPORT e usa teto de 100 mi como conferência.' },
  { version: '0.6.1', date: '2026-08-20', notes: 'DESTINY REVIEW aprende a lei: só carro 0km exporta pro Brasil. Cliente brasileiro com carro usado nos EUA é normal (residência) — flag removida; a contradição real é EXPORT em carro com milhagem de usado, que agora é acusada.' },
  { version: '0.6.0', date: '2026-08-20', notes: 'DATA CHECK vira bancada: conserto de um campo acontece na própria linha (FIX — data, destino, tipo de fornecedor, baixa de recebimento), links de contexto abrem em aba nova, REFRESH re-audita sem perder o lugar. HISTÓRICO agrupa os consertos por sessão (tabela data_fixes — MIGRATION_data_fixes.sql). DESTINY REVIEW cruza cada destino com o dinheiro do carro e acusa contradições, inclusive de mudanças feitas fora da tela.' },
  { version: '0.5.3', date: '2026-08-20', notes: 'EMPRÉSTIMOS: DatePicker sempre em linha própria (estava espremido em meia coluna) e formulário de evento recolhido atrás de um + ADD EVENT por contrato — o card mostra só cabeçalho, saldo devedor e histórico até você querer lançar.' },
  { version: '0.5.2', date: '2026-08-20', notes: 'LEDGERS redesenhado no idioma do app (padrão costs/fixed/new): formulário empilhado com input grande, DatePicker inteiro, valor com prefixo $, botão verde de salvar, listas em card com selo colorido por tipo.' },
  { version: '0.5.1', date: '2026-08-20', notes: 'LEDGERS: seletor de data em modo compacto com duas colunas de largura — os três selects do DatePicker transbordavam a célula e cobriam os campos vizinhos.' },
  { version: '0.5.0', date: '2026-08-20', notes: 'Fase 2 — LEDGERS: capital dos sócios, empréstimos (contratos + recebeu/amortizou/juros) e saldos de caixa por conta, com tela própria e migration (MIGRATION_financial_ledgers.sql). DFC ganha a seção de financiamento completa; DRE ganha o resultado financeiro; Balanço ganha caixa, dívida, capital e o residual do patrimônio; DATA CHECK vigia saldo envelhecido.' },
  { version: '0.4.1', date: '2026-08-19', notes: 'Revisão adversarial (27 agentes, 4 lentes): 9 correções — filhas de QUOTE fora de tudo (eram $206k de fornecedores-fantasma no Balanço), paginação com ORDER BY estável, caixa na data real do recebimento (paid_at), custos ASSET na DRE, good_expenses acima do piso capitalizam, inputs sem categoria não somem, intercompany só conta o pago, carro OWN/TOOL não gera A/R nem FL tax, margem com guarda de zero.' },
  { version: '0.4.0', date: '2026-08-19', notes: 'DATA CHECK: checklist do que trava as demonstrações — invoices sem conclusion date, rides sem CAR DESTINY, pagamentos sem data, jobs legados sem linhas, fornecedores sem tipo, recebimentos vencidos sem baixa — com contagem, impacto em $ e link direto pro conserto.' },
  { version: '0.3.0', date: '2026-08-19', notes: 'Selo ALPHA + versionamento com changelog; versão carimbada nas telas e no rodapé dos PDFs.' },
  { version: '0.2.0', date: '2026-08-19', notes: 'Interface gráfica: KPIs e gráfico entradas×saídas com acumulado (DFC), cascata receita→EBITDA e abertura do OPEX (DRE), composição do ativo e do passivo (Balanço); download de PDF vetorial nas três telas.' },
  { version: '0.1.0', date: '2026-08-19', notes: 'Seção FINANCIAL no ADM: DFC método direto com drill até a linha de origem, DRE acumulada as-booked, Balanço parcial com gaps na cara; dataset único em lib/financials.' },
]
