// ("WHATSAPP HUB" no nascimento; INTERCOM desde 24/ago — escolha do João: sóbrio, negócio, como os outros fronts.)
// Versão do INTERCOM — o espelho permanente dos 2 WhatsApp (US + BR) e a
// tela /whatsapp. Produto próprio desde 24/ago/2026 (ordem do Márcio: "não sou
// feliz com a forma que você acessa o WhatsApp — quero uma forma mais direta").
// Todo patch bumpa WA_VERSION e acrescenta uma linha no changelog.
export const WA_STAGE: 'ALPHA' | 'BETA' | 'STABLE' = 'ALPHA'
export const WA_VERSION = '0.3.2'

export const WA_CHANGELOG: { version: string; date: string; notes: string }[
  { version: '0.3.2', date: '2026-08-24', notes: 'A POLÍTICA É DA CONVERSA, NÃO DA CÓPIA. Marcar IGNORE/MENTION_ONLY atualizava só as linhas de whatsapp_chats que já existiam — se o mesmo contato ainda não tinha cópia no outro número, ela nascia depois com o default ALL e a conversa voltava pro round. Aconteceu na hora com o robô de cobrança 4004-1144, que escreve pros DOIS números: IGNORE na cópia BR, e minutos depois a cópia US apareceu e recolocou a cobrança na fila. Agora o POST /api/whatsapp/inbox faz UPSERT dos dois lados, criando a linha do número que ainda não recebeu — a decisão passa a valer antes da primeira mensagem chegar lá.' },] = [
  { version: '0.3.1',date: '2026-08-24',notes: 'CORREÇÃO GRAVE NO ROUND — o teto de 1000 linhas do PostgREST. A rota /api/whatsapp/round pedia .limit(3000) nos chats e .limit(20000) nas mensagens, mas o PostgREST devolve no máximo 1000 linhas por request e ignora o limite em silêncio: o round enxergava 1000 dos 1369 chats (369 sorteados fora, independente de quão recentes) e só as 1000 mensagens mais novas da janela. Resultado: respondeu ZERO PENDENTES com 100 conversas esperando resposta — ele viu na hora (não, tem mais um monte de msg). Agora as duas leituras paginam de 1000 em 1000 até o fim, com ordenação estável (app+chat_id nos chats, sent_at+id nas mensagens) pra página não repetir nem pular linha. O vigia do round, que lê a mesma rota, também estava cego pelo mesmo motivo.' },
  { version: '0.3.0', date: '2026-08-24', notes: 'O ROUND VIRA DO APP (ordem do Márcio: "você aqui tem que ser só UMA INTERFACE do APP; tudo que puder ficar lá tem que ficar"). Nova rota /api/whatsapp/round devolve a PRÓXIMA conversa não-processada — a regra saiu do script da assistente e virou do app. Marca dágua por conversa (whatsapp_chats.processed_through/processed_at/processed_note): processada é tudo ATÉ aquele instante, e mensagem posterior REABRE a conversa sozinha; botão MARCAR PROCESSADO na tela e placar NO ROUND. Política de pauta por conversa (v0.2.0, mesma leva): ALL / MENTION_ONLY / IGNORE, com seletor na tela — GZ28BR-STAFF já em MENTION_ONLY. Captura de marcações (mentioned_ids do webhook nos 2 números): o corpo mostra @<LID>, nunca o telefone, então só o payload diz quem foi marcado. Fuso pelo ASSUNTO: grupo GZ28US é Orlando mesmo lido pela cópia BR.' },
  { version: '0.1.0', date: '2026-08-24', notes: 'Nasce o INTERCOM. Espelho permanente: TODA mensagem dos 2 números (US e BR) vira linha em whatsapp_messages no Supabase US — webhook em tempo real (widen do webhook do FINANCEIRO, agora TODOS os chats) + cron whatsapp-sync 10/10min como rede de segurança (snapshot de chats, releitura dos que mexeram, log da instância pra mídia). Modo deep (?deep=1) faz o backfill do que a UltraMsg ainda guarda. Tela /whatsapp (ADM → INTERCOM): os dois números numa inbox só, chips ALL/US/BR, busca em chats e mensagens, conversa com mídia, resposta dali mesmo (personal por padrão; BR sai pelo relay → app BR), horário no fuso do assunto (Orlando US / Brasília BR). MCP server local (scripts/whatsapp-mcp.mjs) — o WhatsApp vira ferramenta nativa da assistente: wa_chats, wa_messages, wa_search, wa_unanswered, wa_send.' },
]
